# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['ApplicationArgs', 'Application']

@pulumi.input_type
class ApplicationArgs:
    def __init__(__self__, *,
                 environment_id: pulumi.Input[_builtins.str],
                 name: pulumi.Input[_builtins.str],
                 source: pulumi.Input['ApplicationSourceArgs'],
                 app_name: pulumi.Input[Optional[_builtins.str]] = None,
                 build_args: pulumi.Input[Optional[_builtins.str]] = None,
                 build_registry_id: pulumi.Input[Optional[_builtins.str]] = None,
                 build_secrets: pulumi.Input[Optional[_builtins.str]] = None,
                 create_env_file: pulumi.Input[Optional[_builtins.bool]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 environment: pulumi.Input[Optional[_builtins.str]] = None,
                 registry_id: pulumi.Input[Optional[_builtins.str]] = None,
                 server_id: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a Application resource.

        :param pulumi.Input[_builtins.str] environment_id: The target environment ID.
        :param pulumi.Input[_builtins.str] name: The application name.
        :param pulumi.Input['ApplicationSourceArgs'] source: The application source configuration.
        :param pulumi.Input[_builtins.str] app_name: The optional deployed application name.
        :param pulumi.Input[_builtins.str] build_args: Build arguments for the application.
        :param pulumi.Input[_builtins.str] build_registry_id: The optional build registry ID.
        :param pulumi.Input[_builtins.str] build_secrets: Build secrets for the application.
        :param pulumi.Input[_builtins.bool] create_env_file: Whether to create an environment file.
        :param pulumi.Input[_builtins.str] description: An optional application description.
        :param pulumi.Input[_builtins.str] environment: Environment variables for the application.
        :param pulumi.Input[_builtins.str] registry_id: The optional deployment registry ID.
        :param pulumi.Input[_builtins.str] server_id: The optional server ID.
        """
        pulumi.set(__self__, "environment_id", environment_id)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "source", source)
        if app_name is not None:
            pulumi.set(__self__, "app_name", app_name)
        if build_args is not None:
            pulumi.set(__self__, "build_args", build_args)
        if build_registry_id is not None:
            pulumi.set(__self__, "build_registry_id", build_registry_id)
        if build_secrets is not None:
            pulumi.set(__self__, "build_secrets", build_secrets)
        if create_env_file is not None:
            pulumi.set(__self__, "create_env_file", create_env_file)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if environment is not None:
            pulumi.set(__self__, "environment", environment)
        if registry_id is not None:
            pulumi.set(__self__, "registry_id", registry_id)
        if server_id is not None:
            pulumi.set(__self__, "server_id", server_id)

    @_builtins.property
    @pulumi.getter(name="environmentId")
    def environment_id(self) -> pulumi.Input[_builtins.str]:
        """
        The target environment ID.
        """
        return pulumi.get(self, "environment_id")

    @environment_id.setter
    def environment_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "environment_id", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        The application name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def source(self) -> pulumi.Input['ApplicationSourceArgs']:
        """
        The application source configuration.
        """
        return pulumi.get(self, "source")

    @source.setter
    def source(self, value: pulumi.Input['ApplicationSourceArgs']):
        pulumi.set(self, "source", value)

    @_builtins.property
    @pulumi.getter(name="appName")
    def app_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The optional deployed application name.
        """
        return pulumi.get(self, "app_name")

    @app_name.setter
    def app_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "app_name", value)

    @_builtins.property
    @pulumi.getter(name="buildArgs")
    def build_args(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Build arguments for the application.
        """
        return pulumi.get(self, "build_args")

    @build_args.setter
    def build_args(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "build_args", value)

    @_builtins.property
    @pulumi.getter(name="buildRegistryId")
    def build_registry_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The optional build registry ID.
        """
        return pulumi.get(self, "build_registry_id")

    @build_registry_id.setter
    def build_registry_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "build_registry_id", value)

    @_builtins.property
    @pulumi.getter(name="buildSecrets")
    def build_secrets(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Build secrets for the application.
        """
        return pulumi.get(self, "build_secrets")

    @build_secrets.setter
    def build_secrets(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "build_secrets", value)

    @_builtins.property
    @pulumi.getter(name="createEnvFile")
    def create_env_file(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to create an environment file.
        """
        return pulumi.get(self, "create_env_file")

    @create_env_file.setter
    def create_env_file(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "create_env_file", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        An optional application description.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def environment(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Environment variables for the application.
        """
        return pulumi.get(self, "environment")

    @environment.setter
    def environment(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "environment", value)

    @_builtins.property
    @pulumi.getter(name="registryId")
    def registry_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The optional deployment registry ID.
        """
        return pulumi.get(self, "registry_id")

    @registry_id.setter
    def registry_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "registry_id", value)

    @_builtins.property
    @pulumi.getter(name="serverId")
    def server_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The optional server ID.
        """
        return pulumi.get(self, "server_id")

    @server_id.setter
    def server_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "server_id", value)


@pulumi.type_token("dokploy:index:Application")
class Application(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 app_name: pulumi.Input[Optional[_builtins.str]] = None,
                 build_args: pulumi.Input[Optional[_builtins.str]] = None,
                 build_registry_id: pulumi.Input[Optional[_builtins.str]] = None,
                 build_secrets: pulumi.Input[Optional[_builtins.str]] = None,
                 create_env_file: pulumi.Input[Optional[_builtins.bool]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 environment: pulumi.Input[Optional[_builtins.str]] = None,
                 environment_id: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 registry_id: pulumi.Input[Optional[_builtins.str]] = None,
                 server_id: pulumi.Input[Optional[_builtins.str]] = None,
                 source: pulumi.Input[Optional[Union['ApplicationSourceArgs', 'ApplicationSourceArgsDict']]] = None,
                 __props__=None):
        """
        A Dokploy application.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] app_name: The optional deployed application name.
        :param pulumi.Input[_builtins.str] build_args: Build arguments for the application.
        :param pulumi.Input[_builtins.str] build_registry_id: The optional build registry ID.
        :param pulumi.Input[_builtins.str] build_secrets: Build secrets for the application.
        :param pulumi.Input[_builtins.bool] create_env_file: Whether to create an environment file.
        :param pulumi.Input[_builtins.str] description: An optional application description.
        :param pulumi.Input[_builtins.str] environment: Environment variables for the application.
        :param pulumi.Input[_builtins.str] environment_id: The target environment ID.
        :param pulumi.Input[_builtins.str] name: The application name.
        :param pulumi.Input[_builtins.str] registry_id: The optional deployment registry ID.
        :param pulumi.Input[_builtins.str] server_id: The optional server ID.
        :param pulumi.Input[Union['ApplicationSourceArgs', 'ApplicationSourceArgsDict']] source: The application source configuration.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ApplicationArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        A Dokploy application.

        :param str resource_name: The name of the resource.
        :param ApplicationArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ApplicationArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 app_name: pulumi.Input[Optional[_builtins.str]] = None,
                 build_args: pulumi.Input[Optional[_builtins.str]] = None,
                 build_registry_id: pulumi.Input[Optional[_builtins.str]] = None,
                 build_secrets: pulumi.Input[Optional[_builtins.str]] = None,
                 create_env_file: pulumi.Input[Optional[_builtins.bool]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 environment: pulumi.Input[Optional[_builtins.str]] = None,
                 environment_id: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 registry_id: pulumi.Input[Optional[_builtins.str]] = None,
                 server_id: pulumi.Input[Optional[_builtins.str]] = None,
                 source: pulumi.Input[Optional[Union['ApplicationSourceArgs', 'ApplicationSourceArgsDict']]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ApplicationArgs.__new__(ApplicationArgs)

            __props__.__dict__["app_name"] = app_name
            __props__.__dict__["build_args"] = None if build_args is None else pulumi.Output.secret(build_args)
            __props__.__dict__["build_registry_id"] = build_registry_id
            __props__.__dict__["build_secrets"] = None if build_secrets is None else pulumi.Output.secret(build_secrets)
            __props__.__dict__["create_env_file"] = create_env_file
            __props__.__dict__["description"] = description
            __props__.__dict__["environment"] = None if environment is None else pulumi.Output.secret(environment)
            if environment_id is None and not opts.urn:
                raise TypeError("Missing required property 'environment_id'")
            __props__.__dict__["environment_id"] = environment_id
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["registry_id"] = registry_id
            __props__.__dict__["server_id"] = server_id
            if source is None and not opts.urn:
                raise TypeError("Missing required property 'source'")
            __props__.__dict__["source"] = source
            __props__.__dict__["application_id"] = None
            __props__.__dict__["status"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["buildArgs", "buildSecrets", "environment"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        replace_on_changes = pulumi.ResourceOptions(replace_on_changes=["environmentId", "serverId"])
        opts = pulumi.ResourceOptions.merge(opts, replace_on_changes)
        super(Application, __self__).__init__(
            'dokploy:index:Application',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Application':
        """
        Get an existing Application resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = ApplicationArgs.__new__(ApplicationArgs)

        __props__.__dict__["app_name"] = None
        __props__.__dict__["application_id"] = None
        __props__.__dict__["build_args"] = None
        __props__.__dict__["build_registry_id"] = None
        __props__.__dict__["build_secrets"] = None
        __props__.__dict__["create_env_file"] = None
        __props__.__dict__["description"] = None
        __props__.__dict__["environment"] = None
        __props__.__dict__["environment_id"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["registry_id"] = None
        __props__.__dict__["server_id"] = None
        __props__.__dict__["source"] = None
        __props__.__dict__["status"] = None
        return Application(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="appName")
    def app_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The optional deployed application name.
        """
        return pulumi.get(self, "app_name")

    @_builtins.property
    @pulumi.getter(name="applicationId")
    def application_id(self) -> pulumi.Output[_builtins.str]:
        """
        The stable Dokploy application ID.
        """
        return pulumi.get(self, "application_id")

    @_builtins.property
    @pulumi.getter(name="buildArgs")
    def build_args(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Build arguments for the application.
        """
        return pulumi.get(self, "build_args")

    @_builtins.property
    @pulumi.getter(name="buildRegistryId")
    def build_registry_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The optional build registry ID.
        """
        return pulumi.get(self, "build_registry_id")

    @_builtins.property
    @pulumi.getter(name="buildSecrets")
    def build_secrets(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Build secrets for the application.
        """
        return pulumi.get(self, "build_secrets")

    @_builtins.property
    @pulumi.getter(name="createEnvFile")
    def create_env_file(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether to create an environment file.
        """
        return pulumi.get(self, "create_env_file")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        An optional application description.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def environment(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Environment variables for the application.
        """
        return pulumi.get(self, "environment")

    @_builtins.property
    @pulumi.getter(name="environmentId")
    def environment_id(self) -> pulumi.Output[_builtins.str]:
        """
        The target environment ID.
        """
        return pulumi.get(self, "environment_id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The application name.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="registryId")
    def registry_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The optional deployment registry ID.
        """
        return pulumi.get(self, "registry_id")

    @_builtins.property
    @pulumi.getter(name="serverId")
    def server_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The optional server ID.
        """
        return pulumi.get(self, "server_id")

    @_builtins.property
    @pulumi.getter
    def source(self) -> pulumi.Output['outputs.ApplicationSource']:
        """
        The application source configuration.
        """
        return pulumi.get(self, "source")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output[_builtins.str]:
        """
        The current application deployment status.
        """
        return pulumi.get(self, "status")

