# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['BackupArgs', 'Backup']

@pulumi.input_type
class BackupArgs:
    def __init__(__self__, *,
                 database: pulumi.Input[_builtins.str],
                 destination_id: pulumi.Input[_builtins.str],
                 prefix: pulumi.Input[_builtins.str],
                 schedule: pulumi.Input[_builtins.str],
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 keep_latest_count: pulumi.Input[Optional[_builtins.int]] = None,
                 mariadb_id: pulumi.Input[Optional[_builtins.str]] = None,
                 mongo_id: pulumi.Input[Optional[_builtins.str]] = None,
                 mysql_id: pulumi.Input[Optional[_builtins.str]] = None,
                 postgres_id: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a Backup resource.

        :param pulumi.Input[_builtins.str] database: The database name inside the target instance to back up.
        :param pulumi.Input[_builtins.str] destination_id: The destination ID backups are stored to.
        :param pulumi.Input[_builtins.str] prefix: The backup file prefix.
        :param pulumi.Input[_builtins.str] schedule: The backup cron schedule.
        :param pulumi.Input[_builtins.bool] enabled: Whether the backup schedule is enabled.
        :param pulumi.Input[_builtins.int] keep_latest_count: The optional number of most recent backups to retain.
        :param pulumi.Input[_builtins.str] mariadb_id: The target MariaDB ID.
        :param pulumi.Input[_builtins.str] mongo_id: The target MongoDB ID.
        :param pulumi.Input[_builtins.str] mysql_id: The target MySQL ID.
        :param pulumi.Input[_builtins.str] postgres_id: The target Postgres ID.
        """
        pulumi.set(__self__, "database", database)
        pulumi.set(__self__, "destination_id", destination_id)
        pulumi.set(__self__, "prefix", prefix)
        pulumi.set(__self__, "schedule", schedule)
        if enabled is None:
            enabled = True
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if keep_latest_count is not None:
            pulumi.set(__self__, "keep_latest_count", keep_latest_count)
        if mariadb_id is not None:
            pulumi.set(__self__, "mariadb_id", mariadb_id)
        if mongo_id is not None:
            pulumi.set(__self__, "mongo_id", mongo_id)
        if mysql_id is not None:
            pulumi.set(__self__, "mysql_id", mysql_id)
        if postgres_id is not None:
            pulumi.set(__self__, "postgres_id", postgres_id)

    @_builtins.property
    @pulumi.getter
    def database(self) -> pulumi.Input[_builtins.str]:
        """
        The database name inside the target instance to back up.
        """
        return pulumi.get(self, "database")

    @database.setter
    def database(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "database", value)

    @_builtins.property
    @pulumi.getter(name="destinationId")
    def destination_id(self) -> pulumi.Input[_builtins.str]:
        """
        The destination ID backups are stored to.
        """
        return pulumi.get(self, "destination_id")

    @destination_id.setter
    def destination_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "destination_id", value)

    @_builtins.property
    @pulumi.getter
    def prefix(self) -> pulumi.Input[_builtins.str]:
        """
        The backup file prefix.
        """
        return pulumi.get(self, "prefix")

    @prefix.setter
    def prefix(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "prefix", value)

    @_builtins.property
    @pulumi.getter
    def schedule(self) -> pulumi.Input[_builtins.str]:
        """
        The backup cron schedule.
        """
        return pulumi.get(self, "schedule")

    @schedule.setter
    def schedule(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "schedule", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the backup schedule is enabled.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter(name="keepLatestCount")
    def keep_latest_count(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        The optional number of most recent backups to retain.
        """
        return pulumi.get(self, "keep_latest_count")

    @keep_latest_count.setter
    def keep_latest_count(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "keep_latest_count", value)

    @_builtins.property
    @pulumi.getter(name="mariadbId")
    def mariadb_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The target MariaDB ID.
        """
        return pulumi.get(self, "mariadb_id")

    @mariadb_id.setter
    def mariadb_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "mariadb_id", value)

    @_builtins.property
    @pulumi.getter(name="mongoId")
    def mongo_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The target MongoDB ID.
        """
        return pulumi.get(self, "mongo_id")

    @mongo_id.setter
    def mongo_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "mongo_id", value)

    @_builtins.property
    @pulumi.getter(name="mysqlId")
    def mysql_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The target MySQL ID.
        """
        return pulumi.get(self, "mysql_id")

    @mysql_id.setter
    def mysql_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "mysql_id", value)

    @_builtins.property
    @pulumi.getter(name="postgresId")
    def postgres_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The target Postgres ID.
        """
        return pulumi.get(self, "postgres_id")

    @postgres_id.setter
    def postgres_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "postgres_id", value)


@pulumi.type_token("dokploy:index:Backup")
class Backup(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 database: pulumi.Input[Optional[_builtins.str]] = None,
                 destination_id: pulumi.Input[Optional[_builtins.str]] = None,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 keep_latest_count: pulumi.Input[Optional[_builtins.int]] = None,
                 mariadb_id: pulumi.Input[Optional[_builtins.str]] = None,
                 mongo_id: pulumi.Input[Optional[_builtins.str]] = None,
                 mysql_id: pulumi.Input[Optional[_builtins.str]] = None,
                 postgres_id: pulumi.Input[Optional[_builtins.str]] = None,
                 prefix: pulumi.Input[Optional[_builtins.str]] = None,
                 schedule: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        A scheduled Dokploy database backup. Exactly one of postgresId, mysqlId, mariadbId, or mongoId must be set.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] database: The database name inside the target instance to back up.
        :param pulumi.Input[_builtins.str] destination_id: The destination ID backups are stored to.
        :param pulumi.Input[_builtins.bool] enabled: Whether the backup schedule is enabled.
        :param pulumi.Input[_builtins.int] keep_latest_count: The optional number of most recent backups to retain.
        :param pulumi.Input[_builtins.str] mariadb_id: The target MariaDB ID.
        :param pulumi.Input[_builtins.str] mongo_id: The target MongoDB ID.
        :param pulumi.Input[_builtins.str] mysql_id: The target MySQL ID.
        :param pulumi.Input[_builtins.str] postgres_id: The target Postgres ID.
        :param pulumi.Input[_builtins.str] prefix: The backup file prefix.
        :param pulumi.Input[_builtins.str] schedule: The backup cron schedule.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: BackupArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        A scheduled Dokploy database backup. Exactly one of postgresId, mysqlId, mariadbId, or mongoId must be set.

        :param str resource_name: The name of the resource.
        :param BackupArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(BackupArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 database: pulumi.Input[Optional[_builtins.str]] = None,
                 destination_id: pulumi.Input[Optional[_builtins.str]] = None,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 keep_latest_count: pulumi.Input[Optional[_builtins.int]] = None,
                 mariadb_id: pulumi.Input[Optional[_builtins.str]] = None,
                 mongo_id: pulumi.Input[Optional[_builtins.str]] = None,
                 mysql_id: pulumi.Input[Optional[_builtins.str]] = None,
                 postgres_id: pulumi.Input[Optional[_builtins.str]] = None,
                 prefix: pulumi.Input[Optional[_builtins.str]] = None,
                 schedule: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = BackupArgs.__new__(BackupArgs)

            if database is None and not opts.urn:
                raise TypeError("Missing required property 'database'")
            __props__.__dict__["database"] = database
            if destination_id is None and not opts.urn:
                raise TypeError("Missing required property 'destination_id'")
            __props__.__dict__["destination_id"] = destination_id
            if enabled is None:
                enabled = True
            __props__.__dict__["enabled"] = enabled
            __props__.__dict__["keep_latest_count"] = keep_latest_count
            __props__.__dict__["mariadb_id"] = mariadb_id
            __props__.__dict__["mongo_id"] = mongo_id
            __props__.__dict__["mysql_id"] = mysql_id
            __props__.__dict__["postgres_id"] = postgres_id
            if prefix is None and not opts.urn:
                raise TypeError("Missing required property 'prefix'")
            __props__.__dict__["prefix"] = prefix
            if schedule is None and not opts.urn:
                raise TypeError("Missing required property 'schedule'")
            __props__.__dict__["schedule"] = schedule
            __props__.__dict__["backup_id"] = None
        replace_on_changes = pulumi.ResourceOptions(replace_on_changes=["mariadbId", "mongoId", "mysqlId", "postgresId"])
        opts = pulumi.ResourceOptions.merge(opts, replace_on_changes)
        super(Backup, __self__).__init__(
            'dokploy:index:Backup',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Backup':
        """
        Get an existing Backup resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = BackupArgs.__new__(BackupArgs)

        __props__.__dict__["backup_id"] = None
        __props__.__dict__["database"] = None
        __props__.__dict__["destination_id"] = None
        __props__.__dict__["enabled"] = None
        __props__.__dict__["keep_latest_count"] = None
        __props__.__dict__["mariadb_id"] = None
        __props__.__dict__["mongo_id"] = None
        __props__.__dict__["mysql_id"] = None
        __props__.__dict__["postgres_id"] = None
        __props__.__dict__["prefix"] = None
        __props__.__dict__["schedule"] = None
        return Backup(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="backupId")
    def backup_id(self) -> pulumi.Output[_builtins.str]:
        """
        The stable Dokploy backup ID.
        """
        return pulumi.get(self, "backup_id")

    @_builtins.property
    @pulumi.getter
    def database(self) -> pulumi.Output[_builtins.str]:
        """
        The database name inside the target instance to back up.
        """
        return pulumi.get(self, "database")

    @_builtins.property
    @pulumi.getter(name="destinationId")
    def destination_id(self) -> pulumi.Output[_builtins.str]:
        """
        The destination ID backups are stored to.
        """
        return pulumi.get(self, "destination_id")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether the backup schedule is enabled.
        """
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter(name="keepLatestCount")
    def keep_latest_count(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        The optional number of most recent backups to retain.
        """
        return pulumi.get(self, "keep_latest_count")

    @_builtins.property
    @pulumi.getter(name="mariadbId")
    def mariadb_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The target MariaDB ID.
        """
        return pulumi.get(self, "mariadb_id")

    @_builtins.property
    @pulumi.getter(name="mongoId")
    def mongo_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The target MongoDB ID.
        """
        return pulumi.get(self, "mongo_id")

    @_builtins.property
    @pulumi.getter(name="mysqlId")
    def mysql_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The target MySQL ID.
        """
        return pulumi.get(self, "mysql_id")

    @_builtins.property
    @pulumi.getter(name="postgresId")
    def postgres_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The target Postgres ID.
        """
        return pulumi.get(self, "postgres_id")

    @_builtins.property
    @pulumi.getter
    def prefix(self) -> pulumi.Output[_builtins.str]:
        """
        The backup file prefix.
        """
        return pulumi.get(self, "prefix")

    @_builtins.property
    @pulumi.getter
    def schedule(self) -> pulumi.Output[_builtins.str]:
        """
        The backup cron schedule.
        """
        return pulumi.get(self, "schedule")

