# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetRedisResult',
    'AwaitableGetRedisResult',
    'get_redis',
    'get_redis_output',
]

@pulumi.output_type
class GetRedisResult:
    def __init__(__self__, app_name=None, description=None, docker_image=None, environment_id=None, external_port=None, name=None, redis_id=None, server_id=None, status=None):
        if app_name and not isinstance(app_name, str):
            raise TypeError("Expected argument 'app_name' to be a str")
        pulumi.set(__self__, "app_name", app_name)
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if docker_image and not isinstance(docker_image, str):
            raise TypeError("Expected argument 'docker_image' to be a str")
        pulumi.set(__self__, "docker_image", docker_image)
        if environment_id and not isinstance(environment_id, str):
            raise TypeError("Expected argument 'environment_id' to be a str")
        pulumi.set(__self__, "environment_id", environment_id)
        if external_port and not isinstance(external_port, int):
            raise TypeError("Expected argument 'external_port' to be a int")
        pulumi.set(__self__, "external_port", external_port)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if redis_id and not isinstance(redis_id, str):
            raise TypeError("Expected argument 'redis_id' to be a str")
        pulumi.set(__self__, "redis_id", redis_id)
        if server_id and not isinstance(server_id, str):
            raise TypeError("Expected argument 'server_id' to be a str")
        pulumi.set(__self__, "server_id", server_id)
        if status and not isinstance(status, str):
            raise TypeError("Expected argument 'status' to be a str")
        pulumi.set(__self__, "status", status)

    @_builtins.property
    @pulumi.getter(name="appName")
    def app_name(self) -> Optional[_builtins.str]:
        """
        The optional application name metadata.
        """
        return pulumi.get(self, "app_name")

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[_builtins.str]:
        """
        The optional description metadata.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="dockerImage")
    def docker_image(self) -> Optional[_builtins.str]:
        """
        The optional Docker image metadata.
        """
        return pulumi.get(self, "docker_image")

    @_builtins.property
    @pulumi.getter(name="environmentId")
    def environment_id(self) -> Optional[_builtins.str]:
        """
        The optional environment ID metadata.
        """
        return pulumi.get(self, "environment_id")

    @_builtins.property
    @pulumi.getter(name="externalPort")
    def external_port(self) -> Optional[_builtins.int]:
        """
        The optional external port.
        """
        return pulumi.get(self, "external_port")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The Redis database name.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="redisId")
    def redis_id(self) -> _builtins.str:
        """
        The stable Dokploy Redis ID.
        """
        return pulumi.get(self, "redis_id")

    @_builtins.property
    @pulumi.getter(name="serverId")
    def server_id(self) -> Optional[_builtins.str]:
        """
        The optional server ID metadata.
        """
        return pulumi.get(self, "server_id")

    @_builtins.property
    @pulumi.getter
    def status(self) -> Optional[_builtins.str]:
        """
        The optional application status.
        """
        return pulumi.get(self, "status")


class AwaitableGetRedisResult(GetRedisResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetRedisResult(
            app_name=self.app_name,
            description=self.description,
            docker_image=self.docker_image,
            environment_id=self.environment_id,
            external_port=self.external_port,
            name=self.name,
            redis_id=self.redis_id,
            server_id=self.server_id,
            status=self.status)


def get_redis(redis_id: Optional[_builtins.str] = None,
              opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetRedisResult:
    """
    Read non-secret metadata for an existing Dokploy Redis database by ID without managing it.

    :param _builtins.str redis_id: The ID of the existing Dokploy Redis database to read.
    """
    __args__ = dict()
    __args__['redisId'] = redis_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('dokploy:index:getRedis', __args__, opts=opts, typ=GetRedisResult).value

    return AwaitableGetRedisResult(
        app_name=pulumi.get(__ret__, 'app_name'),
        description=pulumi.get(__ret__, 'description'),
        docker_image=pulumi.get(__ret__, 'docker_image'),
        environment_id=pulumi.get(__ret__, 'environment_id'),
        external_port=pulumi.get(__ret__, 'external_port'),
        name=pulumi.get(__ret__, 'name'),
        redis_id=pulumi.get(__ret__, 'redis_id'),
        server_id=pulumi.get(__ret__, 'server_id'),
        status=pulumi.get(__ret__, 'status'))
def get_redis_output(redis_id: pulumi.Input[Optional[_builtins.str]] = None,
                     opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetRedisResult]:
    """
    Read non-secret metadata for an existing Dokploy Redis database by ID without managing it.

    :param _builtins.str redis_id: The ID of the existing Dokploy Redis database to read.
    """
    __args__ = dict()
    __args__['redisId'] = redis_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('dokploy:index:getRedis', __args__, opts=opts, typ=GetRedisResult)
    return __ret__.apply(lambda __response__: GetRedisResult(
        app_name=pulumi.get(__response__, 'app_name'),
        description=pulumi.get(__response__, 'description'),
        docker_image=pulumi.get(__response__, 'docker_image'),
        environment_id=pulumi.get(__response__, 'environment_id'),
        external_port=pulumi.get(__response__, 'external_port'),
        name=pulumi.get(__response__, 'name'),
        redis_id=pulumi.get(__response__, 'redis_id'),
        server_id=pulumi.get(__response__, 'server_id'),
        status=pulumi.get(__response__, 'status')))
