# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetServerResult',
    'AwaitableGetServerResult',
    'get_server',
    'get_server_output',
]

@pulumi.output_type
class GetServerResult:
    def __init__(__self__, description=None, ip_address=None, name=None, organization_id=None, port=None, server_id=None, server_type=None, ssh_key_id=None, status=None, username=None):
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if ip_address and not isinstance(ip_address, str):
            raise TypeError("Expected argument 'ip_address' to be a str")
        pulumi.set(__self__, "ip_address", ip_address)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if organization_id and not isinstance(organization_id, str):
            raise TypeError("Expected argument 'organization_id' to be a str")
        pulumi.set(__self__, "organization_id", organization_id)
        if port and not isinstance(port, int):
            raise TypeError("Expected argument 'port' to be a int")
        pulumi.set(__self__, "port", port)
        if server_id and not isinstance(server_id, str):
            raise TypeError("Expected argument 'server_id' to be a str")
        pulumi.set(__self__, "server_id", server_id)
        if server_type and not isinstance(server_type, str):
            raise TypeError("Expected argument 'server_type' to be a str")
        pulumi.set(__self__, "server_type", server_type)
        if ssh_key_id and not isinstance(ssh_key_id, str):
            raise TypeError("Expected argument 'ssh_key_id' to be a str")
        pulumi.set(__self__, "ssh_key_id", ssh_key_id)
        if status and not isinstance(status, str):
            raise TypeError("Expected argument 'status' to be a str")
        pulumi.set(__self__, "status", status)
        if username and not isinstance(username, str):
            raise TypeError("Expected argument 'username' to be a str")
        pulumi.set(__self__, "username", username)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[_builtins.str]:
        """
        The optional description metadata.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="ipAddress")
    def ip_address(self) -> Optional[_builtins.str]:
        """
        The optional IP address metadata.
        """
        return pulumi.get(self, "ip_address")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The server name.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> Optional[_builtins.str]:
        """
        The optional organization ID metadata.
        """
        return pulumi.get(self, "organization_id")

    @_builtins.property
    @pulumi.getter
    def port(self) -> Optional[_builtins.int]:
        """
        The optional port metadata.
        """
        return pulumi.get(self, "port")

    @_builtins.property
    @pulumi.getter(name="serverId")
    def server_id(self) -> _builtins.str:
        """
        The stable Dokploy server ID.
        """
        return pulumi.get(self, "server_id")

    @_builtins.property
    @pulumi.getter(name="serverType")
    def server_type(self) -> Optional[_builtins.str]:
        """
        The optional server type metadata.
        """
        return pulumi.get(self, "server_type")

    @_builtins.property
    @pulumi.getter(name="sshKeyId")
    def ssh_key_id(self) -> Optional[_builtins.str]:
        """
        The optional SSH key ID metadata.
        """
        return pulumi.get(self, "ssh_key_id")

    @_builtins.property
    @pulumi.getter
    def status(self) -> Optional[_builtins.str]:
        """
        The optional status metadata.
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter
    def username(self) -> Optional[_builtins.str]:
        """
        The optional username metadata.
        """
        return pulumi.get(self, "username")


class AwaitableGetServerResult(GetServerResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetServerResult(
            description=self.description,
            ip_address=self.ip_address,
            name=self.name,
            organization_id=self.organization_id,
            port=self.port,
            server_id=self.server_id,
            server_type=self.server_type,
            ssh_key_id=self.ssh_key_id,
            status=self.status,
            username=self.username)


def get_server(server_id: Optional[_builtins.str] = None,
               opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetServerResult:
    """
    Read non-secret metadata for an existing Dokploy server by ID without managing it.

    :param _builtins.str server_id: The ID of the existing Dokploy server to read.
    """
    __args__ = dict()
    __args__['serverId'] = server_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('dokploy:index:getServer', __args__, opts=opts, typ=GetServerResult).value

    return AwaitableGetServerResult(
        description=pulumi.get(__ret__, 'description'),
        ip_address=pulumi.get(__ret__, 'ip_address'),
        name=pulumi.get(__ret__, 'name'),
        organization_id=pulumi.get(__ret__, 'organization_id'),
        port=pulumi.get(__ret__, 'port'),
        server_id=pulumi.get(__ret__, 'server_id'),
        server_type=pulumi.get(__ret__, 'server_type'),
        ssh_key_id=pulumi.get(__ret__, 'ssh_key_id'),
        status=pulumi.get(__ret__, 'status'),
        username=pulumi.get(__ret__, 'username'))
def get_server_output(server_id: pulumi.Input[Optional[_builtins.str]] = None,
                      opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetServerResult]:
    """
    Read non-secret metadata for an existing Dokploy server by ID without managing it.

    :param _builtins.str server_id: The ID of the existing Dokploy server to read.
    """
    __args__ = dict()
    __args__['serverId'] = server_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('dokploy:index:getServer', __args__, opts=opts, typ=GetServerResult)
    return __ret__.apply(lambda __response__: GetServerResult(
        description=pulumi.get(__response__, 'description'),
        ip_address=pulumi.get(__response__, 'ip_address'),
        name=pulumi.get(__response__, 'name'),
        organization_id=pulumi.get(__response__, 'organization_id'),
        port=pulumi.get(__response__, 'port'),
        server_id=pulumi.get(__response__, 'server_id'),
        server_type=pulumi.get(__response__, 'server_type'),
        ssh_key_id=pulumi.get(__response__, 'ssh_key_id'),
        status=pulumi.get(__response__, 'status'),
        username=pulumi.get(__response__, 'username')))
