# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetComposeResult',
    'AwaitableGetComposeResult',
    'get_compose',
    'get_compose_output',
]

@pulumi.output_type
class GetComposeResult:
    def __init__(__self__, app_name=None, compose_id=None, compose_type=None, description=None, environment_id=None, name=None, server_id=None, status=None):
        if app_name and not isinstance(app_name, str):
            raise TypeError("Expected argument 'app_name' to be a str")
        pulumi.set(__self__, "app_name", app_name)
        if compose_id and not isinstance(compose_id, str):
            raise TypeError("Expected argument 'compose_id' to be a str")
        pulumi.set(__self__, "compose_id", compose_id)
        if compose_type and not isinstance(compose_type, str):
            raise TypeError("Expected argument 'compose_type' to be a str")
        pulumi.set(__self__, "compose_type", compose_type)
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if environment_id and not isinstance(environment_id, str):
            raise TypeError("Expected argument 'environment_id' to be a str")
        pulumi.set(__self__, "environment_id", environment_id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if server_id and not isinstance(server_id, str):
            raise TypeError("Expected argument 'server_id' to be a str")
        pulumi.set(__self__, "server_id", server_id)
        if status and not isinstance(status, str):
            raise TypeError("Expected argument 'status' to be a str")
        pulumi.set(__self__, "status", status)

    @_builtins.property
    @pulumi.getter(name="appName")
    def app_name(self) -> Optional[_builtins.str]:
        """
        The optional application name metadata.
        """
        return pulumi.get(self, "app_name")

    @_builtins.property
    @pulumi.getter(name="composeId")
    def compose_id(self) -> _builtins.str:
        """
        The stable Dokploy Compose ID.
        """
        return pulumi.get(self, "compose_id")

    @_builtins.property
    @pulumi.getter(name="composeType")
    def compose_type(self) -> Optional[_builtins.str]:
        """
        The optional Compose type.
        """
        return pulumi.get(self, "compose_type")

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[_builtins.str]:
        """
        The optional description metadata.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="environmentId")
    def environment_id(self) -> Optional[_builtins.str]:
        """
        The optional environment ID metadata.
        """
        return pulumi.get(self, "environment_id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The Compose deployment name.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="serverId")
    def server_id(self) -> Optional[_builtins.str]:
        """
        The optional server ID metadata.
        """
        return pulumi.get(self, "server_id")

    @_builtins.property
    @pulumi.getter
    def status(self) -> Optional[_builtins.str]:
        """
        The optional Compose status.
        """
        return pulumi.get(self, "status")


class AwaitableGetComposeResult(GetComposeResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetComposeResult(
            app_name=self.app_name,
            compose_id=self.compose_id,
            compose_type=self.compose_type,
            description=self.description,
            environment_id=self.environment_id,
            name=self.name,
            server_id=self.server_id,
            status=self.status)


def get_compose(compose_id: Optional[_builtins.str] = None,
                opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetComposeResult:
    """
    Read non-secret metadata for an existing Dokploy Compose deployment by ID without managing it.

    :param _builtins.str compose_id: The ID of the existing Dokploy Compose deployment to read.
    """
    __args__ = dict()
    __args__['composeId'] = compose_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('dokploy:index:getCompose', __args__, opts=opts, typ=GetComposeResult).value

    return AwaitableGetComposeResult(
        app_name=pulumi.get(__ret__, 'app_name'),
        compose_id=pulumi.get(__ret__, 'compose_id'),
        compose_type=pulumi.get(__ret__, 'compose_type'),
        description=pulumi.get(__ret__, 'description'),
        environment_id=pulumi.get(__ret__, 'environment_id'),
        name=pulumi.get(__ret__, 'name'),
        server_id=pulumi.get(__ret__, 'server_id'),
        status=pulumi.get(__ret__, 'status'))
def get_compose_output(compose_id: pulumi.Input[Optional[_builtins.str]] = None,
                       opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetComposeResult]:
    """
    Read non-secret metadata for an existing Dokploy Compose deployment by ID without managing it.

    :param _builtins.str compose_id: The ID of the existing Dokploy Compose deployment to read.
    """
    __args__ = dict()
    __args__['composeId'] = compose_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('dokploy:index:getCompose', __args__, opts=opts, typ=GetComposeResult)
    return __ret__.apply(lambda __response__: GetComposeResult(
        app_name=pulumi.get(__response__, 'app_name'),
        compose_id=pulumi.get(__response__, 'compose_id'),
        compose_type=pulumi.get(__response__, 'compose_type'),
        description=pulumi.get(__response__, 'description'),
        environment_id=pulumi.get(__response__, 'environment_id'),
        name=pulumi.get(__response__, 'name'),
        server_id=pulumi.get(__response__, 'server_id'),
        status=pulumi.get(__response__, 'status')))
