// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.gjorgjidimeski.dokploy.inputs;

import com.gjorgjidimeski.dokploy.inputs.DockerSourceArgs;
import com.gjorgjidimeski.dokploy.inputs.GitApplicationSourceArgs;
import com.gjorgjidimeski.dokploy.inputs.GitLabAppSourceArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


/**
 * Application source configuration.
 * 
 */
public final class ApplicationSourceArgs extends com.pulumi.resources.ResourceArgs {

    public static final ApplicationSourceArgs Empty = new ApplicationSourceArgs();

    /**
     * Docker source configuration.
     * 
     */
    @Import(name="docker")
    private @Nullable Output<DockerSourceArgs> docker;

    /**
     * @return Docker source configuration.
     * 
     */
    public Optional<Output<DockerSourceArgs>> docker() {
        return Optional.ofNullable(this.docker);
    }

    /**
     * Git source configuration.
     * 
     */
    @Import(name="git")
    private @Nullable Output<GitApplicationSourceArgs> git;

    /**
     * @return Git source configuration.
     * 
     */
    public Optional<Output<GitApplicationSourceArgs>> git() {
        return Optional.ofNullable(this.git);
    }

    /**
     * GitLab source configuration.
     * 
     */
    @Import(name="gitlab")
    private @Nullable Output<GitLabAppSourceArgs> gitlab;

    /**
     * @return GitLab source configuration.
     * 
     */
    public Optional<Output<GitLabAppSourceArgs>> gitlab() {
        return Optional.ofNullable(this.gitlab);
    }

    /**
     * The application source type.
     * 
     */
    @Import(name="type", required=true)
    private Output<String> type;

    /**
     * @return The application source type.
     * 
     */
    public Output<String> type() {
        return this.type;
    }

    private ApplicationSourceArgs() {}

    private ApplicationSourceArgs(ApplicationSourceArgs $) {
        this.docker = $.docker;
        this.git = $.git;
        this.gitlab = $.gitlab;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ApplicationSourceArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ApplicationSourceArgs $;

        public Builder() {
            $ = new ApplicationSourceArgs();
        }

        public Builder(ApplicationSourceArgs defaults) {
            $ = new ApplicationSourceArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param docker Docker source configuration.
         * 
         * @return builder
         * 
         */
        public Builder docker(@Nullable Output<DockerSourceArgs> docker) {
            $.docker = docker;
            return this;
        }

        /**
         * @param docker Docker source configuration.
         * 
         * @return builder
         * 
         */
        public Builder docker(DockerSourceArgs docker) {
            return docker(Output.of(docker));
        }

        /**
         * @param git Git source configuration.
         * 
         * @return builder
         * 
         */
        public Builder git(@Nullable Output<GitApplicationSourceArgs> git) {
            $.git = git;
            return this;
        }

        /**
         * @param git Git source configuration.
         * 
         * @return builder
         * 
         */
        public Builder git(GitApplicationSourceArgs git) {
            return git(Output.of(git));
        }

        /**
         * @param gitlab GitLab source configuration.
         * 
         * @return builder
         * 
         */
        public Builder gitlab(@Nullable Output<GitLabAppSourceArgs> gitlab) {
            $.gitlab = gitlab;
            return this;
        }

        /**
         * @param gitlab GitLab source configuration.
         * 
         * @return builder
         * 
         */
        public Builder gitlab(GitLabAppSourceArgs gitlab) {
            return gitlab(Output.of(gitlab));
        }

        /**
         * @param type The application source type.
         * 
         * @return builder
         * 
         */
        public Builder type(Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type The application source type.
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        public ApplicationSourceArgs build() {
            if ($.type == null) {
                throw new MissingRequiredPropertyException("ApplicationSourceArgs", "type");
            }
            return $;
        }
    }

}
