// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.gjorgjidimeski.dokploy;

import com.pulumi.core.internal.Codegen;
import java.lang.String;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("dokploy");
/**
 * Dokploy API key sent through x-api-key.
 * 
 */
    public String apiKey() {
        return Codegen.stringProp("apiKey").config(config).env("DOKPLOY_API_KEY").require();
    }
/**
 * Base URL of the Dokploy instance.
 * 
 */
    public String endpoint() {
        return Codegen.stringProp("endpoint").config(config).env("DOKPLOY_ENDPOINT").require();
    }
}
