[tools]
go = "1.26.6"
golangci-lint = "2.9.0"
gotestsum = "1.13.0"
node = "24.18.0"
pulumi = "3.259.0"
syft = "1.51.1"
java = ["temurin-11.0.32+101", "temurin-17.0.20+8"]
gradle = "8.14.3"
maven = "3.9.11"

[env]
_.file = ".env" 
DOKPLOY_ACCEPTANCE=1
