// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Dokploy
{
    /// <summary>
    /// A scheduled Dokploy database backup. Exactly one of postgresId, mysqlId, mariadbId, or mongoId must be set.
    /// </summary>
    [DokployResourceType("dokploy:index:Backup")]
    public partial class Backup : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The stable Dokploy backup ID.
        /// </summary>
        [Output("backupId")]
        public Output<string> BackupId { get; private set; } = null!;

        /// <summary>
        /// The database name inside the target instance to back up.
        /// </summary>
        [Output("database")]
        public Output<string> Database { get; private set; } = null!;

        /// <summary>
        /// The destination ID backups are stored to.
        /// </summary>
        [Output("destinationId")]
        public Output<string> DestinationId { get; private set; } = null!;

        /// <summary>
        /// Whether the backup schedule is enabled.
        /// </summary>
        [Output("enabled")]
        public Output<bool> Enabled { get; private set; } = null!;

        /// <summary>
        /// The optional number of most recent backups to retain.
        /// </summary>
        [Output("keepLatestCount")]
        public Output<int?> KeepLatestCount { get; private set; } = null!;

        /// <summary>
        /// The target MariaDB ID.
        /// </summary>
        [Output("mariadbId")]
        public Output<string?> MariadbId { get; private set; } = null!;

        /// <summary>
        /// The target MongoDB ID.
        /// </summary>
        [Output("mongoId")]
        public Output<string?> MongoId { get; private set; } = null!;

        /// <summary>
        /// The target MySQL ID.
        /// </summary>
        [Output("mysqlId")]
        public Output<string?> MysqlId { get; private set; } = null!;

        /// <summary>
        /// The target Postgres ID.
        /// </summary>
        [Output("postgresId")]
        public Output<string?> PostgresId { get; private set; } = null!;

        /// <summary>
        /// The backup file prefix.
        /// </summary>
        [Output("prefix")]
        public Output<string> Prefix { get; private set; } = null!;

        /// <summary>
        /// The backup cron schedule.
        /// </summary>
        [Output("schedule")]
        public Output<string> Schedule { get; private set; } = null!;


        /// <summary>
        /// Create a Backup resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Backup(string name, BackupArgs args, CustomResourceOptions? options = null)
            : base("dokploy:index:Backup", name, args ?? new BackupArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Backup(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("dokploy:index:Backup", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                ReplaceOnChanges =
                {
                    "mariadbId",
                    "mongoId",
                    "mysqlId",
                    "postgresId",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Backup resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Backup Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Backup(name, id, options);
        }
    }

    public sealed class BackupArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The database name inside the target instance to back up.
        /// </summary>
        [Input("database", required: true)]
        public Input<string> Database { get; set; } = null!;

        /// <summary>
        /// The destination ID backups are stored to.
        /// </summary>
        [Input("destinationId", required: true)]
        public Input<string> DestinationId { get; set; } = null!;

        /// <summary>
        /// Whether the backup schedule is enabled.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// The optional number of most recent backups to retain.
        /// </summary>
        [Input("keepLatestCount")]
        public Input<int>? KeepLatestCount { get; set; }

        /// <summary>
        /// The target MariaDB ID.
        /// </summary>
        [Input("mariadbId")]
        public Input<string>? MariadbId { get; set; }

        /// <summary>
        /// The target MongoDB ID.
        /// </summary>
        [Input("mongoId")]
        public Input<string>? MongoId { get; set; }

        /// <summary>
        /// The target MySQL ID.
        /// </summary>
        [Input("mysqlId")]
        public Input<string>? MysqlId { get; set; }

        /// <summary>
        /// The target Postgres ID.
        /// </summary>
        [Input("postgresId")]
        public Input<string>? PostgresId { get; set; }

        /// <summary>
        /// The backup file prefix.
        /// </summary>
        [Input("prefix", required: true)]
        public Input<string> Prefix { get; set; } = null!;

        /// <summary>
        /// The backup cron schedule.
        /// </summary>
        [Input("schedule", required: true)]
        public Input<string> Schedule { get; set; } = null!;

        public BackupArgs()
        {
            Enabled = true;
        }
        public static new BackupArgs Empty => new BackupArgs();
    }
}
