// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Dokploy
{
    /// <summary>
    /// A Dokploy project-to-tag association.
    /// </summary>
    [DokployResourceType("dokploy:index:ProjectTag")]
    public partial class ProjectTag : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The Dokploy project ID.
        /// </summary>
        [Output("projectId")]
        public Output<string> ProjectId { get; private set; } = null!;

        /// <summary>
        /// The Dokploy tag ID.
        /// </summary>
        [Output("tagId")]
        public Output<string> TagId { get; private set; } = null!;


        /// <summary>
        /// Create a ProjectTag resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ProjectTag(string name, ProjectTagArgs args, CustomResourceOptions? options = null)
            : base("dokploy:index:ProjectTag", name, args ?? new ProjectTagArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ProjectTag(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("dokploy:index:ProjectTag", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                ReplaceOnChanges =
                {
                    "projectId",
                    "tagId",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ProjectTag resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ProjectTag Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new ProjectTag(name, id, options);
        }
    }

    public sealed class ProjectTagArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The Dokploy project ID.
        /// </summary>
        [Input("projectId", required: true)]
        public Input<string> ProjectId { get; set; } = null!;

        /// <summary>
        /// The Dokploy tag ID.
        /// </summary>
        [Input("tagId", required: true)]
        public Input<string> TagId { get; set; } = null!;

        public ProjectTagArgs()
        {
        }
        public static new ProjectTagArgs Empty => new ProjectTagArgs();
    }
}
