// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumi.Dokploy.Dokploy
{
    /// <summary>
    /// A Dokploy application.
    /// </summary>
    [DokployResourceType("dokploy:index:Application")]
    public partial class Application : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The optional deployed application name.
        /// </summary>
        [Output("appName")]
        public Output<string?> AppName { get; private set; } = null!;

        /// <summary>
        /// The stable Dokploy application ID.
        /// </summary>
        [Output("applicationId")]
        public Output<string> ApplicationId { get; private set; } = null!;

        /// <summary>
        /// Build arguments for the application.
        /// </summary>
        [Output("buildArgs")]
        public Output<string?> BuildArgs { get; private set; } = null!;

        /// <summary>
        /// Build secrets for the application.
        /// </summary>
        [Output("buildSecrets")]
        public Output<string?> BuildSecrets { get; private set; } = null!;

        /// <summary>
        /// Whether to create an environment file.
        /// </summary>
        [Output("createEnvFile")]
        public Output<bool?> CreateEnvFile { get; private set; } = null!;

        /// <summary>
        /// An optional application description.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// Environment variables for the application.
        /// </summary>
        [Output("environment")]
        public Output<string?> Environment { get; private set; } = null!;

        /// <summary>
        /// The target environment ID.
        /// </summary>
        [Output("environmentId")]
        public Output<string> EnvironmentId { get; private set; } = null!;

        /// <summary>
        /// The application name.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The optional server ID.
        /// </summary>
        [Output("serverId")]
        public Output<string?> ServerId { get; private set; } = null!;

        /// <summary>
        /// The application source configuration.
        /// </summary>
        [Output("source")]
        public Output<Outputs.ApplicationSource> Source { get; private set; } = null!;

        /// <summary>
        /// The current application deployment status.
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;


        /// <summary>
        /// Create a Application resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Application(string name, ApplicationArgs args, CustomResourceOptions? options = null)
            : base("dokploy:index:Application", name, args ?? new ApplicationArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Application(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("dokploy:index:Application", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "buildArgs",
                    "buildSecrets",
                    "environment",
                },
                ReplaceOnChanges =
                {
                    "environmentId",
                    "serverId",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Application resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Application Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Application(name, id, options);
        }
    }

    public sealed class ApplicationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The optional deployed application name.
        /// </summary>
        [Input("appName")]
        public Input<string>? AppName { get; set; }

        [Input("buildArgs")]
        private Input<string>? _buildArgs;

        /// <summary>
        /// Build arguments for the application.
        /// </summary>
        public Input<string>? BuildArgs
        {
            get => _buildArgs;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _buildArgs = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("buildSecrets")]
        private Input<string>? _buildSecrets;

        /// <summary>
        /// Build secrets for the application.
        /// </summary>
        public Input<string>? BuildSecrets
        {
            get => _buildSecrets;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _buildSecrets = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Whether to create an environment file.
        /// </summary>
        [Input("createEnvFile")]
        public Input<bool>? CreateEnvFile { get; set; }

        /// <summary>
        /// An optional application description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("environment")]
        private Input<string>? _environment;

        /// <summary>
        /// Environment variables for the application.
        /// </summary>
        public Input<string>? Environment
        {
            get => _environment;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _environment = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The target environment ID.
        /// </summary>
        [Input("environmentId", required: true)]
        public Input<string> EnvironmentId { get; set; } = null!;

        /// <summary>
        /// The application name.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// The optional server ID.
        /// </summary>
        [Input("serverId")]
        public Input<string>? ServerId { get; set; }

        /// <summary>
        /// The application source configuration.
        /// </summary>
        [Input("source", required: true)]
        public Input<Inputs.ApplicationSourceArgs> Source { get; set; } = null!;

        public ApplicationArgs()
        {
        }
        public static new ApplicationArgs Empty => new ApplicationArgs();
    }
}
