// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Dimeskigj.Pulumi.Dokploy
{
    public static class GetEnvironment
    {
        /// <summary>
        /// Read non-secret metadata for an existing Dokploy environment by ID without managing it.
        /// </summary>
        public static Task<GetEnvironmentResult> InvokeAsync(GetEnvironmentArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetEnvironmentResult>("dokploy:index:getEnvironment", args ?? new GetEnvironmentArgs(), options.WithDefaults());

        /// <summary>
        /// Read non-secret metadata for an existing Dokploy environment by ID without managing it.
        /// </summary>
        public static Output<GetEnvironmentResult> Invoke(GetEnvironmentInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetEnvironmentResult>("dokploy:index:getEnvironment", args ?? new GetEnvironmentInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Read non-secret metadata for an existing Dokploy environment by ID without managing it.
        /// </summary>
        public static Output<GetEnvironmentResult> Invoke(GetEnvironmentInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetEnvironmentResult>("dokploy:index:getEnvironment", args ?? new GetEnvironmentInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetEnvironmentArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the existing Dokploy environment to read.
        /// </summary>
        [Input("environmentId", required: true)]
        public string EnvironmentId { get; set; } = null!;

        public GetEnvironmentArgs()
        {
        }
        public static new GetEnvironmentArgs Empty => new GetEnvironmentArgs();
    }

    public sealed class GetEnvironmentInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the existing Dokploy environment to read.
        /// </summary>
        [Input("environmentId", required: true)]
        public Input<string> EnvironmentId { get; set; } = null!;

        public GetEnvironmentInvokeArgs()
        {
        }
        public static new GetEnvironmentInvokeArgs Empty => new GetEnvironmentInvokeArgs();
    }


    [OutputType]
    public sealed class GetEnvironmentResult
    {
        /// <summary>
        /// The optional description metadata.
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// The stable Dokploy environment ID.
        /// </summary>
        public readonly string EnvironmentId;
        /// <summary>
        /// The optional is default metadata.
        /// </summary>
        public readonly bool? IsDefault;
        /// <summary>
        /// The environment name.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The optional project ID metadata.
        /// </summary>
        public readonly string? ProjectId;

        [OutputConstructor]
        private GetEnvironmentResult(
            string? description,

            string environmentId,

            bool? isDefault,

            string name,

            string? projectId)
        {
            Description = description;
            EnvironmentId = environmentId;
            IsDefault = isDefault;
            Name = name;
            ProjectId = projectId;
        }
    }
}
