// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Dimeskigj.Pulumi.Dokploy
{
    public static class GetMySQL
    {
        /// <summary>
        /// Read non-secret metadata for an existing Dokploy MySQL database by ID without managing it.
        /// </summary>
        public static Task<GetMySQLResult> InvokeAsync(GetMySQLArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetMySQLResult>("dokploy:index:getMySQL", args ?? new GetMySQLArgs(), options.WithDefaults());

        /// <summary>
        /// Read non-secret metadata for an existing Dokploy MySQL database by ID without managing it.
        /// </summary>
        public static Output<GetMySQLResult> Invoke(GetMySQLInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetMySQLResult>("dokploy:index:getMySQL", args ?? new GetMySQLInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Read non-secret metadata for an existing Dokploy MySQL database by ID without managing it.
        /// </summary>
        public static Output<GetMySQLResult> Invoke(GetMySQLInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetMySQLResult>("dokploy:index:getMySQL", args ?? new GetMySQLInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetMySQLArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the existing Dokploy MySQL database to read.
        /// </summary>
        [Input("mysqlId", required: true)]
        public string MysqlId { get; set; } = null!;

        public GetMySQLArgs()
        {
        }
        public static new GetMySQLArgs Empty => new GetMySQLArgs();
    }

    public sealed class GetMySQLInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the existing Dokploy MySQL database to read.
        /// </summary>
        [Input("mysqlId", required: true)]
        public Input<string> MysqlId { get; set; } = null!;

        public GetMySQLInvokeArgs()
        {
        }
        public static new GetMySQLInvokeArgs Empty => new GetMySQLInvokeArgs();
    }


    [OutputType]
    public sealed class GetMySQLResult
    {
        /// <summary>
        /// The optional application name metadata.
        /// </summary>
        public readonly string? AppName;
        /// <summary>
        /// The optional database name metadata.
        /// </summary>
        public readonly string? DatabaseName;
        /// <summary>
        /// The optional database username metadata.
        /// </summary>
        public readonly string? DatabaseUser;
        /// <summary>
        /// The optional description metadata.
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// The optional Docker image metadata.
        /// </summary>
        public readonly string? DockerImage;
        /// <summary>
        /// The optional environment ID metadata.
        /// </summary>
        public readonly string? EnvironmentId;
        /// <summary>
        /// The optional external port.
        /// </summary>
        public readonly int? ExternalPort;
        /// <summary>
        /// The stable Dokploy MySQL ID.
        /// </summary>
        public readonly string MysqlId;
        /// <summary>
        /// The MySQL database name.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The optional server ID metadata.
        /// </summary>
        public readonly string? ServerId;
        /// <summary>
        /// The optional application status.
        /// </summary>
        public readonly string? Status;

        [OutputConstructor]
        private GetMySQLResult(
            string? appName,

            string? databaseName,

            string? databaseUser,

            string? description,

            string? dockerImage,

            string? environmentId,

            int? externalPort,

            string mysqlId,

            string name,

            string? serverId,

            string? status)
        {
            AppName = appName;
            DatabaseName = databaseName;
            DatabaseUser = databaseUser;
            Description = description;
            DockerImage = dockerImage;
            EnvironmentId = environmentId;
            ExternalPort = externalPort;
            MysqlId = mysqlId;
            Name = name;
            ServerId = serverId;
            Status = status;
        }
    }
}
