// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Dimeskigj.Pulumi.Dokploy
{
    public static class GetRegistry
    {
        /// <summary>
        /// Read non-secret metadata for an existing Dokploy registry by ID without managing it.
        /// </summary>
        public static Task<GetRegistryResult> InvokeAsync(GetRegistryArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetRegistryResult>("dokploy:index:getRegistry", args ?? new GetRegistryArgs(), options.WithDefaults());

        /// <summary>
        /// Read non-secret metadata for an existing Dokploy registry by ID without managing it.
        /// </summary>
        public static Output<GetRegistryResult> Invoke(GetRegistryInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetRegistryResult>("dokploy:index:getRegistry", args ?? new GetRegistryInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Read non-secret metadata for an existing Dokploy registry by ID without managing it.
        /// </summary>
        public static Output<GetRegistryResult> Invoke(GetRegistryInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetRegistryResult>("dokploy:index:getRegistry", args ?? new GetRegistryInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetRegistryArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the existing Dokploy registry to read.
        /// </summary>
        [Input("registryId", required: true)]
        public string RegistryId { get; set; } = null!;

        public GetRegistryArgs()
        {
        }
        public static new GetRegistryArgs Empty => new GetRegistryArgs();
    }

    public sealed class GetRegistryInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the existing Dokploy registry to read.
        /// </summary>
        [Input("registryId", required: true)]
        public Input<string> RegistryId { get; set; } = null!;

        public GetRegistryInvokeArgs()
        {
        }
        public static new GetRegistryInvokeArgs Empty => new GetRegistryInvokeArgs();
    }


    [OutputType]
    public sealed class GetRegistryResult
    {
        /// <summary>
        /// The optional image prefix metadata.
        /// </summary>
        public readonly string? ImagePrefix;
        /// <summary>
        /// The registry name.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The stable Dokploy registry ID.
        /// </summary>
        public readonly string RegistryId;
        /// <summary>
        /// The optional registry type metadata.
        /// </summary>
        public readonly string? RegistryType;
        /// <summary>
        /// The optional server ID metadata.
        /// </summary>
        public readonly string? ServerId;
        /// <summary>
        /// The optional URL metadata.
        /// </summary>
        public readonly string? Url;
        /// <summary>
        /// The optional username metadata.
        /// </summary>
        public readonly string? Username;

        [OutputConstructor]
        private GetRegistryResult(
            string? imagePrefix,

            string name,

            string registryId,

            string? registryType,

            string? serverId,

            string? url,

            string? username)
        {
            ImagePrefix = imagePrefix;
            Name = name;
            RegistryId = registryId;
            RegistryType = registryType;
            ServerId = serverId;
            Url = url;
            Username = username;
        }
    }
}
