// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Dimeskigj.Pulumi.Dokploy
{
    public static class GetRedis
    {
        /// <summary>
        /// Read non-secret metadata for an existing Dokploy Redis database by ID without managing it.
        /// </summary>
        public static Task<GetRedisResult> InvokeAsync(GetRedisArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetRedisResult>("dokploy:index:getRedis", args ?? new GetRedisArgs(), options.WithDefaults());

        /// <summary>
        /// Read non-secret metadata for an existing Dokploy Redis database by ID without managing it.
        /// </summary>
        public static Output<GetRedisResult> Invoke(GetRedisInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetRedisResult>("dokploy:index:getRedis", args ?? new GetRedisInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Read non-secret metadata for an existing Dokploy Redis database by ID without managing it.
        /// </summary>
        public static Output<GetRedisResult> Invoke(GetRedisInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetRedisResult>("dokploy:index:getRedis", args ?? new GetRedisInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetRedisArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the existing Dokploy Redis database to read.
        /// </summary>
        [Input("redisId", required: true)]
        public string RedisId { get; set; } = null!;

        public GetRedisArgs()
        {
        }
        public static new GetRedisArgs Empty => new GetRedisArgs();
    }

    public sealed class GetRedisInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the existing Dokploy Redis database to read.
        /// </summary>
        [Input("redisId", required: true)]
        public Input<string> RedisId { get; set; } = null!;

        public GetRedisInvokeArgs()
        {
        }
        public static new GetRedisInvokeArgs Empty => new GetRedisInvokeArgs();
    }


    [OutputType]
    public sealed class GetRedisResult
    {
        /// <summary>
        /// The optional application name metadata.
        /// </summary>
        public readonly string? AppName;
        /// <summary>
        /// The optional description metadata.
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// The optional Docker image metadata.
        /// </summary>
        public readonly string? DockerImage;
        /// <summary>
        /// The optional environment ID metadata.
        /// </summary>
        public readonly string? EnvironmentId;
        /// <summary>
        /// The optional external port.
        /// </summary>
        public readonly int? ExternalPort;
        /// <summary>
        /// The Redis database name.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The stable Dokploy Redis ID.
        /// </summary>
        public readonly string RedisId;
        /// <summary>
        /// The optional server ID metadata.
        /// </summary>
        public readonly string? ServerId;
        /// <summary>
        /// The optional application status.
        /// </summary>
        public readonly string? Status;

        [OutputConstructor]
        private GetRedisResult(
            string? appName,

            string? description,

            string? dockerImage,

            string? environmentId,

            int? externalPort,

            string name,

            string redisId,

            string? serverId,

            string? status)
        {
            AppName = appName;
            Description = description;
            DockerImage = dockerImage;
            EnvironmentId = environmentId;
            ExternalPort = externalPort;
            Name = name;
            RedisId = redisId;
            ServerId = serverId;
            Status = status;
        }
    }
}
