// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package net.dimeski.pulumi.dokploy.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ApplicationBuild {
    /**
     * @return The Docker build stage.
     * 
     */
    private @Nullable String dockerBuildStage;
    /**
     * @return The Docker build context.
     * 
     */
    private @Nullable String dockerContextPath;
    /**
     * @return The Dockerfile path.
     * 
     */
    private @Nullable String dockerfile;
    /**
     * @return The build type.
     * 
     */
    private String type;

    private ApplicationBuild() {}
    /**
     * @return The Docker build stage.
     * 
     */
    public Optional<String> dockerBuildStage() {
        return Optional.ofNullable(this.dockerBuildStage);
    }
    /**
     * @return The Docker build context.
     * 
     */
    public Optional<String> dockerContextPath() {
        return Optional.ofNullable(this.dockerContextPath);
    }
    /**
     * @return The Dockerfile path.
     * 
     */
    public Optional<String> dockerfile() {
        return Optional.ofNullable(this.dockerfile);
    }
    /**
     * @return The build type.
     * 
     */
    public String type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ApplicationBuild defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String dockerBuildStage;
        private @Nullable String dockerContextPath;
        private @Nullable String dockerfile;
        private String type;
        public Builder() {}
        public Builder(ApplicationBuild defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.dockerBuildStage = defaults.dockerBuildStage;
    	      this.dockerContextPath = defaults.dockerContextPath;
    	      this.dockerfile = defaults.dockerfile;
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder dockerBuildStage(@Nullable String dockerBuildStage) {

            this.dockerBuildStage = dockerBuildStage;
            return this;
        }
        @CustomType.Setter
        public Builder dockerContextPath(@Nullable String dockerContextPath) {

            this.dockerContextPath = dockerContextPath;
            return this;
        }
        @CustomType.Setter
        public Builder dockerfile(@Nullable String dockerfile) {

            this.dockerfile = dockerfile;
            return this;
        }
        @CustomType.Setter
        public Builder type(String type) {
            if (type == null) {
              throw new MissingRequiredPropertyException("ApplicationBuild", "type");
            }
            this.type = type;
            return this;
        }
        public ApplicationBuild build() {
            final var _resultValue = new ApplicationBuild();
            _resultValue.dockerBuildStage = dockerBuildStage;
            _resultValue.dockerContextPath = dockerContextPath;
            _resultValue.dockerfile = dockerfile;
            _resultValue.type = type;
            return _resultValue;
        }
    }
}
