// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package net.dimeski.pulumi.dokploy.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetComposeResult {
    /**
     * @return The optional application name metadata.
     *
     */
    private @Nullable String appName;
    /**
     * @return The stable Dokploy Compose ID.
     *
     */
    private String composeId;
    /**
     * @return The optional Compose type.
     *
     */
    private @Nullable String composeType;
    /**
     * @return The optional description metadata.
     *
     */
    private @Nullable String description;
    /**
     * @return The optional environment ID metadata.
     *
     */
    private @Nullable String environmentId;
    /**
     * @return The Compose deployment name.
     *
     */
    private String name;
    /**
     * @return The optional server ID metadata.
     *
     */
    private @Nullable String serverId;
    /**
     * @return The optional Compose status.
     *
     */
    private @Nullable String status;

    private GetComposeResult() {}
    /**
     * @return The optional application name metadata.
     *
     */
    public Optional<String> appName() {
        return Optional.ofNullable(this.appName);
    }
    /**
     * @return The stable Dokploy Compose ID.
     *
     */
    public String composeId() {
        return this.composeId;
    }
    /**
     * @return The optional Compose type.
     *
     */
    public Optional<String> composeType() {
        return Optional.ofNullable(this.composeType);
    }
    /**
     * @return The optional description metadata.
     *
     */
    public Optional<String> description() {
        return Optional.ofNullable(this.description);
    }
    /**
     * @return The optional environment ID metadata.
     *
     */
    public Optional<String> environmentId() {
        return Optional.ofNullable(this.environmentId);
    }
    /**
     * @return The Compose deployment name.
     *
     */
    public String name() {
        return this.name;
    }
    /**
     * @return The optional server ID metadata.
     *
     */
    public Optional<String> serverId() {
        return Optional.ofNullable(this.serverId);
    }
    /**
     * @return The optional Compose status.
     *
     */
    public Optional<String> status() {
        return Optional.ofNullable(this.status);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetComposeResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String appName;
        private String composeId;
        private @Nullable String composeType;
        private @Nullable String description;
        private @Nullable String environmentId;
        private String name;
        private @Nullable String serverId;
        private @Nullable String status;
        public Builder() {}
        public Builder(GetComposeResult defaults) {
              Objects.requireNonNull(defaults);
              this.appName = defaults.appName;
              this.composeId = defaults.composeId;
              this.composeType = defaults.composeType;
              this.description = defaults.description;
              this.environmentId = defaults.environmentId;
              this.name = defaults.name;
              this.serverId = defaults.serverId;
              this.status = defaults.status;
        }

        @CustomType.Setter
        public Builder appName(@Nullable String appName) {

            this.appName = appName;
            return this;
        }
        @CustomType.Setter
        public Builder composeId(String composeId) {
            if (composeId == null) {
              throw new MissingRequiredPropertyException("GetComposeResult", "composeId");
            }
            this.composeId = composeId;
            return this;
        }
        @CustomType.Setter
        public Builder composeType(@Nullable String composeType) {

            this.composeType = composeType;
            return this;
        }
        @CustomType.Setter
        public Builder description(@Nullable String description) {

            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder environmentId(@Nullable String environmentId) {

            this.environmentId = environmentId;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetComposeResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder serverId(@Nullable String serverId) {

            this.serverId = serverId;
            return this;
        }
        @CustomType.Setter
        public Builder status(@Nullable String status) {

            this.status = status;
            return this;
        }
        public GetComposeResult build() {
            final var _resultValue = new GetComposeResult();
            _resultValue.appName = appName;
            _resultValue.composeId = composeId;
            _resultValue.composeType = composeType;
            _resultValue.description = description;
            _resultValue.environmentId = environmentId;
            _resultValue.name = name;
            _resultValue.serverId = serverId;
            _resultValue.status = status;
            return _resultValue;
        }
    }
}
