// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package net.dimeski.pulumi.dokploy.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetMongoDBResult {
    /**
     * @return The optional application name metadata.
     *
     */
    private @Nullable String appName;
    /**
     * @return The optional database username metadata.
     *
     */
    private @Nullable String databaseUser;
    /**
     * @return The optional description metadata.
     *
     */
    private @Nullable String description;
    /**
     * @return The optional Docker image metadata.
     *
     */
    private @Nullable String dockerImage;
    /**
     * @return The optional environment ID metadata.
     *
     */
    private @Nullable String environmentId;
    /**
     * @return The optional external port.
     *
     */
    private @Nullable Integer externalPort;
    /**
     * @return The stable Dokploy MongoDB ID.
     *
     */
    private String mongoId;
    /**
     * @return The MongoDB database name.
     *
     */
    private String name;
    /**
     * @return Whether replica sets are enabled, if supplied.
     *
     */
    private @Nullable Boolean replicaSets;
    /**
     * @return The optional server ID metadata.
     *
     */
    private @Nullable String serverId;
    /**
     * @return The optional application status.
     *
     */
    private @Nullable String status;

    private GetMongoDBResult() {}
    /**
     * @return The optional application name metadata.
     *
     */
    public Optional<String> appName() {
        return Optional.ofNullable(this.appName);
    }
    /**
     * @return The optional database username metadata.
     *
     */
    public Optional<String> databaseUser() {
        return Optional.ofNullable(this.databaseUser);
    }
    /**
     * @return The optional description metadata.
     *
     */
    public Optional<String> description() {
        return Optional.ofNullable(this.description);
    }
    /**
     * @return The optional Docker image metadata.
     *
     */
    public Optional<String> dockerImage() {
        return Optional.ofNullable(this.dockerImage);
    }
    /**
     * @return The optional environment ID metadata.
     *
     */
    public Optional<String> environmentId() {
        return Optional.ofNullable(this.environmentId);
    }
    /**
     * @return The optional external port.
     *
     */
    public Optional<Integer> externalPort() {
        return Optional.ofNullable(this.externalPort);
    }
    /**
     * @return The stable Dokploy MongoDB ID.
     *
     */
    public String mongoId() {
        return this.mongoId;
    }
    /**
     * @return The MongoDB database name.
     *
     */
    public String name() {
        return this.name;
    }
    /**
     * @return Whether replica sets are enabled, if supplied.
     *
     */
    public Optional<Boolean> replicaSets() {
        return Optional.ofNullable(this.replicaSets);
    }
    /**
     * @return The optional server ID metadata.
     *
     */
    public Optional<String> serverId() {
        return Optional.ofNullable(this.serverId);
    }
    /**
     * @return The optional application status.
     *
     */
    public Optional<String> status() {
        return Optional.ofNullable(this.status);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetMongoDBResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String appName;
        private @Nullable String databaseUser;
        private @Nullable String description;
        private @Nullable String dockerImage;
        private @Nullable String environmentId;
        private @Nullable Integer externalPort;
        private String mongoId;
        private String name;
        private @Nullable Boolean replicaSets;
        private @Nullable String serverId;
        private @Nullable String status;
        public Builder() {}
        public Builder(GetMongoDBResult defaults) {
              Objects.requireNonNull(defaults);
              this.appName = defaults.appName;
              this.databaseUser = defaults.databaseUser;
              this.description = defaults.description;
              this.dockerImage = defaults.dockerImage;
              this.environmentId = defaults.environmentId;
              this.externalPort = defaults.externalPort;
              this.mongoId = defaults.mongoId;
              this.name = defaults.name;
              this.replicaSets = defaults.replicaSets;
              this.serverId = defaults.serverId;
              this.status = defaults.status;
        }

        @CustomType.Setter
        public Builder appName(@Nullable String appName) {

            this.appName = appName;
            return this;
        }
        @CustomType.Setter
        public Builder databaseUser(@Nullable String databaseUser) {

            this.databaseUser = databaseUser;
            return this;
        }
        @CustomType.Setter
        public Builder description(@Nullable String description) {

            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder dockerImage(@Nullable String dockerImage) {

            this.dockerImage = dockerImage;
            return this;
        }
        @CustomType.Setter
        public Builder environmentId(@Nullable String environmentId) {

            this.environmentId = environmentId;
            return this;
        }
        @CustomType.Setter
        public Builder externalPort(@Nullable Integer externalPort) {

            this.externalPort = externalPort;
            return this;
        }
        @CustomType.Setter
        public Builder mongoId(String mongoId) {
            if (mongoId == null) {
              throw new MissingRequiredPropertyException("GetMongoDBResult", "mongoId");
            }
            this.mongoId = mongoId;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetMongoDBResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder replicaSets(@Nullable Boolean replicaSets) {

            this.replicaSets = replicaSets;
            return this;
        }
        @CustomType.Setter
        public Builder serverId(@Nullable String serverId) {

            this.serverId = serverId;
            return this;
        }
        @CustomType.Setter
        public Builder status(@Nullable String status) {

            this.status = status;
            return this;
        }
        public GetMongoDBResult build() {
            final var _resultValue = new GetMongoDBResult();
            _resultValue.appName = appName;
            _resultValue.databaseUser = databaseUser;
            _resultValue.description = description;
            _resultValue.dockerImage = dockerImage;
            _resultValue.environmentId = environmentId;
            _resultValue.externalPort = externalPort;
            _resultValue.mongoId = mongoId;
            _resultValue.name = name;
            _resultValue.replicaSets = replicaSets;
            _resultValue.serverId = serverId;
            _resultValue.status = status;
            return _resultValue;
        }
    }
}
