// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package net.dimeski.pulumi.dokploy.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetMariaDBResult {
    /**
     * @return The optional application name metadata.
     *
     */
    private @Nullable String appName;
    /**
     * @return The optional database name metadata.
     *
     */
    private @Nullable String databaseName;
    /**
     * @return The optional database username metadata.
     *
     */
    private @Nullable String databaseUser;
    /**
     * @return The optional description metadata.
     *
     */
    private @Nullable String description;
    /**
     * @return The optional Docker image metadata.
     *
     */
    private @Nullable String dockerImage;
    /**
     * @return The optional environment ID metadata.
     *
     */
    private @Nullable String environmentId;
    /**
     * @return The optional external port.
     *
     */
    private @Nullable Integer externalPort;
    /**
     * @return The stable Dokploy MariaDB ID.
     *
     */
    private String mariadbId;
    /**
     * @return The MariaDB database name.
     *
     */
    private String name;
    /**
     * @return The optional server ID metadata.
     *
     */
    private @Nullable String serverId;
    /**
     * @return The optional application status.
     *
     */
    private @Nullable String status;

    private GetMariaDBResult() {}
    /**
     * @return The optional application name metadata.
     *
     */
    public Optional<String> appName() {
        return Optional.ofNullable(this.appName);
    }
    /**
     * @return The optional database name metadata.
     *
     */
    public Optional<String> databaseName() {
        return Optional.ofNullable(this.databaseName);
    }
    /**
     * @return The optional database username metadata.
     *
     */
    public Optional<String> databaseUser() {
        return Optional.ofNullable(this.databaseUser);
    }
    /**
     * @return The optional description metadata.
     *
     */
    public Optional<String> description() {
        return Optional.ofNullable(this.description);
    }
    /**
     * @return The optional Docker image metadata.
     *
     */
    public Optional<String> dockerImage() {
        return Optional.ofNullable(this.dockerImage);
    }
    /**
     * @return The optional environment ID metadata.
     *
     */
    public Optional<String> environmentId() {
        return Optional.ofNullable(this.environmentId);
    }
    /**
     * @return The optional external port.
     *
     */
    public Optional<Integer> externalPort() {
        return Optional.ofNullable(this.externalPort);
    }
    /**
     * @return The stable Dokploy MariaDB ID.
     *
     */
    public String mariadbId() {
        return this.mariadbId;
    }
    /**
     * @return The MariaDB database name.
     *
     */
    public String name() {
        return this.name;
    }
    /**
     * @return The optional server ID metadata.
     *
     */
    public Optional<String> serverId() {
        return Optional.ofNullable(this.serverId);
    }
    /**
     * @return The optional application status.
     *
     */
    public Optional<String> status() {
        return Optional.ofNullable(this.status);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetMariaDBResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String appName;
        private @Nullable String databaseName;
        private @Nullable String databaseUser;
        private @Nullable String description;
        private @Nullable String dockerImage;
        private @Nullable String environmentId;
        private @Nullable Integer externalPort;
        private String mariadbId;
        private String name;
        private @Nullable String serverId;
        private @Nullable String status;
        public Builder() {}
        public Builder(GetMariaDBResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.appName = defaults.appName;
    	      this.databaseName = defaults.databaseName;
    	      this.databaseUser = defaults.databaseUser;
    	      this.description = defaults.description;
    	      this.dockerImage = defaults.dockerImage;
    	      this.environmentId = defaults.environmentId;
    	      this.externalPort = defaults.externalPort;
    	      this.mariadbId = defaults.mariadbId;
    	      this.name = defaults.name;
    	      this.serverId = defaults.serverId;
    	      this.status = defaults.status;
        }

        @CustomType.Setter
        public Builder appName(@Nullable String appName) {

            this.appName = appName;
            return this;
        }
        @CustomType.Setter
        public Builder databaseName(@Nullable String databaseName) {

            this.databaseName = databaseName;
            return this;
        }
        @CustomType.Setter
        public Builder databaseUser(@Nullable String databaseUser) {

            this.databaseUser = databaseUser;
            return this;
        }
        @CustomType.Setter
        public Builder description(@Nullable String description) {

            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder dockerImage(@Nullable String dockerImage) {

            this.dockerImage = dockerImage;
            return this;
        }
        @CustomType.Setter
        public Builder environmentId(@Nullable String environmentId) {

            this.environmentId = environmentId;
            return this;
        }
        @CustomType.Setter
        public Builder externalPort(@Nullable Integer externalPort) {

            this.externalPort = externalPort;
            return this;
        }
        @CustomType.Setter
        public Builder mariadbId(String mariadbId) {
            if (mariadbId == null) {
              throw new MissingRequiredPropertyException("GetMariaDBResult", "mariadbId");
            }
            this.mariadbId = mariadbId;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetMariaDBResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder serverId(@Nullable String serverId) {

            this.serverId = serverId;
            return this;
        }
        @CustomType.Setter
        public Builder status(@Nullable String status) {

            this.status = status;
            return this;
        }
        public GetMariaDBResult build() {
            final var _resultValue = new GetMariaDBResult();
            _resultValue.appName = appName;
            _resultValue.databaseName = databaseName;
            _resultValue.databaseUser = databaseUser;
            _resultValue.description = description;
            _resultValue.dockerImage = dockerImage;
            _resultValue.environmentId = environmentId;
            _resultValue.externalPort = externalPort;
            _resultValue.mariadbId = mariadbId;
            _resultValue.name = name;
            _resultValue.serverId = serverId;
            _resultValue.status = status;
            return _resultValue;
        }
    }
}
