// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package net.dimeski.pulumi.dokploy.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetProjectResult {
    /**
     * @return The optional default environment ID metadata.
     *
     */
    private @Nullable String defaultEnvironmentId;
    /**
     * @return The optional description metadata.
     *
     */
    private @Nullable String description;
    /**
     * @return The project name.
     *
     */
    private String name;
    /**
     * @return The stable Dokploy project ID.
     *
     */
    private String projectId;

    private GetProjectResult() {}
    /**
     * @return The optional default environment ID metadata.
     *
     */
    public Optional<String> defaultEnvironmentId() {
        return Optional.ofNullable(this.defaultEnvironmentId);
    }
    /**
     * @return The optional description metadata.
     *
     */
    public Optional<String> description() {
        return Optional.ofNullable(this.description);
    }
    /**
     * @return The project name.
     *
     */
    public String name() {
        return this.name;
    }
    /**
     * @return The stable Dokploy project ID.
     *
     */
    public String projectId() {
        return this.projectId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetProjectResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String defaultEnvironmentId;
        private @Nullable String description;
        private String name;
        private String projectId;
        public Builder() {}
        public Builder(GetProjectResult defaults) {
              Objects.requireNonNull(defaults);
              this.defaultEnvironmentId = defaults.defaultEnvironmentId;
              this.description = defaults.description;
              this.name = defaults.name;
              this.projectId = defaults.projectId;
        }

        @CustomType.Setter
        public Builder defaultEnvironmentId(@Nullable String defaultEnvironmentId) {

            this.defaultEnvironmentId = defaultEnvironmentId;
            return this;
        }
        @CustomType.Setter
        public Builder description(@Nullable String description) {

            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetProjectResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder projectId(String projectId) {
            if (projectId == null) {
              throw new MissingRequiredPropertyException("GetProjectResult", "projectId");
            }
            this.projectId = projectId;
            return this;
        }
        public GetProjectResult build() {
            final var _resultValue = new GetProjectResult();
            _resultValue.defaultEnvironmentId = defaultEnvironmentId;
            _resultValue.description = description;
            _resultValue.name = name;
            _resultValue.projectId = projectId;
            return _resultValue;
        }
    }
}
