// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package net.dimeski.pulumi.dokploy.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetRedisResult {
    /**
     * @return The optional application name metadata.
     *
     */
    private @Nullable String appName;
    /**
     * @return The optional description metadata.
     *
     */
    private @Nullable String description;
    /**
     * @return The optional Docker image metadata.
     *
     */
    private @Nullable String dockerImage;
    /**
     * @return The optional environment ID metadata.
     *
     */
    private @Nullable String environmentId;
    /**
     * @return The optional external port.
     *
     */
    private @Nullable Integer externalPort;
    /**
     * @return The Redis database name.
     *
     */
    private String name;
    /**
     * @return The stable Dokploy Redis ID.
     *
     */
    private String redisId;
    /**
     * @return The optional server ID metadata.
     *
     */
    private @Nullable String serverId;
    /**
     * @return The optional application status.
     *
     */
    private @Nullable String status;

    private GetRedisResult() {}
    /**
     * @return The optional application name metadata.
     *
     */
    public Optional<String> appName() {
        return Optional.ofNullable(this.appName);
    }
    /**
     * @return The optional description metadata.
     *
     */
    public Optional<String> description() {
        return Optional.ofNullable(this.description);
    }
    /**
     * @return The optional Docker image metadata.
     *
     */
    public Optional<String> dockerImage() {
        return Optional.ofNullable(this.dockerImage);
    }
    /**
     * @return The optional environment ID metadata.
     *
     */
    public Optional<String> environmentId() {
        return Optional.ofNullable(this.environmentId);
    }
    /**
     * @return The optional external port.
     *
     */
    public Optional<Integer> externalPort() {
        return Optional.ofNullable(this.externalPort);
    }
    /**
     * @return The Redis database name.
     *
     */
    public String name() {
        return this.name;
    }
    /**
     * @return The stable Dokploy Redis ID.
     *
     */
    public String redisId() {
        return this.redisId;
    }
    /**
     * @return The optional server ID metadata.
     *
     */
    public Optional<String> serverId() {
        return Optional.ofNullable(this.serverId);
    }
    /**
     * @return The optional application status.
     *
     */
    public Optional<String> status() {
        return Optional.ofNullable(this.status);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetRedisResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String appName;
        private @Nullable String description;
        private @Nullable String dockerImage;
        private @Nullable String environmentId;
        private @Nullable Integer externalPort;
        private String name;
        private String redisId;
        private @Nullable String serverId;
        private @Nullable String status;
        public Builder() {}
        public Builder(GetRedisResult defaults) {
              Objects.requireNonNull(defaults);
              this.appName = defaults.appName;
              this.description = defaults.description;
              this.dockerImage = defaults.dockerImage;
              this.environmentId = defaults.environmentId;
              this.externalPort = defaults.externalPort;
              this.name = defaults.name;
              this.redisId = defaults.redisId;
              this.serverId = defaults.serverId;
              this.status = defaults.status;
        }

        @CustomType.Setter
        public Builder appName(@Nullable String appName) {

            this.appName = appName;
            return this;
        }
        @CustomType.Setter
        public Builder description(@Nullable String description) {

            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder dockerImage(@Nullable String dockerImage) {

            this.dockerImage = dockerImage;
            return this;
        }
        @CustomType.Setter
        public Builder environmentId(@Nullable String environmentId) {

            this.environmentId = environmentId;
            return this;
        }
        @CustomType.Setter
        public Builder externalPort(@Nullable Integer externalPort) {

            this.externalPort = externalPort;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetRedisResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder redisId(String redisId) {
            if (redisId == null) {
              throw new MissingRequiredPropertyException("GetRedisResult", "redisId");
            }
            this.redisId = redisId;
            return this;
        }
        @CustomType.Setter
        public Builder serverId(@Nullable String serverId) {

            this.serverId = serverId;
            return this;
        }
        @CustomType.Setter
        public Builder status(@Nullable String status) {

            this.status = status;
            return this;
        }
        public GetRedisResult build() {
            final var _resultValue = new GetRedisResult();
            _resultValue.appName = appName;
            _resultValue.description = description;
            _resultValue.dockerImage = dockerImage;
            _resultValue.environmentId = environmentId;
            _resultValue.externalPort = externalPort;
            _resultValue.name = name;
            _resultValue.redisId = redisId;
            _resultValue.serverId = serverId;
            _resultValue.status = status;
            return _resultValue;
        }
    }
}
