// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package net.dimeski.pulumi.dokploy.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetSSHKeyResult {
    /**
     * @return The optional description metadata.
     *
     */
    private @Nullable String description;
    /**
     * @return The SSH key name.
     *
     */
    private String name;
    /**
     * @return The optional organization ID metadata.
     *
     */
    private @Nullable String organizationId;
    /**
     * @return The optional public key metadata.
     *
     */
    private @Nullable String publicKey;
    /**
     * @return The stable Dokploy SSH key ID.
     *
     */
    private String sshKeyId;

    private GetSSHKeyResult() {}
    /**
     * @return The optional description metadata.
     *
     */
    public Optional<String> description() {
        return Optional.ofNullable(this.description);
    }
    /**
     * @return The SSH key name.
     *
     */
    public String name() {
        return this.name;
    }
    /**
     * @return The optional organization ID metadata.
     *
     */
    public Optional<String> organizationId() {
        return Optional.ofNullable(this.organizationId);
    }
    /**
     * @return The optional public key metadata.
     *
     */
    public Optional<String> publicKey() {
        return Optional.ofNullable(this.publicKey);
    }
    /**
     * @return The stable Dokploy SSH key ID.
     *
     */
    public String sshKeyId() {
        return this.sshKeyId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetSSHKeyResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String description;
        private String name;
        private @Nullable String organizationId;
        private @Nullable String publicKey;
        private String sshKeyId;
        public Builder() {}
        public Builder(GetSSHKeyResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.description = defaults.description;
    	      this.name = defaults.name;
    	      this.organizationId = defaults.organizationId;
    	      this.publicKey = defaults.publicKey;
    	      this.sshKeyId = defaults.sshKeyId;
        }

        @CustomType.Setter
        public Builder description(@Nullable String description) {

            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetSSHKeyResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder organizationId(@Nullable String organizationId) {

            this.organizationId = organizationId;
            return this;
        }
        @CustomType.Setter
        public Builder publicKey(@Nullable String publicKey) {

            this.publicKey = publicKey;
            return this;
        }
        @CustomType.Setter
        public Builder sshKeyId(String sshKeyId) {
            if (sshKeyId == null) {
              throw new MissingRequiredPropertyException("GetSSHKeyResult", "sshKeyId");
            }
            this.sshKeyId = sshKeyId;
            return this;
        }
        public GetSSHKeyResult build() {
            final var _resultValue = new GetSSHKeyResult();
            _resultValue.description = description;
            _resultValue.name = name;
            _resultValue.organizationId = organizationId;
            _resultValue.publicKey = publicKey;
            _resultValue.sshKeyId = sshKeyId;
            return _resultValue;
        }
    }
}
