// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package net.dimeski.pulumi.dokploy.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GitHubComposeSource {
    /**
     * @return The GitHub branch.
     * 
     */
    private String branch;
    /**
     * @return The Compose file path.
     * 
     */
    private @Nullable String composePath;
    /**
     * @return Whether to enable submodules.
     * 
     */
    private @Nullable Boolean enableSubmodules;
    /**
     * @return The GitHub integration ID.
     * 
     */
    private String integrationId;
    /**
     * @return The GitHub owner.
     * 
     */
    private String owner;
    /**
     * @return The GitHub repository.
     * 
     */
    private String repository;
    /**
     * @return The deployment trigger type, either push or tag.
     * 
     */
    private @Nullable String triggerType;
    /**
     * @return Paths to watch.
     * 
     */
    private @Nullable List<String> watchPaths;

    private GitHubComposeSource() {}
    /**
     * @return The GitHub branch.
     * 
     */
    public String branch() {
        return this.branch;
    }
    /**
     * @return The Compose file path.
     * 
     */
    public Optional<String> composePath() {
        return Optional.ofNullable(this.composePath);
    }
    /**
     * @return Whether to enable submodules.
     * 
     */
    public Optional<Boolean> enableSubmodules() {
        return Optional.ofNullable(this.enableSubmodules);
    }
    /**
     * @return The GitHub integration ID.
     * 
     */
    public String integrationId() {
        return this.integrationId;
    }
    /**
     * @return The GitHub owner.
     * 
     */
    public String owner() {
        return this.owner;
    }
    /**
     * @return The GitHub repository.
     * 
     */
    public String repository() {
        return this.repository;
    }
    /**
     * @return The deployment trigger type, either push or tag.
     * 
     */
    public Optional<String> triggerType() {
        return Optional.ofNullable(this.triggerType);
    }
    /**
     * @return Paths to watch.
     * 
     */
    public List<String> watchPaths() {
        return this.watchPaths == null ? List.of() : this.watchPaths;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GitHubComposeSource defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String branch;
        private @Nullable String composePath;
        private @Nullable Boolean enableSubmodules;
        private String integrationId;
        private String owner;
        private String repository;
        private @Nullable String triggerType;
        private @Nullable List<String> watchPaths;
        public Builder() {}
        public Builder(GitHubComposeSource defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.branch = defaults.branch;
    	      this.composePath = defaults.composePath;
    	      this.enableSubmodules = defaults.enableSubmodules;
    	      this.integrationId = defaults.integrationId;
    	      this.owner = defaults.owner;
    	      this.repository = defaults.repository;
    	      this.triggerType = defaults.triggerType;
    	      this.watchPaths = defaults.watchPaths;
        }

        @CustomType.Setter
        public Builder branch(String branch) {
            if (branch == null) {
              throw new MissingRequiredPropertyException("GitHubComposeSource", "branch");
            }
            this.branch = branch;
            return this;
        }
        @CustomType.Setter
        public Builder composePath(@Nullable String composePath) {

            this.composePath = composePath;
            return this;
        }
        @CustomType.Setter
        public Builder enableSubmodules(@Nullable Boolean enableSubmodules) {

            this.enableSubmodules = enableSubmodules;
            return this;
        }
        @CustomType.Setter
        public Builder integrationId(String integrationId) {
            if (integrationId == null) {
              throw new MissingRequiredPropertyException("GitHubComposeSource", "integrationId");
            }
            this.integrationId = integrationId;
            return this;
        }
        @CustomType.Setter
        public Builder owner(String owner) {
            if (owner == null) {
              throw new MissingRequiredPropertyException("GitHubComposeSource", "owner");
            }
            this.owner = owner;
            return this;
        }
        @CustomType.Setter
        public Builder repository(String repository) {
            if (repository == null) {
              throw new MissingRequiredPropertyException("GitHubComposeSource", "repository");
            }
            this.repository = repository;
            return this;
        }
        @CustomType.Setter
        public Builder triggerType(@Nullable String triggerType) {

            this.triggerType = triggerType;
            return this;
        }
        @CustomType.Setter
        public Builder watchPaths(@Nullable List<String> watchPaths) {

            this.watchPaths = watchPaths;
            return this;
        }
        public Builder watchPaths(String... watchPaths) {
            return watchPaths(List.of(watchPaths));
        }
        public GitHubComposeSource build() {
            final var _resultValue = new GitHubComposeSource();
            _resultValue.branch = branch;
            _resultValue.composePath = composePath;
            _resultValue.enableSubmodules = enableSubmodules;
            _resultValue.integrationId = integrationId;
            _resultValue.owner = owner;
            _resultValue.repository = repository;
            _resultValue.triggerType = triggerType;
            _resultValue.watchPaths = watchPaths;
            return _resultValue;
        }
    }
}
