// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package net.dimeski.pulumi.dokploy.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class NotificationGotifyConfig {
    /**
     * @return Secret Gotify application token.
     *
     */
    private String appToken;
    /**
     * @return Whether to decorate messages; defaults to false.
     *
     */
    private @Nullable Boolean decoration;
    /**
     * @return Message priority; defaults to 5 (minimum 1).
     *
     */
    private @Nullable Integer priority;
    /**
     * @return Secret Gotify server URL.
     *
     */
    private String serverUrl;

    private NotificationGotifyConfig() {}
    /**
     * @return Secret Gotify application token.
     *
     */
    public String appToken() {
        return this.appToken;
    }
    /**
     * @return Whether to decorate messages; defaults to false.
     *
     */
    public Optional<Boolean> decoration() {
        return Optional.ofNullable(this.decoration);
    }
    /**
     * @return Message priority; defaults to 5 (minimum 1).
     *
     */
    public Optional<Integer> priority() {
        return Optional.ofNullable(this.priority);
    }
    /**
     * @return Secret Gotify server URL.
     *
     */
    public String serverUrl() {
        return this.serverUrl;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NotificationGotifyConfig defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String appToken;
        private @Nullable Boolean decoration;
        private @Nullable Integer priority;
        private String serverUrl;
        public Builder() {}
        public Builder(NotificationGotifyConfig defaults) {
	      Objects.requireNonNull(defaults);
	      this.appToken = defaults.appToken;
	      this.decoration = defaults.decoration;
	      this.priority = defaults.priority;
	      this.serverUrl = defaults.serverUrl;
        }

        @CustomType.Setter
        public Builder appToken(String appToken) {
            if (appToken == null) {
              throw new MissingRequiredPropertyException("NotificationGotifyConfig", "appToken");
            }
            this.appToken = appToken;
            return this;
        }
        @CustomType.Setter
        public Builder decoration(@Nullable Boolean decoration) {

            this.decoration = decoration;
            return this;
        }
        @CustomType.Setter
        public Builder priority(@Nullable Integer priority) {

            this.priority = priority;
            return this;
        }
        @CustomType.Setter
        public Builder serverUrl(String serverUrl) {
            if (serverUrl == null) {
              throw new MissingRequiredPropertyException("NotificationGotifyConfig", "serverUrl");
            }
            this.serverUrl = serverUrl;
            return this;
        }
        public NotificationGotifyConfig build() {
            final var _resultValue = new NotificationGotifyConfig();
            _resultValue.appToken = appToken;
            _resultValue.decoration = decoration;
            _resultValue.priority = priority;
            _resultValue.serverUrl = serverUrl;
            return _resultValue;
        }
    }
}
