// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package net.dimeski.pulumi.dokploy.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class NotificationPushoverConfig {
    /**
     * @return Secret Pushover API token.
     *
     */
    private String apiToken;
    /**
     * @return Emergency expiry in seconds, 1 through 10800; required for priority 2.
     *
     */
    private @Nullable Integer expire;
    /**
     * @return Priority from -2 through 2; defaults to 0.
     *
     */
    private @Nullable Integer priority;
    /**
     * @return Emergency retry interval in seconds, at least 30; required for priority 2.
     *
     */
    private @Nullable Integer retry;
    /**
     * @return Secret Pushover user key.
     *
     */
    private String userKey;

    private NotificationPushoverConfig() {}
    /**
     * @return Secret Pushover API token.
     *
     */
    public String apiToken() {
        return this.apiToken;
    }
    /**
     * @return Emergency expiry in seconds, 1 through 10800; required for priority 2.
     *
     */
    public Optional<Integer> expire() {
        return Optional.ofNullable(this.expire);
    }
    /**
     * @return Priority from -2 through 2; defaults to 0.
     *
     */
    public Optional<Integer> priority() {
        return Optional.ofNullable(this.priority);
    }
    /**
     * @return Emergency retry interval in seconds, at least 30; required for priority 2.
     *
     */
    public Optional<Integer> retry() {
        return Optional.ofNullable(this.retry);
    }
    /**
     * @return Secret Pushover user key.
     *
     */
    public String userKey() {
        return this.userKey;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NotificationPushoverConfig defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String apiToken;
        private @Nullable Integer expire;
        private @Nullable Integer priority;
        private @Nullable Integer retry;
        private String userKey;
        public Builder() {}
        public Builder(NotificationPushoverConfig defaults) {
	      Objects.requireNonNull(defaults);
	      this.apiToken = defaults.apiToken;
	      this.expire = defaults.expire;
	      this.priority = defaults.priority;
	      this.retry = defaults.retry;
	      this.userKey = defaults.userKey;
        }

        @CustomType.Setter
        public Builder apiToken(String apiToken) {
            if (apiToken == null) {
              throw new MissingRequiredPropertyException("NotificationPushoverConfig", "apiToken");
            }
            this.apiToken = apiToken;
            return this;
        }
        @CustomType.Setter
        public Builder expire(@Nullable Integer expire) {

            this.expire = expire;
            return this;
        }
        @CustomType.Setter
        public Builder priority(@Nullable Integer priority) {

            this.priority = priority;
            return this;
        }
        @CustomType.Setter
        public Builder retry(@Nullable Integer retry) {

            this.retry = retry;
            return this;
        }
        @CustomType.Setter
        public Builder userKey(String userKey) {
            if (userKey == null) {
              throw new MissingRequiredPropertyException("NotificationPushoverConfig", "userKey");
            }
            this.userKey = userKey;
            return this;
        }
        public NotificationPushoverConfig build() {
            final var _resultValue = new NotificationPushoverConfig();
            _resultValue.apiToken = apiToken;
            _resultValue.expire = expire;
            _resultValue.priority = priority;
            _resultValue.retry = retry;
            _resultValue.userKey = userKey;
            return _resultValue;
        }
    }
}
