// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package dev.codechem.pulumi.dokploy.dokploy;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import dev.codechem.pulumi.dokploy.dokploy.RedisArgs;
import dev.codechem.pulumi.dokploy.dokploy.Utilities;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * A Dokploy Redis database.
 * 
 */
@ResourceType(type="dokploy:index:Redis")
public class Redis extends com.pulumi.resources.CustomResource {
    /**
     * The optional deployed database name.
     * 
     */
    @Export(name="appName", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> appName;

    /**
     * @return The optional deployed database name.
     * 
     */
    public Output<Optional<String>> appName() {
        return Codegen.optional(this.appName);
    }
    /**
     * The Redis database password.
     * 
     */
    @Export(name="databasePassword", refs={String.class}, tree="[0]")
    private Output<String> databasePassword;

    /**
     * @return The Redis database password.
     * 
     */
    public Output<String> databasePassword() {
        return this.databasePassword;
    }
    /**
     * An optional database description.
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    /**
     * @return An optional database description.
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * The Redis Docker image.
     * 
     */
    @Export(name="dockerImage", refs={String.class}, tree="[0]")
    private Output<String> dockerImage;

    /**
     * @return The Redis Docker image.
     * 
     */
    public Output<String> dockerImage() {
        return this.dockerImage;
    }
    /**
     * Environment variables for Redis.
     * 
     */
    @Export(name="environment", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> environment;

    /**
     * @return Environment variables for Redis.
     * 
     */
    public Output<Optional<String>> environment() {
        return Codegen.optional(this.environment);
    }
    /**
     * The target environment ID.
     * 
     */
    @Export(name="environmentId", refs={String.class}, tree="[0]")
    private Output<String> environmentId;

    /**
     * @return The target environment ID.
     * 
     */
    public Output<String> environmentId() {
        return this.environmentId;
    }
    /**
     * The optional externally exposed port.
     * 
     */
    @Export(name="externalPort", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> externalPort;

    /**
     * @return The optional externally exposed port.
     * 
     */
    public Output<Optional<Integer>> externalPort() {
        return Codegen.optional(this.externalPort);
    }
    /**
     * The database resource name.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The database resource name.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The stable Dokploy Redis ID.
     * 
     */
    @Export(name="redisId", refs={String.class}, tree="[0]")
    private Output<String> redisId;

    /**
     * @return The stable Dokploy Redis ID.
     * 
     */
    public Output<String> redisId() {
        return this.redisId;
    }
    /**
     * The optional server ID.
     * 
     */
    @Export(name="serverId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> serverId;

    /**
     * @return The optional server ID.
     * 
     */
    public Output<Optional<String>> serverId() {
        return Codegen.optional(this.serverId);
    }
    /**
     * The current Redis deployment status.
     * 
     */
    @Export(name="status", refs={String.class}, tree="[0]")
    private Output<String> status;

    /**
     * @return The current Redis deployment status.
     * 
     */
    public Output<String> status() {
        return this.status;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Redis(java.lang.String name) {
        this(name, RedisArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Redis(java.lang.String name, RedisArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Redis(java.lang.String name, RedisArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("dokploy:index:Redis", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Redis(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("dokploy:index:Redis", name, null, makeResourceOptions(options, id), false);
    }

    private static RedisArgs makeArgs(RedisArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? RedisArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .additionalSecretOutputs(List.of(
                "databasePassword",
                "environment"
            ))
            .replaceOnChanges(List.of(
                "environmentId",
                "serverId"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Redis get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Redis(name, id, options);
    }
}
