// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Dimeskigj.Pulumi.Dokploy.Outputs
{

    /// <summary>
    /// GitHub source configuration.
    /// </summary>
    [OutputType]
    public sealed class GitHubAppSource
    {
        /// <summary>
        /// The GitHub branch.
        /// </summary>
        public readonly string Branch;
        /// <summary>
        /// The build configuration.
        /// </summary>
        public readonly Outputs.ApplicationBuild Build;
        /// <summary>
        /// The build path.
        /// </summary>
        public readonly string? BuildPath;
        /// <summary>
        /// Whether to enable submodules.
        /// </summary>
        public readonly bool? EnableSubmodules;
        /// <summary>
        /// The GitHub integration ID.
        /// </summary>
        public readonly string IntegrationId;
        /// <summary>
        /// The GitHub owner.
        /// </summary>
        public readonly string Owner;
        /// <summary>
        /// The GitHub repository.
        /// </summary>
        public readonly string Repository;
        /// <summary>
        /// The deployment trigger type, either push or tag.
        /// </summary>
        public readonly string? TriggerType;
        /// <summary>
        /// Paths to watch.
        /// </summary>
        public readonly ImmutableArray<string> WatchPaths;

        [OutputConstructor]
        private GitHubAppSource(
            string branch,

            Outputs.ApplicationBuild build,

            string? buildPath,

            bool? enableSubmodules,

            string integrationId,

            string owner,

            string repository,

            string? triggerType,

            ImmutableArray<string> watchPaths)
        {
            Branch = branch;
            Build = build;
            BuildPath = buildPath;
            EnableSubmodules = enableSubmodules;
            IntegrationId = integrationId;
            Owner = owner;
            Repository = repository;
            TriggerType = triggerType;
            WatchPaths = watchPaths;
        }
    }
}
