// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Dimeskigj.Pulumi.Dokploy.Outputs
{

    [OutputType]
    public sealed class NotificationLarkConfig
    {
        /// <summary>
        /// Secret Lark webhook URL.
        /// </summary>
        public readonly string WebhookUrl;

        [OutputConstructor]
        private NotificationLarkConfig(string webhookUrl)
        {
            WebhookUrl = webhookUrl;
        }
    }
}
