// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Dimeskigj.Pulumi.Dokploy.Outputs
{

    [OutputType]
    public sealed class NotificationNtfyConfig
    {
        /// <summary>
        /// Optional secret access token; defaults to empty.
        /// </summary>
        public readonly string? AccessToken;
        /// <summary>
        /// Message priority, 1 through 5; defaults to 3.
        /// </summary>
        public readonly int? Priority;
        /// <summary>
        /// Secret Ntfy server URL.
        /// </summary>
        public readonly string ServerUrl;
        /// <summary>
        /// Ntfy topic.
        /// </summary>
        public readonly string Topic;

        [OutputConstructor]
        private NotificationNtfyConfig(
            string? accessToken,

            int? priority,

            string serverUrl,

            string topic)
        {
            AccessToken = accessToken;
            Priority = priority;
            ServerUrl = serverUrl;
            Topic = topic;
        }
    }
}
