// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Dimeskigj.Pulumi.Dokploy.Outputs
{

    [OutputType]
    public sealed class NotificationPushoverConfig
    {
        /// <summary>
        /// Secret Pushover API token.
        /// </summary>
        public readonly string ApiToken;
        /// <summary>
        /// Emergency expiry in seconds, 1 through 10800; required for priority 2.
        /// </summary>
        public readonly int? Expire;
        /// <summary>
        /// Priority from -2 through 2; defaults to 0.
        /// </summary>
        public readonly int? Priority;
        /// <summary>
        /// Emergency retry interval in seconds, at least 30; required for priority 2.
        /// </summary>
        public readonly int? Retry;
        /// <summary>
        /// Secret Pushover user key.
        /// </summary>
        public readonly string UserKey;

        [OutputConstructor]
        private NotificationPushoverConfig(
            string apiToken,

            int? expire,

            int? priority,

            int? retry,

            string userKey)
        {
            ApiToken = apiToken;
            Expire = expire;
            Priority = priority;
            Retry = retry;
            UserKey = userKey;
        }
    }
}
