// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Dimeskigj.Pulumi.Dokploy.Outputs
{

    [OutputType]
    public sealed class NotificationCustomConfig
    {
        /// <summary>
        /// Secret HTTP(S) destination URL.
        /// </summary>
        public readonly string Endpoint;
        /// <summary>
        /// Secret custom HTTP headers; defaults to an empty map.
        /// </summary>
        public readonly ImmutableDictionary<string, string>? Headers;

        [OutputConstructor]
        private NotificationCustomConfig(
            string endpoint,

            ImmutableDictionary<string, string>? headers)
        {
            Endpoint = endpoint;
            Headers = headers;
        }
    }
}
