// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Dimeskigj.Pulumi.Dokploy.Outputs
{

    [OutputType]
    public sealed class NotificationMattermostConfig
    {
        /// <summary>
        /// Optional routing channel; defaults to empty.
        /// </summary>
        public readonly string? Channel;
        /// <summary>
        /// Optional display username; defaults to empty.
        /// </summary>
        public readonly string? Username;
        /// <summary>
        /// Secret Mattermost webhook URL.
        /// </summary>
        public readonly string WebhookUrl;

        [OutputConstructor]
        private NotificationMattermostConfig(
            string? channel,

            string? username,

            string webhookUrl)
        {
            Channel = channel;
            Username = username;
            WebhookUrl = webhookUrl;
        }
    }
}
