// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Dokploy.Outputs
{

    /// <summary>
    /// Git source configuration.
    /// </summary>
    [OutputType]
    public sealed class GitApplicationSource
    {
        /// <summary>
        /// The Git branch.
        /// </summary>
        public readonly string Branch;
        /// <summary>
        /// The build configuration.
        /// </summary>
        public readonly Outputs.ApplicationBuild Build;
        /// <summary>
        /// The build path.
        /// </summary>
        public readonly string? BuildPath;
        /// <summary>
        /// Whether to enable submodules.
        /// </summary>
        public readonly bool? EnableSubmodules;
        /// <summary>
        /// The SSH key ID.
        /// </summary>
        public readonly string? SshKeyId;
        /// <summary>
        /// The Git repository URL.
        /// </summary>
        public readonly string Url;
        /// <summary>
        /// Paths to watch.
        /// </summary>
        public readonly ImmutableArray<string> WatchPaths;

        [OutputConstructor]
        private GitApplicationSource(
            string branch,

            Outputs.ApplicationBuild build,

            string? buildPath,

            bool? enableSubmodules,

            string? sshKeyId,

            string url,

            ImmutableArray<string> watchPaths)
        {
            Branch = branch;
            Build = build;
            BuildPath = buildPath;
            EnableSubmodules = enableSubmodules;
            SshKeyId = sshKeyId;
            Url = url;
            WatchPaths = watchPaths;
        }
    }
}
