// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package net.dimeski.pulumi.dokploy;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;
import net.dimeski.pulumi.dokploy.BackupArgs;
import net.dimeski.pulumi.dokploy.Utilities;

/**
 * A scheduled Dokploy database backup. Exactly one of postgresId, mysqlId, mariadbId, or mongoId must be set.
 * 
 */
@ResourceType(type="dokploy:index:Backup")
public class Backup extends com.pulumi.resources.CustomResource {
    /**
     * The stable Dokploy backup ID.
     * 
     */
    @Export(name="backupId", refs={String.class}, tree="[0]")
    private Output<String> backupId;

    /**
     * @return The stable Dokploy backup ID.
     * 
     */
    public Output<String> backupId() {
        return this.backupId;
    }
    /**
     * The database name inside the target instance to back up.
     * 
     */
    @Export(name="database", refs={String.class}, tree="[0]")
    private Output<String> database;

    /**
     * @return The database name inside the target instance to back up.
     * 
     */
    public Output<String> database() {
        return this.database;
    }
    /**
     * The destination ID backups are stored to.
     * 
     */
    @Export(name="destinationId", refs={String.class}, tree="[0]")
    private Output<String> destinationId;

    /**
     * @return The destination ID backups are stored to.
     * 
     */
    public Output<String> destinationId() {
        return this.destinationId;
    }
    /**
     * Whether the backup schedule is enabled.
     * 
     */
    @Export(name="enabled", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> enabled;

    /**
     * @return Whether the backup schedule is enabled.
     * 
     */
    public Output<Boolean> enabled() {
        return this.enabled;
    }
    /**
     * The optional number of most recent backups to retain.
     * 
     */
    @Export(name="keepLatestCount", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> keepLatestCount;

    /**
     * @return The optional number of most recent backups to retain.
     * 
     */
    public Output<Optional<Integer>> keepLatestCount() {
        return Codegen.optional(this.keepLatestCount);
    }
    /**
     * The target MariaDB ID.
     * 
     */
    @Export(name="mariadbId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> mariadbId;

    /**
     * @return The target MariaDB ID.
     * 
     */
    public Output<Optional<String>> mariadbId() {
        return Codegen.optional(this.mariadbId);
    }
    /**
     * The target MongoDB ID.
     * 
     */
    @Export(name="mongoId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> mongoId;

    /**
     * @return The target MongoDB ID.
     * 
     */
    public Output<Optional<String>> mongoId() {
        return Codegen.optional(this.mongoId);
    }
    /**
     * The target MySQL ID.
     * 
     */
    @Export(name="mysqlId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> mysqlId;

    /**
     * @return The target MySQL ID.
     * 
     */
    public Output<Optional<String>> mysqlId() {
        return Codegen.optional(this.mysqlId);
    }
    /**
     * The target Postgres ID.
     * 
     */
    @Export(name="postgresId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> postgresId;

    /**
     * @return The target Postgres ID.
     * 
     */
    public Output<Optional<String>> postgresId() {
        return Codegen.optional(this.postgresId);
    }
    /**
     * The backup file prefix.
     * 
     */
    @Export(name="prefix", refs={String.class}, tree="[0]")
    private Output<String> prefix;

    /**
     * @return The backup file prefix.
     * 
     */
    public Output<String> prefix() {
        return this.prefix;
    }
    /**
     * The backup cron schedule.
     * 
     */
    @Export(name="schedule", refs={String.class}, tree="[0]")
    private Output<String> schedule;

    /**
     * @return The backup cron schedule.
     * 
     */
    public Output<String> schedule() {
        return this.schedule;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Backup(java.lang.String name) {
        this(name, BackupArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Backup(java.lang.String name, BackupArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Backup(java.lang.String name, BackupArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("dokploy:index:Backup", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Backup(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("dokploy:index:Backup", name, null, makeResourceOptions(options, id), false);
    }

    private static BackupArgs makeArgs(BackupArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? BackupArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .replaceOnChanges(List.of(
                "mariadbId",
                "mongoId",
                "mysqlId",
                "postgresId"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Backup get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Backup(name, id, options);
    }
}
