// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package net.dimeski.pulumi.dokploy;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;
import net.dimeski.pulumi.dokploy.NotificationArgs;
import net.dimeski.pulumi.dokploy.Utilities;
import net.dimeski.pulumi.dokploy.outputs.NotificationCustomConfig;
import net.dimeski.pulumi.dokploy.outputs.NotificationDiscordConfig;
import net.dimeski.pulumi.dokploy.outputs.NotificationEmailConfig;
import net.dimeski.pulumi.dokploy.outputs.NotificationEvents;
import net.dimeski.pulumi.dokploy.outputs.NotificationGotifyConfig;
import net.dimeski.pulumi.dokploy.outputs.NotificationLarkConfig;
import net.dimeski.pulumi.dokploy.outputs.NotificationMattermostConfig;
import net.dimeski.pulumi.dokploy.outputs.NotificationNtfyConfig;
import net.dimeski.pulumi.dokploy.outputs.NotificationPushoverConfig;
import net.dimeski.pulumi.dokploy.outputs.NotificationResendConfig;
import net.dimeski.pulumi.dokploy.outputs.NotificationSlackConfig;
import net.dimeski.pulumi.dokploy.outputs.NotificationTeamsConfig;
import net.dimeski.pulumi.dokploy.outputs.NotificationTelegramConfig;

/**
 * A Dokploy notification destination and its event subscriptions.
 *
 */
@ResourceType(type="dokploy:index:Notification")
public class Notification extends com.pulumi.resources.CustomResource {
    /**
     * Stable selected channel relation ID.
     *
     */
    @Export(name="channelId", refs={String.class}, tree="[0]")
    private Output<String> channelId;

    /**
     * @return Stable selected channel relation ID.
     *
     */
    public Output<String> channelId() {
        return this.channelId;
    }
    /**
     * Custom HTTP destination; select exactly one channel block.
     *
     */
    @Export(name="custom", refs={NotificationCustomConfig.class}, tree="[0]")
    private Output</* @Nullable */ NotificationCustomConfig> custom;

    /**
     * @return Custom HTTP destination; select exactly one channel block.
     *
     */
    public Output<Optional<NotificationCustomConfig>> custom() {
        return Codegen.optional(this.custom);
    }
    /**
     * Discord destination; select exactly one channel block.
     *
     */
    @Export(name="discord", refs={NotificationDiscordConfig.class}, tree="[0]")
    private Output</* @Nullable */ NotificationDiscordConfig> discord;

    /**
     * @return Discord destination; select exactly one channel block.
     *
     */
    public Output<Optional<NotificationDiscordConfig>> discord() {
        return Codegen.optional(this.discord);
    }
    /**
     * SMTP email destination; select exactly one channel block.
     *
     */
    @Export(name="email", refs={NotificationEmailConfig.class}, tree="[0]")
    private Output</* @Nullable */ NotificationEmailConfig> email;

    /**
     * @return SMTP email destination; select exactly one channel block.
     *
     */
    public Output<Optional<NotificationEmailConfig>> email() {
        return Codegen.optional(this.email);
    }
    /**
     * Optional event subscriptions; every omitted event defaults to false.
     *
     */
    @Export(name="events", refs={NotificationEvents.class}, tree="[0]")
    private Output</* @Nullable */ NotificationEvents> events;

    /**
     * @return Optional event subscriptions; every omitted event defaults to false.
     *
     */
    public Output<Optional<NotificationEvents>> events() {
        return Codegen.optional(this.events);
    }
    /**
     * Gotify destination; select exactly one channel block.
     *
     */
    @Export(name="gotify", refs={NotificationGotifyConfig.class}, tree="[0]")
    private Output</* @Nullable */ NotificationGotifyConfig> gotify;

    /**
     * @return Gotify destination; select exactly one channel block.
     *
     */
    public Output<Optional<NotificationGotifyConfig>> gotify() {
        return Codegen.optional(this.gotify);
    }
    /**
     * Lark destination; select exactly one channel block.
     *
     */
    @Export(name="lark", refs={NotificationLarkConfig.class}, tree="[0]")
    private Output</* @Nullable */ NotificationLarkConfig> lark;

    /**
     * @return Lark destination; select exactly one channel block.
     *
     */
    public Output<Optional<NotificationLarkConfig>> lark() {
        return Codegen.optional(this.lark);
    }
    /**
     * Mattermost destination; select exactly one channel block.
     *
     */
    @Export(name="mattermost", refs={NotificationMattermostConfig.class}, tree="[0]")
    private Output</* @Nullable */ NotificationMattermostConfig> mattermost;

    /**
     * @return Mattermost destination; select exactly one channel block.
     *
     */
    public Output<Optional<NotificationMattermostConfig>> mattermost() {
        return Codegen.optional(this.mattermost);
    }
    /**
     * Required notification name.
     *
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return Required notification name.
     *
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * Stable Dokploy notification ID.
     *
     */
    @Export(name="notificationId", refs={String.class}, tree="[0]")
    private Output<String> notificationId;

    /**
     * @return Stable Dokploy notification ID.
     *
     */
    public Output<String> notificationId() {
        return this.notificationId;
    }
    /**
     * Selected notification channel type.
     *
     */
    @Export(name="notificationType", refs={String.class}, tree="[0]")
    private Output<String> notificationType;

    /**
     * @return Selected notification channel type.
     *
     */
    public Output<String> notificationType() {
        return this.notificationType;
    }
    /**
     * Ntfy destination; select exactly one channel block.
     *
     */
    @Export(name="ntfy", refs={NotificationNtfyConfig.class}, tree="[0]")
    private Output</* @Nullable */ NotificationNtfyConfig> ntfy;

    /**
     * @return Ntfy destination; select exactly one channel block.
     *
     */
    public Output<Optional<NotificationNtfyConfig>> ntfy() {
        return Codegen.optional(this.ntfy);
    }
    /**
     * Owning Dokploy organization ID.
     *
     */
    @Export(name="organizationId", refs={String.class}, tree="[0]")
    private Output<String> organizationId;

    /**
     * @return Owning Dokploy organization ID.
     *
     */
    public Output<String> organizationId() {
        return this.organizationId;
    }
    /**
     * Pushover destination; select exactly one channel block.
     *
     */
    @Export(name="pushover", refs={NotificationPushoverConfig.class}, tree="[0]")
    private Output</* @Nullable */ NotificationPushoverConfig> pushover;

    /**
     * @return Pushover destination; select exactly one channel block.
     *
     */
    public Output<Optional<NotificationPushoverConfig>> pushover() {
        return Codegen.optional(this.pushover);
    }
    /**
     * Resend email destination; select exactly one channel block.
     *
     */
    @Export(name="resend", refs={NotificationResendConfig.class}, tree="[0]")
    private Output</* @Nullable */ NotificationResendConfig> resend;

    /**
     * @return Resend email destination; select exactly one channel block.
     *
     */
    public Output<Optional<NotificationResendConfig>> resend() {
        return Codegen.optional(this.resend);
    }
    /**
     * Slack destination; select exactly one channel block.
     *
     */
    @Export(name="slack", refs={NotificationSlackConfig.class}, tree="[0]")
    private Output</* @Nullable */ NotificationSlackConfig> slack;

    /**
     * @return Slack destination; select exactly one channel block.
     *
     */
    public Output<Optional<NotificationSlackConfig>> slack() {
        return Codegen.optional(this.slack);
    }
    /**
     * Teams destination; select exactly one channel block.
     *
     */
    @Export(name="teams", refs={NotificationTeamsConfig.class}, tree="[0]")
    private Output</* @Nullable */ NotificationTeamsConfig> teams;

    /**
     * @return Teams destination; select exactly one channel block.
     *
     */
    public Output<Optional<NotificationTeamsConfig>> teams() {
        return Codegen.optional(this.teams);
    }
    /**
     * Telegram destination; select exactly one channel block.
     *
     */
    @Export(name="telegram", refs={NotificationTelegramConfig.class}, tree="[0]")
    private Output</* @Nullable */ NotificationTelegramConfig> telegram;

    /**
     * @return Telegram destination; select exactly one channel block.
     *
     */
    public Output<Optional<NotificationTelegramConfig>> telegram() {
        return Codegen.optional(this.telegram);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Notification(java.lang.String name) {
        this(name, NotificationArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Notification(java.lang.String name, NotificationArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Notification(java.lang.String name, NotificationArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("dokploy:index:Notification", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Notification(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("dokploy:index:Notification", name, null, makeResourceOptions(options, id), false);
    }

    private static NotificationArgs makeArgs(NotificationArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? NotificationArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/dimeskigj/pulumi-dokploy")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Notification get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Notification(name, id, options);
    }
}
