// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package net.dimeski.pulumi.dokploy;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;
import net.dimeski.pulumi.dokploy.enums.PortProtocol;
import net.dimeski.pulumi.dokploy.enums.PortPublishMode;


public final class PortArgs extends com.pulumi.resources.ResourceArgs {

    public static final PortArgs Empty = new PortArgs();

    /**
     * The Dokploy application ID.
     *
     */
    @Import(name="applicationId", required=true)
    private Output<String> applicationId;

    /**
     * @return The Dokploy application ID.
     *
     */
    public Output<String> applicationId() {
        return this.applicationId;
    }

    /**
     * The port protocol: tcp or udp.
     *
     */
    @Import(name="protocol")
    private @Nullable Output<PortProtocol> protocol;

    /**
     * @return The port protocol: tcp or udp.
     *
     */
    public Optional<Output<PortProtocol>> protocol() {
        return Optional.ofNullable(this.protocol);
    }

    /**
     * The port publish mode: ingress or host.
     *
     */
    @Import(name="publishMode")
    private @Nullable Output<PortPublishMode> publishMode;

    /**
     * @return The port publish mode: ingress or host.
     *
     */
    public Optional<Output<PortPublishMode>> publishMode() {
        return Optional.ofNullable(this.publishMode);
    }

    /**
     * The externally published port (1-65535).
     *
     */
    @Import(name="publishedPort", required=true)
    private Output<Integer> publishedPort;

    /**
     * @return The externally published port (1-65535).
     *
     */
    public Output<Integer> publishedPort() {
        return this.publishedPort;
    }

    /**
     * The application target port (1-65535).
     *
     */
    @Import(name="targetPort", required=true)
    private Output<Integer> targetPort;

    /**
     * @return The application target port (1-65535).
     *
     */
    public Output<Integer> targetPort() {
        return this.targetPort;
    }

    private PortArgs() {}

    private PortArgs(PortArgs $) {
        this.applicationId = $.applicationId;
        this.protocol = $.protocol;
        this.publishMode = $.publishMode;
        this.publishedPort = $.publishedPort;
        this.targetPort = $.targetPort;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PortArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PortArgs $;

        public Builder() {
            $ = new PortArgs();
        }

        public Builder(PortArgs defaults) {
            $ = new PortArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param applicationId The Dokploy application ID.
         *
         * @return builder
         *
         */
        public Builder applicationId(Output<String> applicationId) {
            $.applicationId = applicationId;
            return this;
        }

        /**
         * @param applicationId The Dokploy application ID.
         *
         * @return builder
         *
         */
        public Builder applicationId(String applicationId) {
            return applicationId(Output.of(applicationId));
        }

        /**
         * @param protocol The port protocol: tcp or udp.
         *
         * @return builder
         *
         */
        public Builder protocol(@Nullable Output<PortProtocol> protocol) {
            $.protocol = protocol;
            return this;
        }

        /**
         * @param protocol The port protocol: tcp or udp.
         *
         * @return builder
         *
         */
        public Builder protocol(PortProtocol protocol) {
            return protocol(Output.of(protocol));
        }

        /**
         * @param publishMode The port publish mode: ingress or host.
         *
         * @return builder
         *
         */
        public Builder publishMode(@Nullable Output<PortPublishMode> publishMode) {
            $.publishMode = publishMode;
            return this;
        }

        /**
         * @param publishMode The port publish mode: ingress or host.
         *
         * @return builder
         *
         */
        public Builder publishMode(PortPublishMode publishMode) {
            return publishMode(Output.of(publishMode));
        }

        /**
         * @param publishedPort The externally published port (1-65535).
         *
         * @return builder
         *
         */
        public Builder publishedPort(Output<Integer> publishedPort) {
            $.publishedPort = publishedPort;
            return this;
        }

        /**
         * @param publishedPort The externally published port (1-65535).
         *
         * @return builder
         *
         */
        public Builder publishedPort(Integer publishedPort) {
            return publishedPort(Output.of(publishedPort));
        }

        /**
         * @param targetPort The application target port (1-65535).
         *
         * @return builder
         *
         */
        public Builder targetPort(Output<Integer> targetPort) {
            $.targetPort = targetPort;
            return this;
        }

        /**
         * @param targetPort The application target port (1-65535).
         *
         * @return builder
         *
         */
        public Builder targetPort(Integer targetPort) {
            return targetPort(Output.of(targetPort));
        }

        public PortArgs build() {
            if ($.applicationId == null) {
                throw new MissingRequiredPropertyException("PortArgs", "applicationId");
            }
            $.protocol = Codegen.objectProp("protocol", PortProtocol.class).output().arg($.protocol).def(PortProtocol.Tcp).getNullable();
            $.publishMode = Codegen.objectProp("publishMode", PortPublishMode.class).output().arg($.publishMode).def(PortPublishMode.Ingress).getNullable();
            if ($.publishedPort == null) {
                throw new MissingRequiredPropertyException("PortArgs", "publishedPort");
            }
            if ($.targetPort == null) {
                throw new MissingRequiredPropertyException("PortArgs", "targetPort");
            }
            return $;
        }
    }

}
