// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package net.dimeski.pulumi.dokploy;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class ProjectTagArgs extends com.pulumi.resources.ResourceArgs {

    public static final ProjectTagArgs Empty = new ProjectTagArgs();

    /**
     * The Dokploy project ID.
     * 
     */
    @Import(name="projectId", required=true)
    private Output<String> projectId;

    /**
     * @return The Dokploy project ID.
     * 
     */
    public Output<String> projectId() {
        return this.projectId;
    }

    /**
     * The Dokploy tag ID.
     * 
     */
    @Import(name="tagId", required=true)
    private Output<String> tagId;

    /**
     * @return The Dokploy tag ID.
     * 
     */
    public Output<String> tagId() {
        return this.tagId;
    }

    private ProjectTagArgs() {}

    private ProjectTagArgs(ProjectTagArgs $) {
        this.projectId = $.projectId;
        this.tagId = $.tagId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProjectTagArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProjectTagArgs $;

        public Builder() {
            $ = new ProjectTagArgs();
        }

        public Builder(ProjectTagArgs defaults) {
            $ = new ProjectTagArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param projectId The Dokploy project ID.
         * 
         * @return builder
         * 
         */
        public Builder projectId(Output<String> projectId) {
            $.projectId = projectId;
            return this;
        }

        /**
         * @param projectId The Dokploy project ID.
         * 
         * @return builder
         * 
         */
        public Builder projectId(String projectId) {
            return projectId(Output.of(projectId));
        }

        /**
         * @param tagId The Dokploy tag ID.
         * 
         * @return builder
         * 
         */
        public Builder tagId(Output<String> tagId) {
            $.tagId = tagId;
            return this;
        }

        /**
         * @param tagId The Dokploy tag ID.
         * 
         * @return builder
         * 
         */
        public Builder tagId(String tagId) {
            return tagId(Output.of(tagId));
        }

        public ProjectTagArgs build() {
            if ($.projectId == null) {
                throw new MissingRequiredPropertyException("ProjectTagArgs", "projectId");
            }
            if ($.tagId == null) {
                throw new MissingRequiredPropertyException("ProjectTagArgs", "tagId");
            }
            return $;
        }
    }

}
