// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package net.dimeski.pulumi.dokploy;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;
import net.dimeski.pulumi.dokploy.RegistryArgs;
import net.dimeski.pulumi.dokploy.Utilities;

/**
 * A Dokploy container registry.
 * 
 */
@ResourceType(type="dokploy:index:Registry")
public class Registry extends com.pulumi.resources.CustomResource {
    /**
     * The optional image prefix.
     * 
     */
    @Export(name="imagePrefix", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> imagePrefix;

    /**
     * @return The optional image prefix.
     * 
     */
    public Output<Optional<String>> imagePrefix() {
        return Codegen.optional(this.imagePrefix);
    }
    /**
     * The registry name.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The registry name.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The registry password.
     * 
     */
    @Export(name="password", refs={String.class}, tree="[0]")
    private Output<String> password;

    /**
     * @return The registry password.
     * 
     */
    public Output<String> password() {
        return this.password;
    }
    /**
     * The stable Dokploy registry ID.
     * 
     */
    @Export(name="registryId", refs={String.class}, tree="[0]")
    private Output<String> registryId;

    /**
     * @return The stable Dokploy registry ID.
     * 
     */
    public Output<String> registryId() {
        return this.registryId;
    }
    /**
     * The optional server ID.
     * 
     */
    @Export(name="serverId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> serverId;

    /**
     * @return The optional server ID.
     * 
     */
    public Output<Optional<String>> serverId() {
        return Codegen.optional(this.serverId);
    }
    /**
     * The registry URL.
     * 
     */
    @Export(name="url", refs={String.class}, tree="[0]")
    private Output<String> url;

    /**
     * @return The registry URL.
     * 
     */
    public Output<String> url() {
        return this.url;
    }
    /**
     * The registry username.
     * 
     */
    @Export(name="username", refs={String.class}, tree="[0]")
    private Output<String> username;

    /**
     * @return The registry username.
     * 
     */
    public Output<String> username() {
        return this.username;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Registry(java.lang.String name) {
        this(name, RegistryArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Registry(java.lang.String name, RegistryArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Registry(java.lang.String name, RegistryArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("dokploy:index:Registry", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Registry(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("dokploy:index:Registry", name, null, makeResourceOptions(options, id), false);
    }

    private static RegistryArgs makeArgs(RegistryArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? RegistryArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .additionalSecretOutputs(List.of(
                "password"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Registry get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Registry(name, id, options);
    }
}
