// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package net.dimeski.pulumi.dokploy;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class RegistryArgs extends com.pulumi.resources.ResourceArgs {

    public static final RegistryArgs Empty = new RegistryArgs();

    /**
     * The optional image prefix.
     * 
     */
    @Import(name="imagePrefix")
    private @Nullable Output<String> imagePrefix;

    /**
     * @return The optional image prefix.
     * 
     */
    public Optional<Output<String>> imagePrefix() {
        return Optional.ofNullable(this.imagePrefix);
    }

    /**
     * The registry name.
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return The registry name.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     * The registry password.
     * 
     */
    @Import(name="password", required=true)
    private Output<String> password;

    /**
     * @return The registry password.
     * 
     */
    public Output<String> password() {
        return this.password;
    }

    /**
     * The optional server ID.
     * 
     */
    @Import(name="serverId")
    private @Nullable Output<String> serverId;

    /**
     * @return The optional server ID.
     * 
     */
    public Optional<Output<String>> serverId() {
        return Optional.ofNullable(this.serverId);
    }

    /**
     * The registry URL.
     * 
     */
    @Import(name="url", required=true)
    private Output<String> url;

    /**
     * @return The registry URL.
     * 
     */
    public Output<String> url() {
        return this.url;
    }

    /**
     * The registry username.
     * 
     */
    @Import(name="username", required=true)
    private Output<String> username;

    /**
     * @return The registry username.
     * 
     */
    public Output<String> username() {
        return this.username;
    }

    private RegistryArgs() {}

    private RegistryArgs(RegistryArgs $) {
        this.imagePrefix = $.imagePrefix;
        this.name = $.name;
        this.password = $.password;
        this.serverId = $.serverId;
        this.url = $.url;
        this.username = $.username;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(RegistryArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private RegistryArgs $;

        public Builder() {
            $ = new RegistryArgs();
        }

        public Builder(RegistryArgs defaults) {
            $ = new RegistryArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param imagePrefix The optional image prefix.
         * 
         * @return builder
         * 
         */
        public Builder imagePrefix(@Nullable Output<String> imagePrefix) {
            $.imagePrefix = imagePrefix;
            return this;
        }

        /**
         * @param imagePrefix The optional image prefix.
         * 
         * @return builder
         * 
         */
        public Builder imagePrefix(String imagePrefix) {
            return imagePrefix(Output.of(imagePrefix));
        }

        /**
         * @param name The registry name.
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The registry name.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param password The registry password.
         * 
         * @return builder
         * 
         */
        public Builder password(Output<String> password) {
            $.password = password;
            return this;
        }

        /**
         * @param password The registry password.
         * 
         * @return builder
         * 
         */
        public Builder password(String password) {
            return password(Output.of(password));
        }

        /**
         * @param serverId The optional server ID.
         * 
         * @return builder
         * 
         */
        public Builder serverId(@Nullable Output<String> serverId) {
            $.serverId = serverId;
            return this;
        }

        /**
         * @param serverId The optional server ID.
         * 
         * @return builder
         * 
         */
        public Builder serverId(String serverId) {
            return serverId(Output.of(serverId));
        }

        /**
         * @param url The registry URL.
         * 
         * @return builder
         * 
         */
        public Builder url(Output<String> url) {
            $.url = url;
            return this;
        }

        /**
         * @param url The registry URL.
         * 
         * @return builder
         * 
         */
        public Builder url(String url) {
            return url(Output.of(url));
        }

        /**
         * @param username The registry username.
         * 
         * @return builder
         * 
         */
        public Builder username(Output<String> username) {
            $.username = username;
            return this;
        }

        /**
         * @param username The registry username.
         * 
         * @return builder
         * 
         */
        public Builder username(String username) {
            return username(Output.of(username));
        }

        public RegistryArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("RegistryArgs", "name");
            }
            if ($.password == null) {
                throw new MissingRequiredPropertyException("RegistryArgs", "password");
            }
            if ($.url == null) {
                throw new MissingRequiredPropertyException("RegistryArgs", "url");
            }
            if ($.username == null) {
                throw new MissingRequiredPropertyException("RegistryArgs", "username");
            }
            return $;
        }
    }

}
