// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package net.dimeski.pulumi.dokploy;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;
import net.dimeski.pulumi.dokploy.ScheduleArgs;
import net.dimeski.pulumi.dokploy.Utilities;

/**
 * A Dokploy scheduled command.
 * 
 */
@ResourceType(type="dokploy:index:Schedule")
public class Schedule extends com.pulumi.resources.CustomResource {
    /**
     * Optional application name.
     * 
     */
    @Export(name="appName", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> appName;

    /**
     * @return Optional application name.
     * 
     */
    public Output<Optional<String>> appName() {
        return Codegen.optional(this.appName);
    }
    /**
     * Target application ID.
     * 
     */
    @Export(name="applicationId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> applicationId;

    /**
     * @return Target application ID.
     * 
     */
    public Output<Optional<String>> applicationId() {
        return Codegen.optional(this.applicationId);
    }
    /**
     * Command executed by the schedule.
     * 
     */
    @Export(name="command", refs={String.class}, tree="[0]")
    private Output<String> command;

    /**
     * @return Command executed by the schedule.
     * 
     */
    public Output<String> command() {
        return this.command;
    }
    /**
     * Target Compose ID.
     * 
     */
    @Export(name="composeId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> composeId;

    /**
     * @return Target Compose ID.
     * 
     */
    public Output<Optional<String>> composeId() {
        return Codegen.optional(this.composeId);
    }
    /**
     * Cron expression for the schedule.
     * 
     */
    @Export(name="cronExpression", refs={String.class}, tree="[0]")
    private Output<String> cronExpression;

    /**
     * @return Cron expression for the schedule.
     * 
     */
    public Output<String> cronExpression() {
        return this.cronExpression;
    }
    /**
     * Optional schedule description.
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    /**
     * @return Optional schedule description.
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * Whether the schedule is enabled; defaults to false.
     * 
     */
    @Export(name="enabled", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> enabled;

    /**
     * @return Whether the schedule is enabled; defaults to false.
     * 
     */
    public Output<Boolean> enabled() {
        return this.enabled;
    }
    /**
     * Schedule name.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return Schedule name.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * Dokploy organization ID.
     * 
     */
    @Export(name="organizationId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> organizationId;

    /**
     * @return Dokploy organization ID.
     * 
     */
    public Output<Optional<String>> organizationId() {
        return Codegen.optional(this.organizationId);
    }
    /**
     * Stable Dokploy schedule ID.
     * 
     */
    @Export(name="scheduleId", refs={String.class}, tree="[0]")
    private Output<String> scheduleId;

    /**
     * @return Stable Dokploy schedule ID.
     * 
     */
    public Output<String> scheduleId() {
        return this.scheduleId;
    }
    /**
     * Schedule target type: application, compose, server, or dokploy-server.
     * 
     */
    @Export(name="scheduleType", refs={String.class}, tree="[0]")
    private Output<String> scheduleType;

    /**
     * @return Schedule target type: application, compose, server, or dokploy-server.
     * 
     */
    public Output<String> scheduleType() {
        return this.scheduleType;
    }
    /**
     * Optional script executed by the schedule.
     * 
     */
    @Export(name="script", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> script;

    /**
     * @return Optional script executed by the schedule.
     * 
     */
    public Output<Optional<String>> script() {
        return Codegen.optional(this.script);
    }
    /**
     * Target server ID.
     * 
     */
    @Export(name="serverId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> serverId;

    /**
     * @return Target server ID.
     * 
     */
    public Output<Optional<String>> serverId() {
        return Codegen.optional(this.serverId);
    }
    /**
     * Optional Compose service name.
     * 
     */
    @Export(name="serviceName", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> serviceName;

    /**
     * @return Optional Compose service name.
     * 
     */
    public Output<Optional<String>> serviceName() {
        return Codegen.optional(this.serviceName);
    }
    /**
     * Shell used to execute the command (bash or sh).
     * 
     */
    @Export(name="shellType", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> shellType;

    /**
     * @return Shell used to execute the command (bash or sh).
     * 
     */
    public Output<Optional<String>> shellType() {
        return Codegen.optional(this.shellType);
    }
    /**
     * Timezone for the schedule.
     * 
     */
    @Export(name="timezone", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> timezone;

    /**
     * @return Timezone for the schedule.
     * 
     */
    public Output<Optional<String>> timezone() {
        return Codegen.optional(this.timezone);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Schedule(java.lang.String name) {
        this(name, ScheduleArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Schedule(java.lang.String name, ScheduleArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Schedule(java.lang.String name, ScheduleArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("dokploy:index:Schedule", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Schedule(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("dokploy:index:Schedule", name, null, makeResourceOptions(options, id), false);
    }

    private static ScheduleArgs makeArgs(ScheduleArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ScheduleArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/dimeskigj/pulumi-dokploy")
            .additionalSecretOutputs(List.of(
                "command",
                "script"
            ))
            .replaceOnChanges(List.of(
                "appName",
                "applicationId",
                "composeId",
                "scheduleType",
                "serverId",
                "serviceName"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Schedule get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Schedule(name, id, options);
    }
}
