// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package net.dimeski.pulumi.dokploy;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ScheduleArgs extends com.pulumi.resources.ResourceArgs {

    public static final ScheduleArgs Empty = new ScheduleArgs();

    /**
     * Optional application name.
     *
     */
    @Import(name="appName")
    private @Nullable Output<String> appName;

    /**
     * @return Optional application name.
     *
     */
    public Optional<Output<String>> appName() {
        return Optional.ofNullable(this.appName);
    }

    /**
     * Target application ID.
     *
     */
    @Import(name="applicationId")
    private @Nullable Output<String> applicationId;

    /**
     * @return Target application ID.
     *
     */
    public Optional<Output<String>> applicationId() {
        return Optional.ofNullable(this.applicationId);
    }

    /**
     * Command executed by the schedule.
     *
     */
    @Import(name="command", required=true)
    private Output<String> command;

    /**
     * @return Command executed by the schedule.
     *
     */
    public Output<String> command() {
        return this.command;
    }

    /**
     * Target Compose ID.
     *
     */
    @Import(name="composeId")
    private @Nullable Output<String> composeId;

    /**
     * @return Target Compose ID.
     *
     */
    public Optional<Output<String>> composeId() {
        return Optional.ofNullable(this.composeId);
    }

    /**
     * Cron expression for the schedule.
     *
     */
    @Import(name="cronExpression", required=true)
    private Output<String> cronExpression;

    /**
     * @return Cron expression for the schedule.
     *
     */
    public Output<String> cronExpression() {
        return this.cronExpression;
    }

    /**
     * Optional schedule description.
     *
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return Optional schedule description.
     *
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * Whether the schedule is enabled; defaults to false.
     *
     */
    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    /**
     * @return Whether the schedule is enabled; defaults to false.
     *
     */
    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    /**
     * Schedule name.
     *
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return Schedule name.
     *
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     * Dokploy organization ID.
     *
     */
    @Import(name="organizationId")
    private @Nullable Output<String> organizationId;

    /**
     * @return Dokploy organization ID.
     *
     */
    public Optional<Output<String>> organizationId() {
        return Optional.ofNullable(this.organizationId);
    }

    /**
     * Schedule target type: application, compose, server, or dokploy-server.
     *
     */
    @Import(name="scheduleType", required=true)
    private Output<String> scheduleType;

    /**
     * @return Schedule target type: application, compose, server, or dokploy-server.
     *
     */
    public Output<String> scheduleType() {
        return this.scheduleType;
    }

    /**
     * Optional script executed by the schedule.
     *
     */
    @Import(name="script")
    private @Nullable Output<String> script;

    /**
     * @return Optional script executed by the schedule.
     *
     */
    public Optional<Output<String>> script() {
        return Optional.ofNullable(this.script);
    }

    /**
     * Target server ID.
     *
     */
    @Import(name="serverId")
    private @Nullable Output<String> serverId;

    /**
     * @return Target server ID.
     *
     */
    public Optional<Output<String>> serverId() {
        return Optional.ofNullable(this.serverId);
    }

    /**
     * Optional Compose service name.
     *
     */
    @Import(name="serviceName")
    private @Nullable Output<String> serviceName;

    /**
     * @return Optional Compose service name.
     *
     */
    public Optional<Output<String>> serviceName() {
        return Optional.ofNullable(this.serviceName);
    }

    /**
     * Shell used to execute the command (bash or sh).
     *
     */
    @Import(name="shellType")
    private @Nullable Output<String> shellType;

    /**
     * @return Shell used to execute the command (bash or sh).
     *
     */
    public Optional<Output<String>> shellType() {
        return Optional.ofNullable(this.shellType);
    }

    /**
     * Timezone for the schedule.
     *
     */
    @Import(name="timezone")
    private @Nullable Output<String> timezone;

    /**
     * @return Timezone for the schedule.
     *
     */
    public Optional<Output<String>> timezone() {
        return Optional.ofNullable(this.timezone);
    }

    private ScheduleArgs() {}

    private ScheduleArgs(ScheduleArgs $) {
        this.appName = $.appName;
        this.applicationId = $.applicationId;
        this.command = $.command;
        this.composeId = $.composeId;
        this.cronExpression = $.cronExpression;
        this.description = $.description;
        this.enabled = $.enabled;
        this.name = $.name;
        this.organizationId = $.organizationId;
        this.scheduleType = $.scheduleType;
        this.script = $.script;
        this.serverId = $.serverId;
        this.serviceName = $.serviceName;
        this.shellType = $.shellType;
        this.timezone = $.timezone;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ScheduleArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ScheduleArgs $;

        public Builder() {
            $ = new ScheduleArgs();
        }

        public Builder(ScheduleArgs defaults) {
            $ = new ScheduleArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param appName Optional application name.
         *
         * @return builder
         *
         */
        public Builder appName(@Nullable Output<String> appName) {
            $.appName = appName;
            return this;
        }

        /**
         * @param appName Optional application name.
         *
         * @return builder
         *
         */
        public Builder appName(String appName) {
            return appName(Output.of(appName));
        }

        /**
         * @param applicationId Target application ID.
         *
         * @return builder
         *
         */
        public Builder applicationId(@Nullable Output<String> applicationId) {
            $.applicationId = applicationId;
            return this;
        }

        /**
         * @param applicationId Target application ID.
         *
         * @return builder
         *
         */
        public Builder applicationId(String applicationId) {
            return applicationId(Output.of(applicationId));
        }

        /**
         * @param command Command executed by the schedule.
         *
         * @return builder
         *
         */
        public Builder command(Output<String> command) {
            $.command = command;
            return this;
        }

        /**
         * @param command Command executed by the schedule.
         *
         * @return builder
         *
         */
        public Builder command(String command) {
            return command(Output.of(command));
        }

        /**
         * @param composeId Target Compose ID.
         *
         * @return builder
         *
         */
        public Builder composeId(@Nullable Output<String> composeId) {
            $.composeId = composeId;
            return this;
        }

        /**
         * @param composeId Target Compose ID.
         *
         * @return builder
         *
         */
        public Builder composeId(String composeId) {
            return composeId(Output.of(composeId));
        }

        /**
         * @param cronExpression Cron expression for the schedule.
         *
         * @return builder
         *
         */
        public Builder cronExpression(Output<String> cronExpression) {
            $.cronExpression = cronExpression;
            return this;
        }

        /**
         * @param cronExpression Cron expression for the schedule.
         *
         * @return builder
         *
         */
        public Builder cronExpression(String cronExpression) {
            return cronExpression(Output.of(cronExpression));
        }

        /**
         * @param description Optional schedule description.
         *
         * @return builder
         *
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description Optional schedule description.
         *
         * @return builder
         *
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param enabled Whether the schedule is enabled; defaults to false.
         *
         * @return builder
         *
         */
        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        /**
         * @param enabled Whether the schedule is enabled; defaults to false.
         *
         * @return builder
         *
         */
        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        /**
         * @param name Schedule name.
         *
         * @return builder
         *
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Schedule name.
         *
         * @return builder
         *
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param organizationId Dokploy organization ID.
         *
         * @return builder
         *
         */
        public Builder organizationId(@Nullable Output<String> organizationId) {
            $.organizationId = organizationId;
            return this;
        }

        /**
         * @param organizationId Dokploy organization ID.
         *
         * @return builder
         *
         */
        public Builder organizationId(String organizationId) {
            return organizationId(Output.of(organizationId));
        }

        /**
         * @param scheduleType Schedule target type: application, compose, server, or dokploy-server.
         *
         * @return builder
         *
         */
        public Builder scheduleType(Output<String> scheduleType) {
            $.scheduleType = scheduleType;
            return this;
        }

        /**
         * @param scheduleType Schedule target type: application, compose, server, or dokploy-server.
         *
         * @return builder
         *
         */
        public Builder scheduleType(String scheduleType) {
            return scheduleType(Output.of(scheduleType));
        }

        /**
         * @param script Optional script executed by the schedule.
         *
         * @return builder
         *
         */
        public Builder script(@Nullable Output<String> script) {
            $.script = script;
            return this;
        }

        /**
         * @param script Optional script executed by the schedule.
         *
         * @return builder
         *
         */
        public Builder script(String script) {
            return script(Output.of(script));
        }

        /**
         * @param serverId Target server ID.
         *
         * @return builder
         *
         */
        public Builder serverId(@Nullable Output<String> serverId) {
            $.serverId = serverId;
            return this;
        }

        /**
         * @param serverId Target server ID.
         *
         * @return builder
         *
         */
        public Builder serverId(String serverId) {
            return serverId(Output.of(serverId));
        }

        /**
         * @param serviceName Optional Compose service name.
         *
         * @return builder
         *
         */
        public Builder serviceName(@Nullable Output<String> serviceName) {
            $.serviceName = serviceName;
            return this;
        }

        /**
         * @param serviceName Optional Compose service name.
         *
         * @return builder
         *
         */
        public Builder serviceName(String serviceName) {
            return serviceName(Output.of(serviceName));
        }

        /**
         * @param shellType Shell used to execute the command (bash or sh).
         *
         * @return builder
         *
         */
        public Builder shellType(@Nullable Output<String> shellType) {
            $.shellType = shellType;
            return this;
        }

        /**
         * @param shellType Shell used to execute the command (bash or sh).
         *
         * @return builder
         *
         */
        public Builder shellType(String shellType) {
            return shellType(Output.of(shellType));
        }

        /**
         * @param timezone Timezone for the schedule.
         *
         * @return builder
         *
         */
        public Builder timezone(@Nullable Output<String> timezone) {
            $.timezone = timezone;
            return this;
        }

        /**
         * @param timezone Timezone for the schedule.
         *
         * @return builder
         *
         */
        public Builder timezone(String timezone) {
            return timezone(Output.of(timezone));
        }

        public ScheduleArgs build() {
            if ($.command == null) {
                throw new MissingRequiredPropertyException("ScheduleArgs", "command");
            }
            if ($.cronExpression == null) {
                throw new MissingRequiredPropertyException("ScheduleArgs", "cronExpression");
            }
            $.enabled = Codegen.booleanProp("enabled").output().arg($.enabled).def(false).getNullable();
            if ($.name == null) {
                throw new MissingRequiredPropertyException("ScheduleArgs", "name");
            }
            if ($.scheduleType == null) {
                throw new MissingRequiredPropertyException("ScheduleArgs", "scheduleType");
            }
            return $;
        }
    }

}
