// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package net.dimeski.pulumi.dokploy;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;
import net.dimeski.pulumi.dokploy.ServerArgs;
import net.dimeski.pulumi.dokploy.Utilities;

/**
 * A remote server record in Dokploy; does not bootstrap or destroy the remote machine.
 *
 */
@ResourceType(type="dokploy:index:Server")
public class Server extends com.pulumi.resources.CustomResource {
    /**
     * Optional description; omission clears the description.
     *
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    /**
     * @return Optional description; omission clears the description.
     *
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * Enable Dokploy&#39;s recurring Docker cleanup schedule; defaults to false.
     *
     */
    @Export(name="enableDockerCleanup", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> enableDockerCleanup;

    /**
     * @return Enable Dokploy&#39;s recurring Docker cleanup schedule; defaults to false.
     *
     */
    public Output<Boolean> enableDockerCleanup() {
        return this.enableDockerCleanup;
    }
    /**
     * Hostname or IP address of the remote server.
     *
     */
    @Export(name="ipAddress", refs={String.class}, tree="[0]")
    private Output<String> ipAddress;

    /**
     * @return Hostname or IP address of the remote server.
     *
     */
    public Output<String> ipAddress() {
        return this.ipAddress;
    }
    /**
     * Server name.
     *
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return Server name.
     *
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * Owning Dokploy organization ID.
     *
     */
    @Export(name="organizationId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> organizationId;

    /**
     * @return Owning Dokploy organization ID.
     *
     */
    public Output<Optional<String>> organizationId() {
        return Codegen.optional(this.organizationId);
    }
    /**
     * SSH port (1–65535); defaults to 22.
     *
     */
    @Export(name="port", refs={Integer.class}, tree="[0]")
    private Output<Integer> port;

    /**
     * @return SSH port (1–65535); defaults to 22.
     *
     */
    public Output<Integer> port() {
        return this.port;
    }
    /**
     * Stable Dokploy server ID.
     *
     */
    @Export(name="serverId", refs={String.class}, tree="[0]")
    private Output<String> serverId;

    /**
     * @return Stable Dokploy server ID.
     *
     */
    public Output<String> serverId() {
        return this.serverId;
    }
    /**
     * Server role: deploy or build; defaults to deploy.
     *
     */
    @Export(name="serverType", refs={String.class}, tree="[0]")
    private Output<String> serverType;

    /**
     * @return Server role: deploy or build; defaults to deploy.
     *
     */
    public Output<String> serverType() {
        return this.serverType;
    }
    /**
     * Managed SSH key ID; omission clears the key.
     *
     */
    @Export(name="sshKeyId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> sshKeyId;

    /**
     * @return Managed SSH key ID; omission clears the key.
     *
     */
    public Output<Optional<String>> sshKeyId() {
        return Codegen.optional(this.sshKeyId);
    }
    /**
     * Dokploy server status (not a readiness guarantee).
     *
     */
    @Export(name="status", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> status;

    /**
     * @return Dokploy server status (not a readiness guarantee).
     *
     */
    public Output<Optional<String>> status() {
        return Codegen.optional(this.status);
    }
    /**
     * SSH username; defaults to root.
     *
     */
    @Export(name="username", refs={String.class}, tree="[0]")
    private Output<String> username;

    /**
     * @return SSH username; defaults to root.
     *
     */
    public Output<String> username() {
        return this.username;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Server(java.lang.String name) {
        this(name, ServerArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Server(java.lang.String name, ServerArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Server(java.lang.String name, ServerArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("dokploy:index:Server", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Server(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("dokploy:index:Server", name, null, makeResourceOptions(options, id), false);
    }

    private static ServerArgs makeArgs(ServerArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ServerArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/dimeskigj/pulumi-dokploy")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Server get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Server(name, id, options);
    }
}
