// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package net.dimeski.pulumi.dokploy;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ServerArgs extends com.pulumi.resources.ResourceArgs {

    public static final ServerArgs Empty = new ServerArgs();

    /**
     * Optional description; omission clears the description.
     *
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return Optional description; omission clears the description.
     *
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * Enable Dokploy&#39;s recurring Docker cleanup schedule; defaults to false.
     *
     */
    @Import(name="enableDockerCleanup")
    private @Nullable Output<Boolean> enableDockerCleanup;

    /**
     * @return Enable Dokploy&#39;s recurring Docker cleanup schedule; defaults to false.
     *
     */
    public Optional<Output<Boolean>> enableDockerCleanup() {
        return Optional.ofNullable(this.enableDockerCleanup);
    }

    /**
     * Hostname or IP address of the remote server.
     *
     */
    @Import(name="ipAddress", required=true)
    private Output<String> ipAddress;

    /**
     * @return Hostname or IP address of the remote server.
     *
     */
    public Output<String> ipAddress() {
        return this.ipAddress;
    }

    /**
     * Server name.
     *
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return Server name.
     *
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     * SSH port (1–65535); defaults to 22.
     *
     */
    @Import(name="port")
    private @Nullable Output<Integer> port;

    /**
     * @return SSH port (1–65535); defaults to 22.
     *
     */
    public Optional<Output<Integer>> port() {
        return Optional.ofNullable(this.port);
    }

    /**
     * Server role: deploy or build; defaults to deploy.
     *
     */
    @Import(name="serverType")
    private @Nullable Output<String> serverType;

    /**
     * @return Server role: deploy or build; defaults to deploy.
     *
     */
    public Optional<Output<String>> serverType() {
        return Optional.ofNullable(this.serverType);
    }

    /**
     * Managed SSH key ID; omission clears the key.
     *
     */
    @Import(name="sshKeyId")
    private @Nullable Output<String> sshKeyId;

    /**
     * @return Managed SSH key ID; omission clears the key.
     *
     */
    public Optional<Output<String>> sshKeyId() {
        return Optional.ofNullable(this.sshKeyId);
    }

    /**
     * SSH username; defaults to root.
     *
     */
    @Import(name="username")
    private @Nullable Output<String> username;

    /**
     * @return SSH username; defaults to root.
     *
     */
    public Optional<Output<String>> username() {
        return Optional.ofNullable(this.username);
    }

    private ServerArgs() {}

    private ServerArgs(ServerArgs $) {
        this.description = $.description;
        this.enableDockerCleanup = $.enableDockerCleanup;
        this.ipAddress = $.ipAddress;
        this.name = $.name;
        this.port = $.port;
        this.serverType = $.serverType;
        this.sshKeyId = $.sshKeyId;
        this.username = $.username;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ServerArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ServerArgs $;

        public Builder() {
            $ = new ServerArgs();
        }

        public Builder(ServerArgs defaults) {
            $ = new ServerArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param description Optional description; omission clears the description.
         *
         * @return builder
         *
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description Optional description; omission clears the description.
         *
         * @return builder
         *
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param enableDockerCleanup Enable Dokploy&#39;s recurring Docker cleanup schedule; defaults to false.
         *
         * @return builder
         *
         */
        public Builder enableDockerCleanup(@Nullable Output<Boolean> enableDockerCleanup) {
            $.enableDockerCleanup = enableDockerCleanup;
            return this;
        }

        /**
         * @param enableDockerCleanup Enable Dokploy&#39;s recurring Docker cleanup schedule; defaults to false.
         *
         * @return builder
         *
         */
        public Builder enableDockerCleanup(Boolean enableDockerCleanup) {
            return enableDockerCleanup(Output.of(enableDockerCleanup));
        }

        /**
         * @param ipAddress Hostname or IP address of the remote server.
         *
         * @return builder
         *
         */
        public Builder ipAddress(Output<String> ipAddress) {
            $.ipAddress = ipAddress;
            return this;
        }

        /**
         * @param ipAddress Hostname or IP address of the remote server.
         *
         * @return builder
         *
         */
        public Builder ipAddress(String ipAddress) {
            return ipAddress(Output.of(ipAddress));
        }

        /**
         * @param name Server name.
         *
         * @return builder
         *
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Server name.
         *
         * @return builder
         *
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param port SSH port (1–65535); defaults to 22.
         *
         * @return builder
         *
         */
        public Builder port(@Nullable Output<Integer> port) {
            $.port = port;
            return this;
        }

        /**
         * @param port SSH port (1–65535); defaults to 22.
         *
         * @return builder
         *
         */
        public Builder port(Integer port) {
            return port(Output.of(port));
        }

        /**
         * @param serverType Server role: deploy or build; defaults to deploy.
         *
         * @return builder
         *
         */
        public Builder serverType(@Nullable Output<String> serverType) {
            $.serverType = serverType;
            return this;
        }

        /**
         * @param serverType Server role: deploy or build; defaults to deploy.
         *
         * @return builder
         *
         */
        public Builder serverType(String serverType) {
            return serverType(Output.of(serverType));
        }

        /**
         * @param sshKeyId Managed SSH key ID; omission clears the key.
         *
         * @return builder
         *
         */
        public Builder sshKeyId(@Nullable Output<String> sshKeyId) {
            $.sshKeyId = sshKeyId;
            return this;
        }

        /**
         * @param sshKeyId Managed SSH key ID; omission clears the key.
         *
         * @return builder
         *
         */
        public Builder sshKeyId(String sshKeyId) {
            return sshKeyId(Output.of(sshKeyId));
        }

        /**
         * @param username SSH username; defaults to root.
         *
         * @return builder
         *
         */
        public Builder username(@Nullable Output<String> username) {
            $.username = username;
            return this;
        }

        /**
         * @param username SSH username; defaults to root.
         *
         * @return builder
         *
         */
        public Builder username(String username) {
            return username(Output.of(username));
        }

        public ServerArgs build() {
            $.enableDockerCleanup = Codegen.booleanProp("enableDockerCleanup").output().arg($.enableDockerCleanup).def(false).getNullable();
            if ($.ipAddress == null) {
                throw new MissingRequiredPropertyException("ServerArgs", "ipAddress");
            }
            if ($.name == null) {
                throw new MissingRequiredPropertyException("ServerArgs", "name");
            }
            $.port = Codegen.integerProp("port").output().arg($.port).def(22).getNullable();
            $.serverType = Codegen.stringProp("serverType").output().arg($.serverType).def("deploy").getNullable();
            $.username = Codegen.stringProp("username").output().arg($.username).def("root").getNullable();
            return $;
        }
    }

}
