// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package net.dimeski.pulumi.dokploy;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;
import net.dimeski.pulumi.dokploy.TagArgs;
import net.dimeski.pulumi.dokploy.Utilities;

/**
 * A reusable Dokploy project tag.
 * 
 */
@ResourceType(type="dokploy:index:Tag")
public class Tag extends com.pulumi.resources.CustomResource {
    /**
     * The optional opaque tag color.
     * 
     */
    @Export(name="color", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> color;

    /**
     * @return The optional opaque tag color.
     * 
     */
    public Output<Optional<String>> color() {
        return Codegen.optional(this.color);
    }
    /**
     * The tag name.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The tag name.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The stable Dokploy tag ID.
     * 
     */
    @Export(name="tagId", refs={String.class}, tree="[0]")
    private Output<String> tagId;

    /**
     * @return The stable Dokploy tag ID.
     * 
     */
    public Output<String> tagId() {
        return this.tagId;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Tag(java.lang.String name) {
        this(name, TagArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Tag(java.lang.String name, TagArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Tag(java.lang.String name, TagArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("dokploy:index:Tag", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Tag(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("dokploy:index:Tag", name, null, makeResourceOptions(options, id), false);
    }

    private static TagArgs makeArgs(TagArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? TagArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Tag get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Tag(name, id, options);
    }
}
