// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package net.dimeski.pulumi.dokploy;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class VolumeBackupArgs extends com.pulumi.resources.ResourceArgs {

    public static final VolumeBackupArgs Empty = new VolumeBackupArgs();

    /**
     * The optional target application ID.
     * 
     */
    @Import(name="applicationId")
    private @Nullable Output<String> applicationId;

    /**
     * @return The optional target application ID.
     * 
     */
    public Optional<Output<String>> applicationId() {
        return Optional.ofNullable(this.applicationId);
    }

    /**
     * The optional target Compose ID.
     * 
     */
    @Import(name="composeId")
    private @Nullable Output<String> composeId;

    /**
     * @return The optional target Compose ID.
     * 
     */
    public Optional<Output<String>> composeId() {
        return Optional.ofNullable(this.composeId);
    }

    /**
     * The backup cron schedule.
     * 
     */
    @Import(name="cronExpression", required=true)
    private Output<String> cronExpression;

    /**
     * @return The backup cron schedule.
     * 
     */
    public Output<String> cronExpression() {
        return this.cronExpression;
    }

    /**
     * The destination ID backups are stored to.
     * 
     */
    @Import(name="destinationId", required=true)
    private Output<String> destinationId;

    /**
     * @return The destination ID backups are stored to.
     * 
     */
    public Output<String> destinationId() {
        return this.destinationId;
    }

    /**
     * Whether the backup schedule is enabled.
     * 
     */
    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    /**
     * @return Whether the backup schedule is enabled.
     * 
     */
    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    /**
     * The optional number of most recent backups to retain.
     * 
     */
    @Import(name="keepLatestCount")
    private @Nullable Output<Integer> keepLatestCount;

    /**
     * @return The optional number of most recent backups to retain.
     * 
     */
    public Optional<Output<Integer>> keepLatestCount() {
        return Optional.ofNullable(this.keepLatestCount);
    }

    /**
     * The volume backup resource name.
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return The volume backup resource name.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     * The backup file prefix.
     * 
     */
    @Import(name="prefix", required=true)
    private Output<String> prefix;

    /**
     * @return The backup file prefix.
     * 
     */
    public Output<String> prefix() {
        return this.prefix;
    }

    /**
     * The Compose service name that owns the volume.
     * 
     */
    @Import(name="serviceName")
    private @Nullable Output<String> serviceName;

    /**
     * @return The Compose service name that owns the volume.
     * 
     */
    public Optional<Output<String>> serviceName() {
        return Optional.ofNullable(this.serviceName);
    }

    /**
     * Whether to turn the backup off without deleting it.
     * 
     */
    @Import(name="turnOff")
    private @Nullable Output<Boolean> turnOff;

    /**
     * @return Whether to turn the backup off without deleting it.
     * 
     */
    public Optional<Output<Boolean>> turnOff() {
        return Optional.ofNullable(this.turnOff);
    }

    /**
     * The Docker volume name to back up.
     * 
     */
    @Import(name="volumeName", required=true)
    private Output<String> volumeName;

    /**
     * @return The Docker volume name to back up.
     * 
     */
    public Output<String> volumeName() {
        return this.volumeName;
    }

    private VolumeBackupArgs() {}

    private VolumeBackupArgs(VolumeBackupArgs $) {
        this.applicationId = $.applicationId;
        this.composeId = $.composeId;
        this.cronExpression = $.cronExpression;
        this.destinationId = $.destinationId;
        this.enabled = $.enabled;
        this.keepLatestCount = $.keepLatestCount;
        this.name = $.name;
        this.prefix = $.prefix;
        this.serviceName = $.serviceName;
        this.turnOff = $.turnOff;
        this.volumeName = $.volumeName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(VolumeBackupArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private VolumeBackupArgs $;

        public Builder() {
            $ = new VolumeBackupArgs();
        }

        public Builder(VolumeBackupArgs defaults) {
            $ = new VolumeBackupArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param applicationId The optional target application ID.
         * 
         * @return builder
         * 
         */
        public Builder applicationId(@Nullable Output<String> applicationId) {
            $.applicationId = applicationId;
            return this;
        }

        /**
         * @param applicationId The optional target application ID.
         * 
         * @return builder
         * 
         */
        public Builder applicationId(String applicationId) {
            return applicationId(Output.of(applicationId));
        }

        /**
         * @param composeId The optional target Compose ID.
         * 
         * @return builder
         * 
         */
        public Builder composeId(@Nullable Output<String> composeId) {
            $.composeId = composeId;
            return this;
        }

        /**
         * @param composeId The optional target Compose ID.
         * 
         * @return builder
         * 
         */
        public Builder composeId(String composeId) {
            return composeId(Output.of(composeId));
        }

        /**
         * @param cronExpression The backup cron schedule.
         * 
         * @return builder
         * 
         */
        public Builder cronExpression(Output<String> cronExpression) {
            $.cronExpression = cronExpression;
            return this;
        }

        /**
         * @param cronExpression The backup cron schedule.
         * 
         * @return builder
         * 
         */
        public Builder cronExpression(String cronExpression) {
            return cronExpression(Output.of(cronExpression));
        }

        /**
         * @param destinationId The destination ID backups are stored to.
         * 
         * @return builder
         * 
         */
        public Builder destinationId(Output<String> destinationId) {
            $.destinationId = destinationId;
            return this;
        }

        /**
         * @param destinationId The destination ID backups are stored to.
         * 
         * @return builder
         * 
         */
        public Builder destinationId(String destinationId) {
            return destinationId(Output.of(destinationId));
        }

        /**
         * @param enabled Whether the backup schedule is enabled.
         * 
         * @return builder
         * 
         */
        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        /**
         * @param enabled Whether the backup schedule is enabled.
         * 
         * @return builder
         * 
         */
        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        /**
         * @param keepLatestCount The optional number of most recent backups to retain.
         * 
         * @return builder
         * 
         */
        public Builder keepLatestCount(@Nullable Output<Integer> keepLatestCount) {
            $.keepLatestCount = keepLatestCount;
            return this;
        }

        /**
         * @param keepLatestCount The optional number of most recent backups to retain.
         * 
         * @return builder
         * 
         */
        public Builder keepLatestCount(Integer keepLatestCount) {
            return keepLatestCount(Output.of(keepLatestCount));
        }

        /**
         * @param name The volume backup resource name.
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The volume backup resource name.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param prefix The backup file prefix.
         * 
         * @return builder
         * 
         */
        public Builder prefix(Output<String> prefix) {
            $.prefix = prefix;
            return this;
        }

        /**
         * @param prefix The backup file prefix.
         * 
         * @return builder
         * 
         */
        public Builder prefix(String prefix) {
            return prefix(Output.of(prefix));
        }

        /**
         * @param serviceName The Compose service name that owns the volume.
         * 
         * @return builder
         * 
         */
        public Builder serviceName(@Nullable Output<String> serviceName) {
            $.serviceName = serviceName;
            return this;
        }

        /**
         * @param serviceName The Compose service name that owns the volume.
         * 
         * @return builder
         * 
         */
        public Builder serviceName(String serviceName) {
            return serviceName(Output.of(serviceName));
        }

        /**
         * @param turnOff Whether to turn the backup off without deleting it.
         * 
         * @return builder
         * 
         */
        public Builder turnOff(@Nullable Output<Boolean> turnOff) {
            $.turnOff = turnOff;
            return this;
        }

        /**
         * @param turnOff Whether to turn the backup off without deleting it.
         * 
         * @return builder
         * 
         */
        public Builder turnOff(Boolean turnOff) {
            return turnOff(Output.of(turnOff));
        }

        /**
         * @param volumeName The Docker volume name to back up.
         * 
         * @return builder
         * 
         */
        public Builder volumeName(Output<String> volumeName) {
            $.volumeName = volumeName;
            return this;
        }

        /**
         * @param volumeName The Docker volume name to back up.
         * 
         * @return builder
         * 
         */
        public Builder volumeName(String volumeName) {
            return volumeName(Output.of(volumeName));
        }

        public VolumeBackupArgs build() {
            if ($.cronExpression == null) {
                throw new MissingRequiredPropertyException("VolumeBackupArgs", "cronExpression");
            }
            if ($.destinationId == null) {
                throw new MissingRequiredPropertyException("VolumeBackupArgs", "destinationId");
            }
            $.enabled = Codegen.booleanProp("enabled").output().arg($.enabled).def(true).getNullable();
            if ($.name == null) {
                throw new MissingRequiredPropertyException("VolumeBackupArgs", "name");
            }
            if ($.prefix == null) {
                throw new MissingRequiredPropertyException("VolumeBackupArgs", "prefix");
            }
            if ($.volumeName == null) {
                throw new MissingRequiredPropertyException("VolumeBackupArgs", "volumeName");
            }
            return $;
        }
    }

}
