// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package net.dimeski.pulumi.dokploy.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetMySQLArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetMySQLArgs Empty = new GetMySQLArgs();

    /**
     * The ID of the existing Dokploy MySQL database to read.
     *
     */
    @Import(name="mysqlId", required=true)
    private Output<String> mysqlId;

    /**
     * @return The ID of the existing Dokploy MySQL database to read.
     *
     */
    public Output<String> mysqlId() {
        return this.mysqlId;
    }

    private GetMySQLArgs() {}

    private GetMySQLArgs(GetMySQLArgs $) {
        this.mysqlId = $.mysqlId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetMySQLArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetMySQLArgs $;

        public Builder() {
            $ = new GetMySQLArgs();
        }

        public Builder(GetMySQLArgs defaults) {
            $ = new GetMySQLArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param mysqlId The ID of the existing Dokploy MySQL database to read.
         *
         * @return builder
         *
         */
        public Builder mysqlId(Output<String> mysqlId) {
            $.mysqlId = mysqlId;
            return this;
        }

        /**
         * @param mysqlId The ID of the existing Dokploy MySQL database to read.
         *
         * @return builder
         *
         */
        public Builder mysqlId(String mysqlId) {
            return mysqlId(Output.of(mysqlId));
        }

        public GetMySQLArgs build() {
            if ($.mysqlId == null) {
                throw new MissingRequiredPropertyException("GetMySQLArgs", "mysqlId");
            }
            return $;
        }
    }

}
