// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package net.dimeski.pulumi.dokploy.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetRedisPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetRedisPlainArgs Empty = new GetRedisPlainArgs();

    /**
     * The ID of the existing Dokploy Redis database to read.
     *
     */
    @Import(name="redisId", required=true)
    private String redisId;

    /**
     * @return The ID of the existing Dokploy Redis database to read.
     *
     */
    public String redisId() {
        return this.redisId;
    }

    private GetRedisPlainArgs() {}

    private GetRedisPlainArgs(GetRedisPlainArgs $) {
        this.redisId = $.redisId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetRedisPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetRedisPlainArgs $;

        public Builder() {
            $ = new GetRedisPlainArgs();
        }

        public Builder(GetRedisPlainArgs defaults) {
            $ = new GetRedisPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param redisId The ID of the existing Dokploy Redis database to read.
         *
         * @return builder
         *
         */
        public Builder redisId(String redisId) {
            $.redisId = redisId;
            return this;
        }

        public GetRedisPlainArgs build() {
            if ($.redisId == null) {
                throw new MissingRequiredPropertyException("GetRedisPlainArgs", "redisId");
            }
            return $;
        }
    }

}
