// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package net.dimeski.pulumi.dokploy.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetRegistryArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetRegistryArgs Empty = new GetRegistryArgs();

    /**
     * The ID of the existing Dokploy registry to read.
     *
     */
    @Import(name="registryId", required=true)
    private Output<String> registryId;

    /**
     * @return The ID of the existing Dokploy registry to read.
     *
     */
    public Output<String> registryId() {
        return this.registryId;
    }

    private GetRegistryArgs() {}

    private GetRegistryArgs(GetRegistryArgs $) {
        this.registryId = $.registryId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetRegistryArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetRegistryArgs $;

        public Builder() {
            $ = new GetRegistryArgs();
        }

        public Builder(GetRegistryArgs defaults) {
            $ = new GetRegistryArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param registryId The ID of the existing Dokploy registry to read.
         *
         * @return builder
         *
         */
        public Builder registryId(Output<String> registryId) {
            $.registryId = registryId;
            return this;
        }

        /**
         * @param registryId The ID of the existing Dokploy registry to read.
         *
         * @return builder
         *
         */
        public Builder registryId(String registryId) {
            return registryId(Output.of(registryId));
        }

        public GetRegistryArgs build() {
            if ($.registryId == null) {
                throw new MissingRequiredPropertyException("GetRegistryArgs", "registryId");
            }
            return $;
        }
    }

}
