// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package net.dimeski.pulumi.dokploy.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetSSHKeyPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetSSHKeyPlainArgs Empty = new GetSSHKeyPlainArgs();

    /**
     * The ID of the existing Dokploy SSH key to read.
     *
     */
    @Import(name="sshKeyId", required=true)
    private String sshKeyId;

    /**
     * @return The ID of the existing Dokploy SSH key to read.
     *
     */
    public String sshKeyId() {
        return this.sshKeyId;
    }

    private GetSSHKeyPlainArgs() {}

    private GetSSHKeyPlainArgs(GetSSHKeyPlainArgs $) {
        this.sshKeyId = $.sshKeyId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetSSHKeyPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetSSHKeyPlainArgs $;

        public Builder() {
            $ = new GetSSHKeyPlainArgs();
        }

        public Builder(GetSSHKeyPlainArgs defaults) {
            $ = new GetSSHKeyPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param sshKeyId The ID of the existing Dokploy SSH key to read.
         *
         * @return builder
         *
         */
        public Builder sshKeyId(String sshKeyId) {
            $.sshKeyId = sshKeyId;
            return this;
        }

        public GetSSHKeyPlainArgs build() {
            if ($.sshKeyId == null) {
                throw new MissingRequiredPropertyException("GetSSHKeyPlainArgs", "sshKeyId");
            }
            return $;
        }
    }

}
