// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package net.dimeski.pulumi.dokploy.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetServerPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetServerPlainArgs Empty = new GetServerPlainArgs();

    /**
     * The ID of the existing Dokploy server to read.
     *
     */
    @Import(name="serverId", required=true)
    private String serverId;

    /**
     * @return The ID of the existing Dokploy server to read.
     *
     */
    public String serverId() {
        return this.serverId;
    }

    private GetServerPlainArgs() {}

    private GetServerPlainArgs(GetServerPlainArgs $) {
        this.serverId = $.serverId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetServerPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetServerPlainArgs $;

        public Builder() {
            $ = new GetServerPlainArgs();
        }

        public Builder(GetServerPlainArgs defaults) {
            $ = new GetServerPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param serverId The ID of the existing Dokploy server to read.
         *
         * @return builder
         *
         */
        public Builder serverId(String serverId) {
            $.serverId = serverId;
            return this;
        }

        public GetServerPlainArgs build() {
            if ($.serverId == null) {
                throw new MissingRequiredPropertyException("GetServerPlainArgs", "serverId");
            }
            return $;
        }
    }

}
