// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package net.dimeski.pulumi.dokploy.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class NotificationTeamsConfigArgs extends com.pulumi.resources.ResourceArgs {

    public static final NotificationTeamsConfigArgs Empty = new NotificationTeamsConfigArgs();

    /**
     * Secret Teams webhook URL.
     *
     */
    @Import(name="webhookUrl", required=true)
    private Output<String> webhookUrl;

    /**
     * @return Secret Teams webhook URL.
     *
     */
    public Output<String> webhookUrl() {
        return this.webhookUrl;
    }

    private NotificationTeamsConfigArgs() {}

    private NotificationTeamsConfigArgs(NotificationTeamsConfigArgs $) {
        this.webhookUrl = $.webhookUrl;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NotificationTeamsConfigArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NotificationTeamsConfigArgs $;

        public Builder() {
            $ = new NotificationTeamsConfigArgs();
        }

        public Builder(NotificationTeamsConfigArgs defaults) {
            $ = new NotificationTeamsConfigArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param webhookUrl Secret Teams webhook URL.
         *
         * @return builder
         *
         */
        public Builder webhookUrl(Output<String> webhookUrl) {
            $.webhookUrl = webhookUrl;
            return this;
        }

        /**
         * @param webhookUrl Secret Teams webhook URL.
         *
         * @return builder
         *
         */
        public Builder webhookUrl(String webhookUrl) {
            return webhookUrl(Output.of(webhookUrl));
        }

        public NotificationTeamsConfigArgs build() {
            if ($.webhookUrl == null) {
                throw new MissingRequiredPropertyException("NotificationTeamsConfigArgs", "webhookUrl");
            }
            return $;
        }
    }

}
