// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package net.dimeski.pulumi.dokploy.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class NotificationDiscordConfigArgs extends com.pulumi.resources.ResourceArgs {

    public static final NotificationDiscordConfigArgs Empty = new NotificationDiscordConfigArgs();

    /**
     * Whether to decorate messages; defaults to false.
     *
     */
    @Import(name="decoration")
    private @Nullable Output<Boolean> decoration;

    /**
     * @return Whether to decorate messages; defaults to false.
     *
     */
    public Optional<Output<Boolean>> decoration() {
        return Optional.ofNullable(this.decoration);
    }

    /**
     * Secret Discord webhook URL.
     *
     */
    @Import(name="webhookUrl", required=true)
    private Output<String> webhookUrl;

    /**
     * @return Secret Discord webhook URL.
     *
     */
    public Output<String> webhookUrl() {
        return this.webhookUrl;
    }

    private NotificationDiscordConfigArgs() {}

    private NotificationDiscordConfigArgs(NotificationDiscordConfigArgs $) {
        this.decoration = $.decoration;
        this.webhookUrl = $.webhookUrl;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NotificationDiscordConfigArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NotificationDiscordConfigArgs $;

        public Builder() {
            $ = new NotificationDiscordConfigArgs();
        }

        public Builder(NotificationDiscordConfigArgs defaults) {
            $ = new NotificationDiscordConfigArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param decoration Whether to decorate messages; defaults to false.
         *
         * @return builder
         *
         */
        public Builder decoration(@Nullable Output<Boolean> decoration) {
            $.decoration = decoration;
            return this;
        }

        /**
         * @param decoration Whether to decorate messages; defaults to false.
         *
         * @return builder
         *
         */
        public Builder decoration(Boolean decoration) {
            return decoration(Output.of(decoration));
        }

        /**
         * @param webhookUrl Secret Discord webhook URL.
         *
         * @return builder
         *
         */
        public Builder webhookUrl(Output<String> webhookUrl) {
            $.webhookUrl = webhookUrl;
            return this;
        }

        /**
         * @param webhookUrl Secret Discord webhook URL.
         *
         * @return builder
         *
         */
        public Builder webhookUrl(String webhookUrl) {
            return webhookUrl(Output.of(webhookUrl));
        }

        public NotificationDiscordConfigArgs build() {
            $.decoration = Codegen.booleanProp("decoration").output().arg($.decoration).def(false).getNullable();
            if ($.webhookUrl == null) {
                throw new MissingRequiredPropertyException("NotificationDiscordConfigArgs", "webhookUrl");
            }
            return $;
        }
    }

}
