// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package net.dimeski.pulumi.dokploy.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class NotificationPushoverConfigArgs extends com.pulumi.resources.ResourceArgs {

    public static final NotificationPushoverConfigArgs Empty = new NotificationPushoverConfigArgs();

    /**
     * Secret Pushover API token.
     *
     */
    @Import(name="apiToken", required=true)
    private Output<String> apiToken;

    /**
     * @return Secret Pushover API token.
     *
     */
    public Output<String> apiToken() {
        return this.apiToken;
    }

    /**
     * Emergency expiry in seconds, 1 through 10800; required for priority 2.
     *
     */
    @Import(name="expire")
    private @Nullable Output<Integer> expire;

    /**
     * @return Emergency expiry in seconds, 1 through 10800; required for priority 2.
     *
     */
    public Optional<Output<Integer>> expire() {
        return Optional.ofNullable(this.expire);
    }

    /**
     * Priority from -2 through 2; defaults to 0.
     *
     */
    @Import(name="priority")
    private @Nullable Output<Integer> priority;

    /**
     * @return Priority from -2 through 2; defaults to 0.
     *
     */
    public Optional<Output<Integer>> priority() {
        return Optional.ofNullable(this.priority);
    }

    /**
     * Emergency retry interval in seconds, at least 30; required for priority 2.
     *
     */
    @Import(name="retry")
    private @Nullable Output<Integer> retry;

    /**
     * @return Emergency retry interval in seconds, at least 30; required for priority 2.
     *
     */
    public Optional<Output<Integer>> retry() {
        return Optional.ofNullable(this.retry);
    }

    /**
     * Secret Pushover user key.
     *
     */
    @Import(name="userKey", required=true)
    private Output<String> userKey;

    /**
     * @return Secret Pushover user key.
     *
     */
    public Output<String> userKey() {
        return this.userKey;
    }

    private NotificationPushoverConfigArgs() {}

    private NotificationPushoverConfigArgs(NotificationPushoverConfigArgs $) {
        this.apiToken = $.apiToken;
        this.expire = $.expire;
        this.priority = $.priority;
        this.retry = $.retry;
        this.userKey = $.userKey;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NotificationPushoverConfigArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NotificationPushoverConfigArgs $;

        public Builder() {
            $ = new NotificationPushoverConfigArgs();
        }

        public Builder(NotificationPushoverConfigArgs defaults) {
            $ = new NotificationPushoverConfigArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param apiToken Secret Pushover API token.
         *
         * @return builder
         *
         */
        public Builder apiToken(Output<String> apiToken) {
            $.apiToken = apiToken;
            return this;
        }

        /**
         * @param apiToken Secret Pushover API token.
         *
         * @return builder
         *
         */
        public Builder apiToken(String apiToken) {
            return apiToken(Output.of(apiToken));
        }

        /**
         * @param expire Emergency expiry in seconds, 1 through 10800; required for priority 2.
         *
         * @return builder
         *
         */
        public Builder expire(@Nullable Output<Integer> expire) {
            $.expire = expire;
            return this;
        }

        /**
         * @param expire Emergency expiry in seconds, 1 through 10800; required for priority 2.
         *
         * @return builder
         *
         */
        public Builder expire(Integer expire) {
            return expire(Output.of(expire));
        }

        /**
         * @param priority Priority from -2 through 2; defaults to 0.
         *
         * @return builder
         *
         */
        public Builder priority(@Nullable Output<Integer> priority) {
            $.priority = priority;
            return this;
        }

        /**
         * @param priority Priority from -2 through 2; defaults to 0.
         *
         * @return builder
         *
         */
        public Builder priority(Integer priority) {
            return priority(Output.of(priority));
        }

        /**
         * @param retry Emergency retry interval in seconds, at least 30; required for priority 2.
         *
         * @return builder
         *
         */
        public Builder retry(@Nullable Output<Integer> retry) {
            $.retry = retry;
            return this;
        }

        /**
         * @param retry Emergency retry interval in seconds, at least 30; required for priority 2.
         *
         * @return builder
         *
         */
        public Builder retry(Integer retry) {
            return retry(Output.of(retry));
        }

        /**
         * @param userKey Secret Pushover user key.
         *
         * @return builder
         *
         */
        public Builder userKey(Output<String> userKey) {
            $.userKey = userKey;
            return this;
        }

        /**
         * @param userKey Secret Pushover user key.
         *
         * @return builder
         *
         */
        public Builder userKey(String userKey) {
            return userKey(Output.of(userKey));
        }

        public NotificationPushoverConfigArgs build() {
            if ($.apiToken == null) {
                throw new MissingRequiredPropertyException("NotificationPushoverConfigArgs", "apiToken");
            }
            $.priority = Codegen.integerProp("priority").output().arg($.priority).def(0).getNullable();
            if ($.userKey == null) {
                throw new MissingRequiredPropertyException("NotificationPushoverConfigArgs", "userKey");
            }
            return $;
        }
    }

}
