#!/usr/bin/env python3
"""Apply the repository's explicit CI policy to pinned CI Management output."""

import hashlib
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
WORKFLOWS = ROOT / ".github" / "workflows"
GENERATED_WORKFLOW_NAMES = (
    "build.yml", "command-dispatch.yml", "comment-on-stale-issues.yml",
    "community-moderation.yml", "export-repo-secrets.yml", "lint.yml",
    "prerelease.yml", "pull-request.yml", "release_command.yml", "release.yml",
    "run-acceptance-tests.yml", "weekly-pulumi-update.yml",
)
RELEASE_ACTION = "pulumi/action-release-by-pr-label@a90569296b805a3179b81c1860f5777073cc7aa2"
PUBLISH_GO_ACTION = "pulumi/publish-go-sdk-action@0a153fa3c54227a3c0f7c97a57033ecfe94ab3c2"
GO_VERSION = "1.25.13"
KNOWN_MISE_SHA256 = {
    "mise.toml": "6e4d48dfc6ba5bc647f8de223f35044793ae73aea8ff52f5e989a1dd597f1b08",
    "mise.test.toml": "25d93429d74aefa3c4c59cafc6c33dbbd00b1a876714855eaaadc7a6c8ded0c9",
}
BUILD_PUSH_WITH_PATHS_IGNORE = """  push:
    branches:
    - master
    - main
    - feature-**
    paths-ignore:
    - CHANGELOG.md
    tags-ignore:
    - v*
    - sdk/*
    - "**"
  pull_request: {}
"""
BUILD_PUSH_NORMALIZED = BUILD_PUSH_WITH_PATHS_IGNORE.replace(
    "    paths-ignore:\n    - CHANGELOG.md\n", ""
).replace("  pull_request: {}\n", '    - "**"\n  pull_request: {}\n')


def replace_exact(text: str, old: str, new: str) -> str:
    old_count = text.count(old)
    new_count = text.count(new)
    if old_count == 1 and new_count == 0:
        return text.replace(old, new, 1)
    if old_count == 0 and new_count == 1:
        return text
    raise SystemExit(f"expected exactly one old xor normalized pattern: old={old_count}, new={new_count}")


def exact_once(path: Path, old: str, new: str) -> None:
    path.write_text(replace_exact(path.read_text(), old, new))


def exact_optional(path: Path, old: str, new: str) -> None:
    text = path.read_text()
    old_count = text.count(old)
    new_count = text.count(new)
    if old_count == 0 and new_count == 0:
        raise SystemExit(f"expected generated pattern not found in {path}: {old!r}")
    if old_count and new_count:
        raise SystemExit(f"generated pattern is partially normalized in {path}")
    if old_count > 1 or new_count > 1:
        raise SystemExit(f"generated pattern is ambiguous in {path}")
    if old_count:
        path.write_text(text.replace(old, new, 1))


def exact_remove(path: Path, old: str) -> None:
    text = path.read_text()
    count = text.count(old)
    if count == 0:
        return
    if count != 1:
        raise SystemExit(f"expected at most one removable generated pattern: count={count}")
    path.write_text(text.replace(old, "", 1))


def normalize_build_trigger(text: str) -> str:
    return replace_exact(text, BUILD_PUSH_WITH_PATHS_IGNORE, BUILD_PUSH_NORMALIZED)


def ensure_build_pull_request(text: str) -> str:
    old = "  pull_request: {}\n"
    if text.count(old) == 0 and text.count("  workflow_dispatch: {}\n") == 1:
        return text.replace("  workflow_dispatch: {}\n", "  pull_request: {}\n  workflow_dispatch: {}\n", 1)
    if text.count(old) == 1 and text.count("  workflow_dispatch: {}\n") == 1:
        return text
    raise SystemExit("expected exactly one build pull_request/workflow_dispatch trigger state")


def insert_in_job(path: Path, job: str, marker: str, insertion: str) -> None:
    text = path.read_text()
    start = text.find(f"  {job}:\n")
    if start < 0:
        raise SystemExit(f"expected job not found in {path}: {job}")
    next_job = re.search(r"\n  [^ ]", text[start + 3 :])
    end = start + 3 + next_job.start() if next_job else len(text)
    section = text[start:end]
    if insertion in section:
        return
    if section.count(marker) != 1:
        raise SystemExit(f"expected one insertion marker in {path} job {job}")
    path.write_text(text[:start] + section.replace(marker, insertion + marker, 1) + text[end:])


def trim_explicit_outputs() -> None:
    paths = [WORKFLOWS / name for name in GENERATED_WORKFLOW_NAMES]
    paths += [ROOT / ".github" / "ISSUE_TEMPLATE" / "bug.yaml"]
    paths += [ROOT / name for name in ("CODE-OF-CONDUCT.md", "CONTRIBUTING.md", "SECURITY.md")]
    for path in paths:
        if not path.exists():
            raise SystemExit(f"expected generated output not found: {path}")
        path.write_text("\n".join(line.rstrip() for line in path.read_text().splitlines()) + "\n")


def remove_validated_generated_mise() -> None:
    header = "# WARNING: This file is autogenerated - changes will be overwritten when regenerated by https://github.com/pulumi/ci-mgmt"
    for path in (ROOT / ".config" / "mise.toml", ROOT / ".config" / "mise.test.toml"):
        if not path.exists():
            continue
        lines = path.read_text().splitlines()
        if not lines or lines[0] != header:
            raise SystemExit(f"refusing to remove unrecognized generated mise file: {path}")
        if "[tools]" not in lines:
            raise SystemExit(f"refusing to remove malformed generated mise file: {path}")
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        if digest != KNOWN_MISE_SHA256[path.name]:
            raise SystemExit(f"refusing to remove modified generated mise file: {path}")
        path.unlink()


def main() -> None:
    # These are the only generator-owned files this policy is allowed to touch.
    trim_explicit_outputs()
    remove_validated_generated_mise()
    build = WORKFLOWS / "build.yml"
    build.write_text(ensure_build_pull_request(build.read_text()))
    build.write_text(normalize_build_trigger(build.read_text()))
    exact_optional(build, "pulumi/action-release-by-pr-label@main", RELEASE_ACTION)
    gate = """    - name: Check OpenAPI and generated SDKs
      run: make check_openapi && make check_codegen
    - name: Run race tests
      run: make test_race
    - name: Build all SDKs
      run: make build_sdks
    - name: Test all examples
      run: make test_examples
    - name: Vulnerability scan
      run: make govulncheck
    - name: License scan
      run: make license
"""
    build_text = build.read_text()
    if gate not in build_text:
        marker = "    - name: Build Provider\n"
        if build_text.count(marker) != 1:
            raise SystemExit(f"expected one build insertion marker in {build}")
        build.write_text(build_text.replace(marker, gate + marker, 1))

    acceptance = WORKFLOWS / "run-acceptance-tests.yml"
    exact_remove(acceptance, "  pull_request:\n    paths-ignore:\n    - CHANGELOG.md\n")
    exact_once(
        acceptance,
        "  prerequisites:\n    runs-on:",
        "  prerequisites:\n    environment: dokploy-acceptance\n    runs-on:",
    )
    credential_step = """    - name: Require Dokploy acceptance credentials
      env:
        DOKPLOY_ENDPOINT: ${{ steps.esc-secrets.outputs.DOKPLOY_ENDPOINT }}
        DOKPLOY_API_KEY: ${{ steps.esc-secrets.outputs.DOKPLOY_API_KEY }}
      run: test -n "$DOKPLOY_ENDPOINT" && test -n "$DOKPLOY_API_KEY"
"""
    insert_in_job(acceptance, "prerequisites", "    - name: Setup Tools\n", credential_step)

    command_dispatch = WORKFLOWS / "command-dispatch.yml"
    exact_once(command_dispatch, "repository: pulumi/pulumi-dokploy", "repository: gjorgjidimeski/pulumi-dokploy")

    release_command = WORKFLOWS / "release_command.yml"
    exact_optional(release_command, "pulumi/action-release-by-pr-label@main", RELEASE_ACTION)

    release = WORKFLOWS / "release.yml"
    exact_optional(
        release,
        "args: -p 3 release --clean --timeout 60m0s",
        "args: -p 3 -f .goreleaser.yml release --clean --timeout 60m0s",
    )

    for name in ("release.yml", "prerelease.yml"):
        exact_optional(WORKFLOWS / name, "pulumi/publish-go-sdk-action@v1", PUBLISH_GO_ACTION)

    for name in (".goreleaser.yml", ".goreleaser.prerelease.yml"):
        path = ROOT / name
        exact_optional(
            path,
            "github.com/pulumi/pulumi-dokploy/provider/pkg/version.Version={{.Tag}}",
            "github.com/gjorgjidimeski/pulumi-dokploy/provider.Version={{.Tag}}",
        )

    for name in ("build.yml", "prerelease.yml", "release.yml", "run-acceptance-tests.yml", "weekly-pulumi-update.yml"):
        exact_once(WORKFLOWS / name, 'GOVERSION: "1.21.x"', f'GOVERSION: "{GO_VERSION}"')
    exact_once(
        WORKFLOWS / "lint.yml",
        """env:
  PULUMI_API: https://api.pulumi-staging.io
""",
        """env:
  GOVERSION: "1.25.13"
  PULUMI_API: https://api.pulumi-staging.io
""",
    )

    lint = ROOT / ".golangci.yml"
    exact_once(
        lint,
        """  enable:
    - goconst
    - gosec
    - lll
    - misspell
    - nakedret
    - revive
    - unconvert
""",
        """  enable: [goconst, gosec, misspell, nakedret, unconvert]
  disable: [lll, revive]
""",
    )
    exact_once(lint, """  enable:
    - gci
    - gofmt
""", """  enable:
    - gofmt
""")
    exact_once(
        lint,
        """        path: pkg/
        text: "var-naming" # https://github.com/pulumi/ci-mgmt/issues/2100
formatters:
""",
        """        path: pkg/
        text: "var-naming" # https://github.com/pulumi/ci-mgmt/issues/2100
      - linters:
          - goconst
        path: '.*_test\\.go'
formatters:
""",
    )

    if "paths-ignore:" in build.read_text() or "pull_request:" not in build.read_text():
        raise SystemExit("build workflow trigger normalization failed")
    if "pull_request:" in acceptance.read_text():
        raise SystemExit("acceptance workflow must not trigger on pull_request")


if __name__ == "__main__":
    main()
