// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumi.Dokploy.Dokploy.Inputs
{

    /// <summary>
    /// Git Compose source configuration.
    /// </summary>
    public sealed class GitComposeSourceArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The Git branch.
        /// </summary>
        [Input("branch", required: true)]
        public Input<string> Branch { get; set; } = null!;

        /// <summary>
        /// The Compose file path.
        /// </summary>
        [Input("composePath")]
        public Input<string>? ComposePath { get; set; }

        /// <summary>
        /// Whether to enable submodules.
        /// </summary>
        [Input("enableSubmodules")]
        public Input<bool>? EnableSubmodules { get; set; }

        /// <summary>
        /// The SSH key ID.
        /// </summary>
        [Input("sshKeyId")]
        public Input<string>? SshKeyId { get; set; }

        /// <summary>
        /// The Git repository URL.
        /// </summary>
        [Input("url", required: true)]
        public Input<string> Url { get; set; } = null!;

        [Input("watchPaths")]
        private InputList<string>? _watchPaths;

        /// <summary>
        /// Paths to watch.
        /// </summary>
        public InputList<string> WatchPaths
        {
            get => _watchPaths ?? (_watchPaths = new InputList<string>());
            set => _watchPaths = value;
        }

        public GitComposeSourceArgs()
        {
        }
        public static new GitComposeSourceArgs Empty => new GitComposeSourceArgs();
    }
}
