// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Dimeskigj.Pulumi.Dokploy.Inputs
{

    public sealed class NotificationNtfyConfigArgs : global::Pulumi.ResourceArgs
    {
        [Input("accessToken")]
        private Input<string>? _accessToken;

        /// <summary>
        /// Optional secret access token; defaults to empty.
        /// </summary>
        public Input<string>? AccessToken
        {
            get => _accessToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _accessToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Message priority, 1 through 5; defaults to 3.
        /// </summary>
        [Input("priority")]
        public Input<int>? Priority { get; set; }

        [Input("serverUrl", required: true)]
        private Input<string>? _serverUrl;

        /// <summary>
        /// Secret Ntfy server URL.
        /// </summary>
        public Input<string>? ServerUrl
        {
            get => _serverUrl;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _serverUrl = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Ntfy topic.
        /// </summary>
        [Input("topic", required: true)]
        public Input<string> Topic { get; set; } = null!;

        public NotificationNtfyConfigArgs()
        {
            AccessToken = "";
            Priority = 3;
        }
        public static new NotificationNtfyConfigArgs Empty => new NotificationNtfyConfigArgs();
    }
}
