// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Dimeskigj.Pulumi.Dokploy.Inputs
{

    public sealed class NotificationTeamsConfigArgs : global::Pulumi.ResourceArgs
    {
        [Input("webhookUrl", required: true)]
        private Input<string>? _webhookUrl;

        /// <summary>
        /// Secret Teams webhook URL.
        /// </summary>
        public Input<string>? WebhookUrl
        {
            get => _webhookUrl;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _webhookUrl = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public NotificationTeamsConfigArgs()
        {
        }
        public static new NotificationTeamsConfigArgs Empty => new NotificationTeamsConfigArgs();
    }
}
