// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Dimeskigj.Pulumi.Dokploy.Inputs
{

    public sealed class NotificationGotifyConfigArgs : global::Pulumi.ResourceArgs
    {
        [Input("appToken", required: true)]
        private Input<string>? _appToken;

        /// <summary>
        /// Secret Gotify application token.
        /// </summary>
        public Input<string>? AppToken
        {
            get => _appToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _appToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Whether to decorate messages; defaults to false.
        /// </summary>
        [Input("decoration")]
        public Input<bool>? Decoration { get; set; }

        /// <summary>
        /// Message priority; defaults to 5 (minimum 1).
        /// </summary>
        [Input("priority")]
        public Input<int>? Priority { get; set; }

        [Input("serverUrl", required: true)]
        private Input<string>? _serverUrl;

        /// <summary>
        /// Secret Gotify server URL.
        /// </summary>
        public Input<string>? ServerUrl
        {
            get => _serverUrl;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _serverUrl = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public NotificationGotifyConfigArgs()
        {
            Decoration = false;
            Priority = 5;
        }
        public static new NotificationGotifyConfigArgs Empty => new NotificationGotifyConfigArgs();
    }
}
