// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Dimeskigj.Pulumi.Dokploy.Inputs
{

    public sealed class NotificationDiscordConfigArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether to decorate messages; defaults to false.
        /// </summary>
        [Input("decoration")]
        public Input<bool>? Decoration { get; set; }

        [Input("webhookUrl", required: true)]
        private Input<string>? _webhookUrl;

        /// <summary>
        /// Secret Discord webhook URL.
        /// </summary>
        public Input<string>? WebhookUrl
        {
            get => _webhookUrl;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _webhookUrl = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public NotificationDiscordConfigArgs()
        {
            Decoration = false;
        }
        public static new NotificationDiscordConfigArgs Empty => new NotificationDiscordConfigArgs();
    }
}
