// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Gjorgjidimeski.Dokploy.Inputs
{

    /// <summary>
    /// GitLab Compose source configuration.
    /// </summary>
    public sealed class GitLabComposeSourceArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The GitLab branch.
        /// </summary>
        [Input("branch", required: true)]
        public Input<string> Branch { get; set; } = null!;

        /// <summary>
        /// The Compose file path.
        /// </summary>
        [Input("composePath")]
        public Input<string>? ComposePath { get; set; }

        /// <summary>
        /// Whether to enable submodules.
        /// </summary>
        [Input("enableSubmodules")]
        public Input<bool>? EnableSubmodules { get; set; }

        /// <summary>
        /// The GitLab integration ID.
        /// </summary>
        [Input("integrationId", required: true)]
        public Input<string> IntegrationId { get; set; } = null!;

        /// <summary>
        /// The GitLab namespace.
        /// </summary>
        [Input("namespace", required: true)]
        public Input<string> Namespace { get; set; } = null!;

        /// <summary>
        /// The GitLab owner.
        /// </summary>
        [Input("owner", required: true)]
        public Input<string> Owner { get; set; } = null!;

        /// <summary>
        /// The GitLab project ID.
        /// </summary>
        [Input("projectId", required: true)]
        public Input<int> ProjectId { get; set; } = null!;

        /// <summary>
        /// The GitLab repository.
        /// </summary>
        [Input("repository", required: true)]
        public Input<string> Repository { get; set; } = null!;

        [Input("watchPaths")]
        private InputList<string>? _watchPaths;

        /// <summary>
        /// Paths to watch.
        /// </summary>
        public InputList<string> WatchPaths
        {
            get => _watchPaths ?? (_watchPaths = new InputList<string>());
            set => _watchPaths = value;
        }

        public GitLabComposeSourceArgs()
        {
        }
        public static new GitLabComposeSourceArgs Empty => new GitLabComposeSourceArgs();
    }
}
