// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dokploy

import (
	"context"
	"reflect"

	"errors"
	"github.com/dimeskigj/pulumi-dokploy/sdk/go/dokploy/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A scheduled Dokploy database backup. Exactly one of postgresId, mysqlId, mariadbId, or mongoId must be set.
type Backup struct {
	pulumi.CustomResourceState

	// The stable Dokploy backup ID.
	BackupId pulumi.StringOutput `pulumi:"backupId"`
	// The database name inside the target instance to back up.
	Database pulumi.StringOutput `pulumi:"database"`
	// The destination ID backups are stored to.
	DestinationId pulumi.StringOutput `pulumi:"destinationId"`
	// Whether the backup schedule is enabled.
	Enabled pulumi.BoolOutput `pulumi:"enabled"`
	// The optional number of most recent backups to retain.
	KeepLatestCount pulumi.IntPtrOutput `pulumi:"keepLatestCount"`
	// The target MariaDB ID.
	MariadbId pulumi.StringPtrOutput `pulumi:"mariadbId"`
	// The target MongoDB ID.
	MongoId pulumi.StringPtrOutput `pulumi:"mongoId"`
	// The target MySQL ID.
	MysqlId pulumi.StringPtrOutput `pulumi:"mysqlId"`
	// The target Postgres ID.
	PostgresId pulumi.StringPtrOutput `pulumi:"postgresId"`
	// The backup file prefix.
	Prefix pulumi.StringOutput `pulumi:"prefix"`
	// The backup cron schedule.
	Schedule pulumi.StringOutput `pulumi:"schedule"`
}

// NewBackup registers a new resource with the given unique name, arguments, and options.
func NewBackup(ctx *pulumi.Context,
	name string, args *BackupArgs, opts ...pulumi.ResourceOption) (*Backup, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Database == nil {
		return nil, errors.New("invalid value for required argument 'Database'")
	}
	if args.DestinationId == nil {
		return nil, errors.New("invalid value for required argument 'DestinationId'")
	}
	if args.Prefix == nil {
		return nil, errors.New("invalid value for required argument 'Prefix'")
	}
	if args.Schedule == nil {
		return nil, errors.New("invalid value for required argument 'Schedule'")
	}
	if args.Enabled == nil {
		args.Enabled = pulumi.BoolPtr(true)
	}
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"mariadbId",
		"mongoId",
		"mysqlId",
		"postgresId",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Backup
	err := ctx.RegisterResource("dokploy:index:Backup", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetBackup gets an existing Backup resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetBackup(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *BackupState, opts ...pulumi.ResourceOption) (*Backup, error) {
	var resource Backup
	err := ctx.ReadResource("dokploy:index:Backup", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Backup resources.
type backupState struct {
}

type BackupState struct {
}

func (BackupState) ElementType() reflect.Type {
	return reflect.TypeOf((*backupState)(nil)).Elem()
}

type backupArgs struct {
	// The database name inside the target instance to back up.
	Database string `pulumi:"database"`
	// The destination ID backups are stored to.
	DestinationId string `pulumi:"destinationId"`
	// Whether the backup schedule is enabled.
	Enabled *bool `pulumi:"enabled"`
	// The optional number of most recent backups to retain.
	KeepLatestCount *int `pulumi:"keepLatestCount"`
	// The target MariaDB ID.
	MariadbId *string `pulumi:"mariadbId"`
	// The target MongoDB ID.
	MongoId *string `pulumi:"mongoId"`
	// The target MySQL ID.
	MysqlId *string `pulumi:"mysqlId"`
	// The target Postgres ID.
	PostgresId *string `pulumi:"postgresId"`
	// The backup file prefix.
	Prefix string `pulumi:"prefix"`
	// The backup cron schedule.
	Schedule string `pulumi:"schedule"`
}

// The set of arguments for constructing a Backup resource.
type BackupArgs struct {
	// The database name inside the target instance to back up.
	Database pulumi.StringInput
	// The destination ID backups are stored to.
	DestinationId pulumi.StringInput
	// Whether the backup schedule is enabled.
	Enabled pulumi.BoolPtrInput
	// The optional number of most recent backups to retain.
	KeepLatestCount pulumi.IntPtrInput
	// The target MariaDB ID.
	MariadbId pulumi.StringPtrInput
	// The target MongoDB ID.
	MongoId pulumi.StringPtrInput
	// The target MySQL ID.
	MysqlId pulumi.StringPtrInput
	// The target Postgres ID.
	PostgresId pulumi.StringPtrInput
	// The backup file prefix.
	Prefix pulumi.StringInput
	// The backup cron schedule.
	Schedule pulumi.StringInput
}

func (BackupArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*backupArgs)(nil)).Elem()
}

type BackupInput interface {
	pulumi.Input

	ToBackupOutput() BackupOutput
	ToBackupOutputWithContext(ctx context.Context) BackupOutput
}

func (*Backup) ElementType() reflect.Type {
	return reflect.TypeOf((**Backup)(nil)).Elem()
}

func (i *Backup) ToBackupOutput() BackupOutput {
	return i.ToBackupOutputWithContext(context.Background())
}

func (i *Backup) ToBackupOutputWithContext(ctx context.Context) BackupOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BackupOutput)
}

type BackupOutput struct{ *pulumi.OutputState }

func (BackupOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Backup)(nil)).Elem()
}

func (o BackupOutput) ToBackupOutput() BackupOutput {
	return o
}

func (o BackupOutput) ToBackupOutputWithContext(ctx context.Context) BackupOutput {
	return o
}

// The stable Dokploy backup ID.
func (o BackupOutput) BackupId() pulumi.StringOutput {
	return o.ApplyT(func(v *Backup) pulumi.StringOutput { return v.BackupId }).(pulumi.StringOutput)
}

// The database name inside the target instance to back up.
func (o BackupOutput) Database() pulumi.StringOutput {
	return o.ApplyT(func(v *Backup) pulumi.StringOutput { return v.Database }).(pulumi.StringOutput)
}

// The destination ID backups are stored to.
func (o BackupOutput) DestinationId() pulumi.StringOutput {
	return o.ApplyT(func(v *Backup) pulumi.StringOutput { return v.DestinationId }).(pulumi.StringOutput)
}

// Whether the backup schedule is enabled.
func (o BackupOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *Backup) pulumi.BoolOutput { return v.Enabled }).(pulumi.BoolOutput)
}

// The optional number of most recent backups to retain.
func (o BackupOutput) KeepLatestCount() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Backup) pulumi.IntPtrOutput { return v.KeepLatestCount }).(pulumi.IntPtrOutput)
}

// The target MariaDB ID.
func (o BackupOutput) MariadbId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Backup) pulumi.StringPtrOutput { return v.MariadbId }).(pulumi.StringPtrOutput)
}

// The target MongoDB ID.
func (o BackupOutput) MongoId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Backup) pulumi.StringPtrOutput { return v.MongoId }).(pulumi.StringPtrOutput)
}

// The target MySQL ID.
func (o BackupOutput) MysqlId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Backup) pulumi.StringPtrOutput { return v.MysqlId }).(pulumi.StringPtrOutput)
}

// The target Postgres ID.
func (o BackupOutput) PostgresId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Backup) pulumi.StringPtrOutput { return v.PostgresId }).(pulumi.StringPtrOutput)
}

// The backup file prefix.
func (o BackupOutput) Prefix() pulumi.StringOutput {
	return o.ApplyT(func(v *Backup) pulumi.StringOutput { return v.Prefix }).(pulumi.StringOutput)
}

// The backup cron schedule.
func (o BackupOutput) Schedule() pulumi.StringOutput {
	return o.ApplyT(func(v *Backup) pulumi.StringOutput { return v.Schedule }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*BackupInput)(nil)).Elem(), &Backup{})
	pulumi.RegisterOutputType(BackupOutput{})
}
