// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dokploy

import (
	"context"
	"reflect"

	"github.com/dimeskigj/pulumi-dokploy/sdk/go/dokploy/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Read non-secret metadata for an existing Dokploy Compose deployment by ID without managing it.
func LookupCompose(ctx *pulumi.Context, args *LookupComposeArgs, opts ...pulumi.InvokeOption) (*LookupComposeResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupComposeResult
	err := ctx.Invoke("dokploy:index:getCompose", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupComposeArgs struct {
	// The ID of the existing Dokploy Compose deployment to read.
	ComposeId string `pulumi:"composeId"`
}

type LookupComposeResult struct {
	// The optional application name metadata.
	AppName *string `pulumi:"appName"`
	// The stable Dokploy Compose ID.
	ComposeId string `pulumi:"composeId"`
	// The optional Compose type.
	ComposeType *string `pulumi:"composeType"`
	// The optional description metadata.
	Description *string `pulumi:"description"`
	// The optional environment ID metadata.
	EnvironmentId *string `pulumi:"environmentId"`
	// The Compose deployment name.
	Name string `pulumi:"name"`
	// The optional server ID metadata.
	ServerId *string `pulumi:"serverId"`
	// The optional Compose status.
	Status *string `pulumi:"status"`
}

func LookupComposeOutput(ctx *pulumi.Context, args LookupComposeOutputArgs, opts ...pulumi.InvokeOption) LookupComposeResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("dokploy:index:getCompose", args, LookupComposeResultOutput{}, options).(LookupComposeResultOutput)
}

type LookupComposeOutputArgs struct {
	// The ID of the existing Dokploy Compose deployment to read.
	ComposeId pulumi.StringInput `pulumi:"composeId"`
}

func (LookupComposeOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupComposeArgs)(nil)).Elem()
}

type LookupComposeResultOutput struct{ *pulumi.OutputState }

func (LookupComposeResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupComposeResult)(nil)).Elem()
}

func (o LookupComposeResultOutput) ToLookupComposeResultOutput() LookupComposeResultOutput {
	return o
}

func (o LookupComposeResultOutput) ToLookupComposeResultOutputWithContext(ctx context.Context) LookupComposeResultOutput {
	return o
}

// The optional application name metadata.
func (o LookupComposeResultOutput) AppName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupComposeResult) *string { return v.AppName }).(pulumi.StringPtrOutput)
}

// The stable Dokploy Compose ID.
func (o LookupComposeResultOutput) ComposeId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComposeResult) string { return v.ComposeId }).(pulumi.StringOutput)
}

// The optional Compose type.
func (o LookupComposeResultOutput) ComposeType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupComposeResult) *string { return v.ComposeType }).(pulumi.StringPtrOutput)
}

// The optional description metadata.
func (o LookupComposeResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupComposeResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// The optional environment ID metadata.
func (o LookupComposeResultOutput) EnvironmentId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupComposeResult) *string { return v.EnvironmentId }).(pulumi.StringPtrOutput)
}

// The Compose deployment name.
func (o LookupComposeResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupComposeResult) string { return v.Name }).(pulumi.StringOutput)
}

// The optional server ID metadata.
func (o LookupComposeResultOutput) ServerId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupComposeResult) *string { return v.ServerId }).(pulumi.StringPtrOutput)
}

// The optional Compose status.
func (o LookupComposeResultOutput) Status() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupComposeResult) *string { return v.Status }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupComposeResultOutput{})
}
