// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dokploy

import (
	"context"
	"reflect"

	"github.com/dimeskigj/pulumi-dokploy/sdk/go/dokploy/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Read non-secret metadata for an existing Dokploy MongoDB database by ID without managing it.
func LookupMongoDB(ctx *pulumi.Context, args *LookupMongoDBArgs, opts ...pulumi.InvokeOption) (*LookupMongoDBResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupMongoDBResult
	err := ctx.Invoke("dokploy:index:getMongoDB", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupMongoDBArgs struct {
	// The ID of the existing Dokploy MongoDB database to read.
	MongoId string `pulumi:"mongoId"`
}

type LookupMongoDBResult struct {
	// The optional application name metadata.
	AppName *string `pulumi:"appName"`
	// The optional database username metadata.
	DatabaseUser *string `pulumi:"databaseUser"`
	// The optional description metadata.
	Description *string `pulumi:"description"`
	// The optional Docker image metadata.
	DockerImage *string `pulumi:"dockerImage"`
	// The optional environment ID metadata.
	EnvironmentId *string `pulumi:"environmentId"`
	// The optional external port.
	ExternalPort *int `pulumi:"externalPort"`
	// The stable Dokploy MongoDB ID.
	MongoId string `pulumi:"mongoId"`
	// The MongoDB database name.
	Name string `pulumi:"name"`
	// Whether replica sets are enabled, if supplied.
	ReplicaSets *bool `pulumi:"replicaSets"`
	// The optional server ID metadata.
	ServerId *string `pulumi:"serverId"`
	// The optional application status.
	Status *string `pulumi:"status"`
}

func LookupMongoDBOutput(ctx *pulumi.Context, args LookupMongoDBOutputArgs, opts ...pulumi.InvokeOption) LookupMongoDBResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("dokploy:index:getMongoDB", args, LookupMongoDBResultOutput{}, options).(LookupMongoDBResultOutput)
}

type LookupMongoDBOutputArgs struct {
	// The ID of the existing Dokploy MongoDB database to read.
	MongoId pulumi.StringInput `pulumi:"mongoId"`
}

func (LookupMongoDBOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupMongoDBArgs)(nil)).Elem()
}

type LookupMongoDBResultOutput struct{ *pulumi.OutputState }

func (LookupMongoDBResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupMongoDBResult)(nil)).Elem()
}

func (o LookupMongoDBResultOutput) ToLookupMongoDBResultOutput() LookupMongoDBResultOutput {
	return o
}

func (o LookupMongoDBResultOutput) ToLookupMongoDBResultOutputWithContext(ctx context.Context) LookupMongoDBResultOutput {
	return o
}

// The optional application name metadata.
func (o LookupMongoDBResultOutput) AppName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupMongoDBResult) *string { return v.AppName }).(pulumi.StringPtrOutput)
}

// The optional database username metadata.
func (o LookupMongoDBResultOutput) DatabaseUser() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupMongoDBResult) *string { return v.DatabaseUser }).(pulumi.StringPtrOutput)
}

// The optional description metadata.
func (o LookupMongoDBResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupMongoDBResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// The optional Docker image metadata.
func (o LookupMongoDBResultOutput) DockerImage() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupMongoDBResult) *string { return v.DockerImage }).(pulumi.StringPtrOutput)
}

// The optional environment ID metadata.
func (o LookupMongoDBResultOutput) EnvironmentId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupMongoDBResult) *string { return v.EnvironmentId }).(pulumi.StringPtrOutput)
}

// The optional external port.
func (o LookupMongoDBResultOutput) ExternalPort() pulumi.IntPtrOutput {
	return o.ApplyT(func(v LookupMongoDBResult) *int { return v.ExternalPort }).(pulumi.IntPtrOutput)
}

// The stable Dokploy MongoDB ID.
func (o LookupMongoDBResultOutput) MongoId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMongoDBResult) string { return v.MongoId }).(pulumi.StringOutput)
}

// The MongoDB database name.
func (o LookupMongoDBResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMongoDBResult) string { return v.Name }).(pulumi.StringOutput)
}

// Whether replica sets are enabled, if supplied.
func (o LookupMongoDBResultOutput) ReplicaSets() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupMongoDBResult) *bool { return v.ReplicaSets }).(pulumi.BoolPtrOutput)
}

// The optional server ID metadata.
func (o LookupMongoDBResultOutput) ServerId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupMongoDBResult) *string { return v.ServerId }).(pulumi.StringPtrOutput)
}

// The optional application status.
func (o LookupMongoDBResultOutput) Status() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupMongoDBResult) *string { return v.Status }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupMongoDBResultOutput{})
}
