// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dokploy

import (
	"context"
	"reflect"

	"github.com/dimeskigj/pulumi-dokploy/sdk/go/dokploy/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Read non-secret metadata for an existing Dokploy MySQL database by ID without managing it.
func LookupMySQL(ctx *pulumi.Context, args *LookupMySQLArgs, opts ...pulumi.InvokeOption) (*LookupMySQLResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupMySQLResult
	err := ctx.Invoke("dokploy:index:getMySQL", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupMySQLArgs struct {
	// The ID of the existing Dokploy MySQL database to read.
	MysqlId string `pulumi:"mysqlId"`
}

type LookupMySQLResult struct {
	// The optional application name metadata.
	AppName *string `pulumi:"appName"`
	// The optional database name metadata.
	DatabaseName *string `pulumi:"databaseName"`
	// The optional database username metadata.
	DatabaseUser *string `pulumi:"databaseUser"`
	// The optional description metadata.
	Description *string `pulumi:"description"`
	// The optional Docker image metadata.
	DockerImage *string `pulumi:"dockerImage"`
	// The optional environment ID metadata.
	EnvironmentId *string `pulumi:"environmentId"`
	// The optional external port.
	ExternalPort *int `pulumi:"externalPort"`
	// The stable Dokploy MySQL ID.
	MysqlId string `pulumi:"mysqlId"`
	// The MySQL database name.
	Name string `pulumi:"name"`
	// The optional server ID metadata.
	ServerId *string `pulumi:"serverId"`
	// The optional application status.
	Status *string `pulumi:"status"`
}

func LookupMySQLOutput(ctx *pulumi.Context, args LookupMySQLOutputArgs, opts ...pulumi.InvokeOption) LookupMySQLResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("dokploy:index:getMySQL", args, LookupMySQLResultOutput{}, options).(LookupMySQLResultOutput)
}

type LookupMySQLOutputArgs struct {
	// The ID of the existing Dokploy MySQL database to read.
	MysqlId pulumi.StringInput `pulumi:"mysqlId"`
}

func (LookupMySQLOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupMySQLArgs)(nil)).Elem()
}

type LookupMySQLResultOutput struct{ *pulumi.OutputState }

func (LookupMySQLResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupMySQLResult)(nil)).Elem()
}

func (o LookupMySQLResultOutput) ToLookupMySQLResultOutput() LookupMySQLResultOutput {
	return o
}

func (o LookupMySQLResultOutput) ToLookupMySQLResultOutputWithContext(ctx context.Context) LookupMySQLResultOutput {
	return o
}

// The optional application name metadata.
func (o LookupMySQLResultOutput) AppName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupMySQLResult) *string { return v.AppName }).(pulumi.StringPtrOutput)
}

// The optional database name metadata.
func (o LookupMySQLResultOutput) DatabaseName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupMySQLResult) *string { return v.DatabaseName }).(pulumi.StringPtrOutput)
}

// The optional database username metadata.
func (o LookupMySQLResultOutput) DatabaseUser() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupMySQLResult) *string { return v.DatabaseUser }).(pulumi.StringPtrOutput)
}

// The optional description metadata.
func (o LookupMySQLResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupMySQLResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// The optional Docker image metadata.
func (o LookupMySQLResultOutput) DockerImage() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupMySQLResult) *string { return v.DockerImage }).(pulumi.StringPtrOutput)
}

// The optional environment ID metadata.
func (o LookupMySQLResultOutput) EnvironmentId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupMySQLResult) *string { return v.EnvironmentId }).(pulumi.StringPtrOutput)
}

// The optional external port.
func (o LookupMySQLResultOutput) ExternalPort() pulumi.IntPtrOutput {
	return o.ApplyT(func(v LookupMySQLResult) *int { return v.ExternalPort }).(pulumi.IntPtrOutput)
}

// The stable Dokploy MySQL ID.
func (o LookupMySQLResultOutput) MysqlId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMySQLResult) string { return v.MysqlId }).(pulumi.StringOutput)
}

// The MySQL database name.
func (o LookupMySQLResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMySQLResult) string { return v.Name }).(pulumi.StringOutput)
}

// The optional server ID metadata.
func (o LookupMySQLResultOutput) ServerId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupMySQLResult) *string { return v.ServerId }).(pulumi.StringPtrOutput)
}

// The optional application status.
func (o LookupMySQLResultOutput) Status() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupMySQLResult) *string { return v.Status }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupMySQLResultOutput{})
}
