// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dokploy

import (
	"context"
	"reflect"

	"github.com/dimeskigj/pulumi-dokploy/sdk/go/dokploy/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Read non-secret metadata for an existing Dokploy registry by ID without managing it.
func LookupRegistry(ctx *pulumi.Context, args *LookupRegistryArgs, opts ...pulumi.InvokeOption) (*LookupRegistryResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupRegistryResult
	err := ctx.Invoke("dokploy:index:getRegistry", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupRegistryArgs struct {
	// The ID of the existing Dokploy registry to read.
	RegistryId string `pulumi:"registryId"`
}

type LookupRegistryResult struct {
	// The optional image prefix metadata.
	ImagePrefix *string `pulumi:"imagePrefix"`
	// The registry name.
	Name string `pulumi:"name"`
	// The stable Dokploy registry ID.
	RegistryId string `pulumi:"registryId"`
	// The optional registry type metadata.
	RegistryType *string `pulumi:"registryType"`
	// The optional server ID metadata.
	ServerId *string `pulumi:"serverId"`
	// The optional URL metadata.
	Url *string `pulumi:"url"`
	// The optional username metadata.
	Username *string `pulumi:"username"`
}

func LookupRegistryOutput(ctx *pulumi.Context, args LookupRegistryOutputArgs, opts ...pulumi.InvokeOption) LookupRegistryResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("dokploy:index:getRegistry", args, LookupRegistryResultOutput{}, options).(LookupRegistryResultOutput)
}

type LookupRegistryOutputArgs struct {
	// The ID of the existing Dokploy registry to read.
	RegistryId pulumi.StringInput `pulumi:"registryId"`
}

func (LookupRegistryOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupRegistryArgs)(nil)).Elem()
}

type LookupRegistryResultOutput struct{ *pulumi.OutputState }

func (LookupRegistryResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupRegistryResult)(nil)).Elem()
}

func (o LookupRegistryResultOutput) ToLookupRegistryResultOutput() LookupRegistryResultOutput {
	return o
}

func (o LookupRegistryResultOutput) ToLookupRegistryResultOutputWithContext(ctx context.Context) LookupRegistryResultOutput {
	return o
}

// The optional image prefix metadata.
func (o LookupRegistryResultOutput) ImagePrefix() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupRegistryResult) *string { return v.ImagePrefix }).(pulumi.StringPtrOutput)
}

// The registry name.
func (o LookupRegistryResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRegistryResult) string { return v.Name }).(pulumi.StringOutput)
}

// The stable Dokploy registry ID.
func (o LookupRegistryResultOutput) RegistryId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRegistryResult) string { return v.RegistryId }).(pulumi.StringOutput)
}

// The optional registry type metadata.
func (o LookupRegistryResultOutput) RegistryType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupRegistryResult) *string { return v.RegistryType }).(pulumi.StringPtrOutput)
}

// The optional server ID metadata.
func (o LookupRegistryResultOutput) ServerId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupRegistryResult) *string { return v.ServerId }).(pulumi.StringPtrOutput)
}

// The optional URL metadata.
func (o LookupRegistryResultOutput) Url() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupRegistryResult) *string { return v.Url }).(pulumi.StringPtrOutput)
}

// The optional username metadata.
func (o LookupRegistryResultOutput) Username() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupRegistryResult) *string { return v.Username }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupRegistryResultOutput{})
}
