// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dokploy

import (
	"context"
	"reflect"

	"github.com/dimeskigj/pulumi-dokploy/sdk/go/dokploy/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Read non-secret metadata for an existing Dokploy SSH key by ID without managing it.
func LookupSSHKey(ctx *pulumi.Context, args *LookupSSHKeyArgs, opts ...pulumi.InvokeOption) (*LookupSSHKeyResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSSHKeyResult
	err := ctx.Invoke("dokploy:index:getSSHKey", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupSSHKeyArgs struct {
	// The ID of the existing Dokploy SSH key to read.
	SshKeyId string `pulumi:"sshKeyId"`
}

type LookupSSHKeyResult struct {
	// The optional description metadata.
	Description *string `pulumi:"description"`
	// The SSH key name.
	Name string `pulumi:"name"`
	// The optional organization ID metadata.
	OrganizationId *string `pulumi:"organizationId"`
	// The optional public key metadata.
	PublicKey *string `pulumi:"publicKey"`
	// The stable Dokploy SSH key ID.
	SshKeyId string `pulumi:"sshKeyId"`
}

func LookupSSHKeyOutput(ctx *pulumi.Context, args LookupSSHKeyOutputArgs, opts ...pulumi.InvokeOption) LookupSSHKeyResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("dokploy:index:getSSHKey", args, LookupSSHKeyResultOutput{}, options).(LookupSSHKeyResultOutput)
}

type LookupSSHKeyOutputArgs struct {
	// The ID of the existing Dokploy SSH key to read.
	SshKeyId pulumi.StringInput `pulumi:"sshKeyId"`
}

func (LookupSSHKeyOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSSHKeyArgs)(nil)).Elem()
}

type LookupSSHKeyResultOutput struct{ *pulumi.OutputState }

func (LookupSSHKeyResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSSHKeyResult)(nil)).Elem()
}

func (o LookupSSHKeyResultOutput) ToLookupSSHKeyResultOutput() LookupSSHKeyResultOutput {
	return o
}

func (o LookupSSHKeyResultOutput) ToLookupSSHKeyResultOutputWithContext(ctx context.Context) LookupSSHKeyResultOutput {
	return o
}

// The optional description metadata.
func (o LookupSSHKeyResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupSSHKeyResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// The SSH key name.
func (o LookupSSHKeyResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSSHKeyResult) string { return v.Name }).(pulumi.StringOutput)
}

// The optional organization ID metadata.
func (o LookupSSHKeyResultOutput) OrganizationId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupSSHKeyResult) *string { return v.OrganizationId }).(pulumi.StringPtrOutput)
}

// The optional public key metadata.
func (o LookupSSHKeyResultOutput) PublicKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupSSHKeyResult) *string { return v.PublicKey }).(pulumi.StringPtrOutput)
}

// The stable Dokploy SSH key ID.
func (o LookupSSHKeyResultOutput) SshKeyId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSSHKeyResult) string { return v.SshKeyId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSSHKeyResultOutput{})
}
