// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dokploy

import (
	"context"
	"reflect"

	"errors"
	"github.com/dimeskigj/pulumi-dokploy/sdk/go/dokploy/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A Dokploy application port mapping.
type Port struct {
	pulumi.CustomResourceState

	// The Dokploy application ID.
	ApplicationId pulumi.StringOutput `pulumi:"applicationId"`
	// Stable Dokploy port ID.
	PortId pulumi.StringOutput `pulumi:"portId"`
	// The port protocol: tcp or udp.
	Protocol PortProtocolOutput `pulumi:"protocol"`
	// The port publish mode: ingress or host.
	PublishMode PortPublishModeOutput `pulumi:"publishMode"`
	// The externally published port (1-65535).
	PublishedPort pulumi.IntOutput `pulumi:"publishedPort"`
	// The application target port (1-65535).
	TargetPort pulumi.IntOutput `pulumi:"targetPort"`
}

// NewPort registers a new resource with the given unique name, arguments, and options.
func NewPort(ctx *pulumi.Context,
	name string, args *PortArgs, opts ...pulumi.ResourceOption) (*Port, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ApplicationId == nil {
		return nil, errors.New("invalid value for required argument 'ApplicationId'")
	}
	if args.PublishedPort == nil {
		return nil, errors.New("invalid value for required argument 'PublishedPort'")
	}
	if args.TargetPort == nil {
		return nil, errors.New("invalid value for required argument 'TargetPort'")
	}
	if args.Protocol == nil {
		args.Protocol = PortProtocol("tcp")
	}
	if args.PublishMode == nil {
		args.PublishMode = PortPublishMode("ingress")
	}
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"applicationId",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Port
	err := ctx.RegisterResource("dokploy:index:Port", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPort gets an existing Port resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPort(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PortState, opts ...pulumi.ResourceOption) (*Port, error) {
	var resource Port
	err := ctx.ReadResource("dokploy:index:Port", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Port resources.
type portState struct {
}

type PortState struct {
}

func (PortState) ElementType() reflect.Type {
	return reflect.TypeOf((*portState)(nil)).Elem()
}

type portArgs struct {
	// The Dokploy application ID.
	ApplicationId string `pulumi:"applicationId"`
	// The port protocol: tcp or udp.
	Protocol *PortProtocol `pulumi:"protocol"`
	// The port publish mode: ingress or host.
	PublishMode *PortPublishMode `pulumi:"publishMode"`
	// The externally published port (1-65535).
	PublishedPort int `pulumi:"publishedPort"`
	// The application target port (1-65535).
	TargetPort int `pulumi:"targetPort"`
}

// The set of arguments for constructing a Port resource.
type PortArgs struct {
	// The Dokploy application ID.
	ApplicationId pulumi.StringInput
	// The port protocol: tcp or udp.
	Protocol PortProtocolPtrInput
	// The port publish mode: ingress or host.
	PublishMode PortPublishModePtrInput
	// The externally published port (1-65535).
	PublishedPort pulumi.IntInput
	// The application target port (1-65535).
	TargetPort pulumi.IntInput
}

func (PortArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*portArgs)(nil)).Elem()
}

type PortInput interface {
	pulumi.Input

	ToPortOutput() PortOutput
	ToPortOutputWithContext(ctx context.Context) PortOutput
}

func (*Port) ElementType() reflect.Type {
	return reflect.TypeOf((**Port)(nil)).Elem()
}

func (i *Port) ToPortOutput() PortOutput {
	return i.ToPortOutputWithContext(context.Background())
}

func (i *Port) ToPortOutputWithContext(ctx context.Context) PortOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PortOutput)
}

type PortOutput struct{ *pulumi.OutputState }

func (PortOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Port)(nil)).Elem()
}

func (o PortOutput) ToPortOutput() PortOutput {
	return o
}

func (o PortOutput) ToPortOutputWithContext(ctx context.Context) PortOutput {
	return o
}

// The Dokploy application ID.
func (o PortOutput) ApplicationId() pulumi.StringOutput {
	return o.ApplyT(func(v *Port) pulumi.StringOutput { return v.ApplicationId }).(pulumi.StringOutput)
}

// Stable Dokploy port ID.
func (o PortOutput) PortId() pulumi.StringOutput {
	return o.ApplyT(func(v *Port) pulumi.StringOutput { return v.PortId }).(pulumi.StringOutput)
}

// The port protocol: tcp or udp.
func (o PortOutput) Protocol() PortProtocolOutput {
	return o.ApplyT(func(v *Port) PortProtocolOutput { return v.Protocol }).(PortProtocolOutput)
}

// The port publish mode: ingress or host.
func (o PortOutput) PublishMode() PortPublishModeOutput {
	return o.ApplyT(func(v *Port) PortPublishModeOutput { return v.PublishMode }).(PortPublishModeOutput)
}

// The externally published port (1-65535).
func (o PortOutput) PublishedPort() pulumi.IntOutput {
	return o.ApplyT(func(v *Port) pulumi.IntOutput { return v.PublishedPort }).(pulumi.IntOutput)
}

// The application target port (1-65535).
func (o PortOutput) TargetPort() pulumi.IntOutput {
	return o.ApplyT(func(v *Port) pulumi.IntOutput { return v.TargetPort }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PortInput)(nil)).Elem(), &Port{})
	pulumi.RegisterOutputType(PortOutput{})
}
