// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dokploy

import (
	"context"
	"reflect"

	"errors"
	"github.com/dimeskigj/pulumi-dokploy/sdk/go/dokploy/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A Dokploy scheduled command.
type Schedule struct {
	pulumi.CustomResourceState

	// Optional application name.
	AppName pulumi.StringPtrOutput `pulumi:"appName"`
	// Target application ID.
	ApplicationId pulumi.StringPtrOutput `pulumi:"applicationId"`
	// Command executed by the schedule.
	Command pulumi.StringOutput `pulumi:"command"`
	// Target Compose ID.
	ComposeId pulumi.StringPtrOutput `pulumi:"composeId"`
	// Cron expression for the schedule.
	CronExpression pulumi.StringOutput `pulumi:"cronExpression"`
	// Optional schedule description.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Whether the schedule is enabled; defaults to false.
	Enabled pulumi.BoolOutput `pulumi:"enabled"`
	// Schedule name.
	Name pulumi.StringOutput `pulumi:"name"`
	// Dokploy organization ID.
	OrganizationId pulumi.StringPtrOutput `pulumi:"organizationId"`
	// Stable Dokploy schedule ID.
	ScheduleId pulumi.StringOutput `pulumi:"scheduleId"`
	// Schedule target type: application, compose, server, or dokploy-server.
	ScheduleType pulumi.StringOutput `pulumi:"scheduleType"`
	// Optional script executed by the schedule.
	Script pulumi.StringPtrOutput `pulumi:"script"`
	// Target server ID.
	ServerId pulumi.StringPtrOutput `pulumi:"serverId"`
	// Optional Compose service name.
	ServiceName pulumi.StringPtrOutput `pulumi:"serviceName"`
	// Shell used to execute the command (bash or sh).
	ShellType pulumi.StringPtrOutput `pulumi:"shellType"`
	// Timezone for the schedule.
	Timezone pulumi.StringPtrOutput `pulumi:"timezone"`
}

// NewSchedule registers a new resource with the given unique name, arguments, and options.
func NewSchedule(ctx *pulumi.Context,
	name string, args *ScheduleArgs, opts ...pulumi.ResourceOption) (*Schedule, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Command == nil {
		return nil, errors.New("invalid value for required argument 'Command'")
	}
	if args.CronExpression == nil {
		return nil, errors.New("invalid value for required argument 'CronExpression'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.ScheduleType == nil {
		return nil, errors.New("invalid value for required argument 'ScheduleType'")
	}
	if args.Enabled == nil {
		args.Enabled = pulumi.BoolPtr(false)
	}
	if args.Command != nil {
		args.Command = pulumi.ToSecret(args.Command).(pulumi.StringInput)
	}
	if args.Script != nil {
		args.Script = pulumi.ToSecret(args.Script).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"command",
		"script",
	})
	opts = append(opts, secrets)
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"appName",
		"applicationId",
		"composeId",
		"scheduleType",
		"serverId",
		"serviceName",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Schedule
	err := ctx.RegisterResource("dokploy:index:Schedule", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSchedule gets an existing Schedule resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSchedule(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ScheduleState, opts ...pulumi.ResourceOption) (*Schedule, error) {
	var resource Schedule
	err := ctx.ReadResource("dokploy:index:Schedule", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Schedule resources.
type scheduleState struct {
}

type ScheduleState struct {
}

func (ScheduleState) ElementType() reflect.Type {
	return reflect.TypeOf((*scheduleState)(nil)).Elem()
}

type scheduleArgs struct {
	// Optional application name.
	AppName *string `pulumi:"appName"`
	// Target application ID.
	ApplicationId *string `pulumi:"applicationId"`
	// Command executed by the schedule.
	Command string `pulumi:"command"`
	// Target Compose ID.
	ComposeId *string `pulumi:"composeId"`
	// Cron expression for the schedule.
	CronExpression string `pulumi:"cronExpression"`
	// Optional schedule description.
	Description *string `pulumi:"description"`
	// Whether the schedule is enabled; defaults to false.
	Enabled *bool `pulumi:"enabled"`
	// Schedule name.
	Name string `pulumi:"name"`
	// Dokploy organization ID.
	OrganizationId *string `pulumi:"organizationId"`
	// Schedule target type: application, compose, server, or dokploy-server.
	ScheduleType string `pulumi:"scheduleType"`
	// Optional script executed by the schedule.
	Script *string `pulumi:"script"`
	// Target server ID.
	ServerId *string `pulumi:"serverId"`
	// Optional Compose service name.
	ServiceName *string `pulumi:"serviceName"`
	// Shell used to execute the command (bash or sh).
	ShellType *string `pulumi:"shellType"`
	// Timezone for the schedule.
	Timezone *string `pulumi:"timezone"`
}

// The set of arguments for constructing a Schedule resource.
type ScheduleArgs struct {
	// Optional application name.
	AppName pulumi.StringPtrInput
	// Target application ID.
	ApplicationId pulumi.StringPtrInput
	// Command executed by the schedule.
	Command pulumi.StringInput
	// Target Compose ID.
	ComposeId pulumi.StringPtrInput
	// Cron expression for the schedule.
	CronExpression pulumi.StringInput
	// Optional schedule description.
	Description pulumi.StringPtrInput
	// Whether the schedule is enabled; defaults to false.
	Enabled pulumi.BoolPtrInput
	// Schedule name.
	Name pulumi.StringInput
	// Dokploy organization ID.
	OrganizationId pulumi.StringPtrInput
	// Schedule target type: application, compose, server, or dokploy-server.
	ScheduleType pulumi.StringInput
	// Optional script executed by the schedule.
	Script pulumi.StringPtrInput
	// Target server ID.
	ServerId pulumi.StringPtrInput
	// Optional Compose service name.
	ServiceName pulumi.StringPtrInput
	// Shell used to execute the command (bash or sh).
	ShellType pulumi.StringPtrInput
	// Timezone for the schedule.
	Timezone pulumi.StringPtrInput
}

func (ScheduleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*scheduleArgs)(nil)).Elem()
}

type ScheduleInput interface {
	pulumi.Input

	ToScheduleOutput() ScheduleOutput
	ToScheduleOutputWithContext(ctx context.Context) ScheduleOutput
}

func (*Schedule) ElementType() reflect.Type {
	return reflect.TypeOf((**Schedule)(nil)).Elem()
}

func (i *Schedule) ToScheduleOutput() ScheduleOutput {
	return i.ToScheduleOutputWithContext(context.Background())
}

func (i *Schedule) ToScheduleOutputWithContext(ctx context.Context) ScheduleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ScheduleOutput)
}

type ScheduleOutput struct{ *pulumi.OutputState }

func (ScheduleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Schedule)(nil)).Elem()
}

func (o ScheduleOutput) ToScheduleOutput() ScheduleOutput {
	return o
}

func (o ScheduleOutput) ToScheduleOutputWithContext(ctx context.Context) ScheduleOutput {
	return o
}

// Optional application name.
func (o ScheduleOutput) AppName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringPtrOutput { return v.AppName }).(pulumi.StringPtrOutput)
}

// Target application ID.
func (o ScheduleOutput) ApplicationId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringPtrOutput { return v.ApplicationId }).(pulumi.StringPtrOutput)
}

// Command executed by the schedule.
func (o ScheduleOutput) Command() pulumi.StringOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringOutput { return v.Command }).(pulumi.StringOutput)
}

// Target Compose ID.
func (o ScheduleOutput) ComposeId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringPtrOutput { return v.ComposeId }).(pulumi.StringPtrOutput)
}

// Cron expression for the schedule.
func (o ScheduleOutput) CronExpression() pulumi.StringOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringOutput { return v.CronExpression }).(pulumi.StringOutput)
}

// Optional schedule description.
func (o ScheduleOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Whether the schedule is enabled; defaults to false.
func (o ScheduleOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *Schedule) pulumi.BoolOutput { return v.Enabled }).(pulumi.BoolOutput)
}

// Schedule name.
func (o ScheduleOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Dokploy organization ID.
func (o ScheduleOutput) OrganizationId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringPtrOutput { return v.OrganizationId }).(pulumi.StringPtrOutput)
}

// Stable Dokploy schedule ID.
func (o ScheduleOutput) ScheduleId() pulumi.StringOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringOutput { return v.ScheduleId }).(pulumi.StringOutput)
}

// Schedule target type: application, compose, server, or dokploy-server.
func (o ScheduleOutput) ScheduleType() pulumi.StringOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringOutput { return v.ScheduleType }).(pulumi.StringOutput)
}

// Optional script executed by the schedule.
func (o ScheduleOutput) Script() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringPtrOutput { return v.Script }).(pulumi.StringPtrOutput)
}

// Target server ID.
func (o ScheduleOutput) ServerId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringPtrOutput { return v.ServerId }).(pulumi.StringPtrOutput)
}

// Optional Compose service name.
func (o ScheduleOutput) ServiceName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringPtrOutput { return v.ServiceName }).(pulumi.StringPtrOutput)
}

// Shell used to execute the command (bash or sh).
func (o ScheduleOutput) ShellType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringPtrOutput { return v.ShellType }).(pulumi.StringPtrOutput)
}

// Timezone for the schedule.
func (o ScheduleOutput) Timezone() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringPtrOutput { return v.Timezone }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ScheduleInput)(nil)).Elem(), &Schedule{})
	pulumi.RegisterOutputType(ScheduleOutput{})
}
