// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A Dokploy domain routing rule.
 */
export class Domain extends pulumi.CustomResource {
    /**
     * Get an existing Domain resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Domain {
        return new Domain(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'dokploy:index:Domain';

    /**
     * Returns true if the given object is an instance of Domain.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Domain {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Domain.__pulumiType;
    }

    /**
     * The optional application ID target.
     */
    declare public readonly applicationId: pulumi.Output<string | undefined>;
    /**
     * The certificate resolver type.
     */
    declare public readonly certificateType: pulumi.Output<string>;
    /**
     * The optional Compose ID target.
     */
    declare public readonly composeId: pulumi.Output<string | undefined>;
    /**
     * The custom certificate resolver.
     */
    declare public readonly customCertResolver: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly domainId: pulumi.Output<string>;
    /**
     * Whether the domain is enabled.
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * The domain hostname.
     */
    declare public readonly host: pulumi.Output<string>;
    /**
     * Whether HTTPS is enabled.
     */
    declare public readonly https: pulumi.Output<boolean>;
    /**
     * The internal URL path.
     */
    declare public readonly internalPath: pulumi.Output<string | undefined>;
    /**
     * The public URL path.
     */
    declare public readonly path: pulumi.Output<string | undefined>;
    /**
     * The target port.
     */
    declare public readonly port: pulumi.Output<number | undefined>;
    /**
     * The Compose service name.
     */
    declare public readonly serviceName: pulumi.Output<string | undefined>;
    /**
     * Whether to strip the public path.
     */
    declare public readonly stripPath: pulumi.Output<boolean | undefined>;

    /**
     * Create a Domain resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DomainArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.host === undefined && !opts.urn) {
                throw new Error("Missing required property 'host'");
            }
            resourceInputs["applicationId"] = args?.applicationId;
            resourceInputs["certificateType"] = (args?.certificateType) ?? "letsencrypt";
            resourceInputs["composeId"] = args?.composeId;
            resourceInputs["customCertResolver"] = args?.customCertResolver;
            resourceInputs["enabled"] = (args?.enabled) ?? true;
            resourceInputs["host"] = args?.host;
            resourceInputs["https"] = (args?.https) ?? true;
            resourceInputs["internalPath"] = args?.internalPath;
            resourceInputs["path"] = args?.path;
            resourceInputs["port"] = args?.port;
            resourceInputs["serviceName"] = args?.serviceName;
            resourceInputs["stripPath"] = args?.stripPath;
            resourceInputs["domainId"] = undefined /*out*/;
        } else {
            resourceInputs["applicationId"] = undefined /*out*/;
            resourceInputs["certificateType"] = undefined /*out*/;
            resourceInputs["composeId"] = undefined /*out*/;
            resourceInputs["customCertResolver"] = undefined /*out*/;
            resourceInputs["domainId"] = undefined /*out*/;
            resourceInputs["enabled"] = undefined /*out*/;
            resourceInputs["host"] = undefined /*out*/;
            resourceInputs["https"] = undefined /*out*/;
            resourceInputs["internalPath"] = undefined /*out*/;
            resourceInputs["path"] = undefined /*out*/;
            resourceInputs["port"] = undefined /*out*/;
            resourceInputs["serviceName"] = undefined /*out*/;
            resourceInputs["stripPath"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const replaceOnChanges = { replaceOnChanges: ["applicationId", "composeId", "serviceName"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(Domain.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Domain resource.
 */
export interface DomainArgs {
    /**
     * The optional application ID target.
     */
    applicationId?: pulumi.Input<string | undefined>;
    /**
     * The certificate resolver type.
     */
    certificateType?: pulumi.Input<string | undefined>;
    /**
     * The optional Compose ID target.
     */
    composeId?: pulumi.Input<string | undefined>;
    /**
     * The custom certificate resolver.
     */
    customCertResolver?: pulumi.Input<string | undefined>;
    /**
     * Whether the domain is enabled.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * The domain hostname.
     */
    host: pulumi.Input<string>;
    /**
     * Whether HTTPS is enabled.
     */
    https?: pulumi.Input<boolean | undefined>;
    /**
     * The internal URL path.
     */
    internalPath?: pulumi.Input<string | undefined>;
    /**
     * The public URL path.
     */
    path?: pulumi.Input<string | undefined>;
    /**
     * The target port.
     */
    port?: pulumi.Input<number | undefined>;
    /**
     * The Compose service name.
     */
    serviceName?: pulumi.Input<string | undefined>;
    /**
     * Whether to strip the public path.
     */
    stripPath?: pulumi.Input<boolean | undefined>;
}
