// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Read non-secret metadata for an existing Dokploy Compose deployment by ID without managing it.
 */
export function getCompose(args: GetComposeArgs, opts?: pulumi.InvokeOptions): Promise<GetComposeResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("dokploy:index:getCompose", {
        "composeId": args.composeId,
    }, opts);
}

export interface GetComposeArgs {
    /**
     * The ID of the existing Dokploy Compose deployment to read.
     */
    composeId: string;
}

export interface GetComposeResult {
    /**
     * The optional application name metadata.
     */
    readonly appName?: string;
    /**
     * The stable Dokploy Compose ID.
     */
    readonly composeId: string;
    /**
     * The optional Compose type.
     */
    readonly composeType?: string;
    /**
     * The optional description metadata.
     */
    readonly description?: string;
    /**
     * The optional environment ID metadata.
     */
    readonly environmentId?: string;
    /**
     * The Compose deployment name.
     */
    readonly name: string;
    /**
     * The optional server ID metadata.
     */
    readonly serverId?: string;
    /**
     * The optional Compose status.
     */
    readonly status?: string;
}
/**
 * Read non-secret metadata for an existing Dokploy Compose deployment by ID without managing it.
 */
export function getComposeOutput(args: GetComposeOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetComposeResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("dokploy:index:getCompose", {
        "composeId": args.composeId,
    }, opts);
}

export interface GetComposeOutputArgs {
    /**
     * The ID of the existing Dokploy Compose deployment to read.
     */
    composeId: pulumi.Input<string>;
}
