// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Read non-secret metadata for an existing Dokploy Postgres database by ID without managing it.
 */
export function getPostgres(args: GetPostgresArgs, opts?: pulumi.InvokeOptions): Promise<GetPostgresResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("dokploy:index:getPostgres", {
        "postgresId": args.postgresId,
    }, opts);
}

export interface GetPostgresArgs {
    /**
     * The ID of the existing Dokploy Postgres database to read.
     */
    postgresId: string;
}

export interface GetPostgresResult {
    /**
     * The optional application name metadata.
     */
    readonly appName?: string;
    /**
     * The optional database name metadata.
     */
    readonly databaseName?: string;
    /**
     * The optional database username metadata.
     */
    readonly databaseUser?: string;
    /**
     * The optional description metadata.
     */
    readonly description?: string;
    /**
     * The optional Docker image metadata.
     */
    readonly dockerImage?: string;
    /**
     * The optional environment ID metadata.
     */
    readonly environmentId?: string;
    /**
     * The optional external port.
     */
    readonly externalPort?: number;
    /**
     * The Postgres database name.
     */
    readonly name: string;
    /**
     * The stable Dokploy Postgres ID.
     */
    readonly postgresId: string;
    /**
     * The optional server ID metadata.
     */
    readonly serverId?: string;
    /**
     * The optional application status.
     */
    readonly status?: string;
}
/**
 * Read non-secret metadata for an existing Dokploy Postgres database by ID without managing it.
 */
export function getPostgresOutput(args: GetPostgresOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPostgresResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("dokploy:index:getPostgres", {
        "postgresId": args.postgresId,
    }, opts);
}

export interface GetPostgresOutputArgs {
    /**
     * The ID of the existing Dokploy Postgres database to read.
     */
    postgresId: pulumi.Input<string>;
}
