// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Read non-secret metadata for an existing Dokploy registry by ID without managing it.
 */
export function getRegistry(args: GetRegistryArgs, opts?: pulumi.InvokeOptions): Promise<GetRegistryResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("dokploy:index:getRegistry", {
        "registryId": args.registryId,
    }, opts);
}

export interface GetRegistryArgs {
    /**
     * The ID of the existing Dokploy registry to read.
     */
    registryId: string;
}

export interface GetRegistryResult {
    /**
     * The optional image prefix metadata.
     */
    readonly imagePrefix?: string;
    /**
     * The registry name.
     */
    readonly name: string;
    /**
     * The stable Dokploy registry ID.
     */
    readonly registryId: string;
    /**
     * The optional registry type metadata.
     */
    readonly registryType?: string;
    /**
     * The optional server ID metadata.
     */
    readonly serverId?: string;
    /**
     * The optional URL metadata.
     */
    readonly url?: string;
    /**
     * The optional username metadata.
     */
    readonly username?: string;
}
/**
 * Read non-secret metadata for an existing Dokploy registry by ID without managing it.
 */
export function getRegistryOutput(args: GetRegistryOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRegistryResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("dokploy:index:getRegistry", {
        "registryId": args.registryId,
    }, opts);
}

export interface GetRegistryOutputArgs {
    /**
     * The ID of the existing Dokploy registry to read.
     */
    registryId: pulumi.Input<string>;
}
