// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { ApplicationArgs } from "./application";
export type Application = import("./application").Application;
export const Application: typeof import("./application").Application = null as any;
utilities.lazyLoad(exports, ["Application"], () => require("./application"));

export { BackupArgs } from "./backup";
export type Backup = import("./backup").Backup;
export const Backup: typeof import("./backup").Backup = null as any;
utilities.lazyLoad(exports, ["Backup"], () => require("./backup"));

export { ComposeArgs } from "./compose";
export type Compose = import("./compose").Compose;
export const Compose: typeof import("./compose").Compose = null as any;
utilities.lazyLoad(exports, ["Compose"], () => require("./compose"));

export { DestinationArgs } from "./destination";
export type Destination = import("./destination").Destination;
export const Destination: typeof import("./destination").Destination = null as any;
utilities.lazyLoad(exports, ["Destination"], () => require("./destination"));

export { DomainArgs } from "./domain";
export type Domain = import("./domain").Domain;
export const Domain: typeof import("./domain").Domain = null as any;
utilities.lazyLoad(exports, ["Domain"], () => require("./domain"));

export { EnvironmentArgs } from "./environment";
export type Environment = import("./environment").Environment;
export const Environment: typeof import("./environment").Environment = null as any;
utilities.lazyLoad(exports, ["Environment"], () => require("./environment"));

export { MariaDBArgs } from "./mariaDB";
export type MariaDB = import("./mariaDB").MariaDB;
export const MariaDB: typeof import("./mariaDB").MariaDB = null as any;
utilities.lazyLoad(exports, ["MariaDB"], () => require("./mariaDB"));

export { MongoDBArgs } from "./mongoDB";
export type MongoDB = import("./mongoDB").MongoDB;
export const MongoDB: typeof import("./mongoDB").MongoDB = null as any;
utilities.lazyLoad(exports, ["MongoDB"], () => require("./mongoDB"));

export { MountArgs } from "./mount";
export type Mount = import("./mount").Mount;
export const Mount: typeof import("./mount").Mount = null as any;
utilities.lazyLoad(exports, ["Mount"], () => require("./mount"));

export { MySQLArgs } from "./mySQL";
export type MySQL = import("./mySQL").MySQL;
export const MySQL: typeof import("./mySQL").MySQL = null as any;
utilities.lazyLoad(exports, ["MySQL"], () => require("./mySQL"));

export { PostgresArgs } from "./postgres";
export type Postgres = import("./postgres").Postgres;
export const Postgres: typeof import("./postgres").Postgres = null as any;
utilities.lazyLoad(exports, ["Postgres"], () => require("./postgres"));

export { ProjectArgs } from "./project";
export type Project = import("./project").Project;
export const Project: typeof import("./project").Project = null as any;
utilities.lazyLoad(exports, ["Project"], () => require("./project"));

export { ProjectTagArgs } from "./projectTag";
export type ProjectTag = import("./projectTag").ProjectTag;
export const ProjectTag: typeof import("./projectTag").ProjectTag = null as any;
utilities.lazyLoad(exports, ["ProjectTag"], () => require("./projectTag"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { RedisArgs } from "./redis";
export type Redis = import("./redis").Redis;
export const Redis: typeof import("./redis").Redis = null as any;
utilities.lazyLoad(exports, ["Redis"], () => require("./redis"));

export { RegistryArgs } from "./registry";
export type Registry = import("./registry").Registry;
export const Registry: typeof import("./registry").Registry = null as any;
utilities.lazyLoad(exports, ["Registry"], () => require("./registry"));

export { SSHKeyArgs } from "./sshkey";
export type SSHKey = import("./sshkey").SSHKey;
export const SSHKey: typeof import("./sshkey").SSHKey = null as any;
utilities.lazyLoad(exports, ["SSHKey"], () => require("./sshkey"));

export { TagArgs } from "./tag";
export type Tag = import("./tag").Tag;
export const Tag: typeof import("./tag").Tag = null as any;
utilities.lazyLoad(exports, ["Tag"], () => require("./tag"));

export { VolumeBackupArgs } from "./volumeBackup";
export type VolumeBackup = import("./volumeBackup").VolumeBackup;
export const VolumeBackup: typeof import("./volumeBackup").VolumeBackup = null as any;
utilities.lazyLoad(exports, ["VolumeBackup"], () => require("./volumeBackup"));


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "dokploy:index:Application":
                return new Application(name, <any>undefined, { urn })
            case "dokploy:index:Backup":
                return new Backup(name, <any>undefined, { urn })
            case "dokploy:index:Compose":
                return new Compose(name, <any>undefined, { urn })
            case "dokploy:index:Destination":
                return new Destination(name, <any>undefined, { urn })
            case "dokploy:index:Domain":
                return new Domain(name, <any>undefined, { urn })
            case "dokploy:index:Environment":
                return new Environment(name, <any>undefined, { urn })
            case "dokploy:index:MariaDB":
                return new MariaDB(name, <any>undefined, { urn })
            case "dokploy:index:MongoDB":
                return new MongoDB(name, <any>undefined, { urn })
            case "dokploy:index:Mount":
                return new Mount(name, <any>undefined, { urn })
            case "dokploy:index:MySQL":
                return new MySQL(name, <any>undefined, { urn })
            case "dokploy:index:Postgres":
                return new Postgres(name, <any>undefined, { urn })
            case "dokploy:index:Project":
                return new Project(name, <any>undefined, { urn })
            case "dokploy:index:ProjectTag":
                return new ProjectTag(name, <any>undefined, { urn })
            case "dokploy:index:Redis":
                return new Redis(name, <any>undefined, { urn })
            case "dokploy:index:Registry":
                return new Registry(name, <any>undefined, { urn })
            case "dokploy:index:SSHKey":
                return new SSHKey(name, <any>undefined, { urn })
            case "dokploy:index:Tag":
                return new Tag(name, <any>undefined, { urn })
            case "dokploy:index:VolumeBackup":
                return new VolumeBackup(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("dokploy", "index", _module)
pulumi.runtime.registerResourcePackage("dokploy", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:dokploy") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
